### ISSUE TITLE
ASP.NET MVC Adapter required for utilizing DI 

### ISSUE THREAD

**Issue by BillKrat** [unitycontainer/unity#1]
The ASP.NET MVC 5/6 requires an adapter for integrating external IOC container, currently only Autofac provides one.  I created a "poor mans" adapter (until you release one) and blog on the topic [HERE](http://www.global-webnet.com/blog/post/2015/08/24/Dependency-Injection-in-ASPNET-vNext-%28adding-Unity-container%29.aspx) - would be great to have one for Unity.   From what I'm seeing this would call for you to migrate all of the default container registrations into a Unity container ([Autofac](https://github.com/autofac/Autofac) does this in a Populate method).

**Comment by pcibraro** [comment]
Thanks for the feedback. We are working on this. Expect a new release soon.

**Comment by ENikS** [comment]
https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection/
