### ISSUE TITLE
Preview version of Unity 5

### ISSUE THREAD

**Issue by dersia** [unitycontainer/unity#101]
first of all thanks for picking up this old code and refactoring it to new standards.

That said, can we create an preview version of 5.0.0 and push it to nuget? As far as I've seen there is just one open issue left in the milestones for 5.0.

Thanks again for your work!

**Comment by ENikS** [comment]
https://www.nuget.org/packages/CommonServiceLocator/
https://www.nuget.org/packages/Unity/5.0.0-alpha
https://www.nuget.org/packages/Unity.Configuration/
https://www.nuget.org/packages/Unity.Interception/5.0.0-alpha
https://www.nuget.org/packages/Unity.Interception.Configuration/
https://www.nuget.org/packages/Unity.ServiceLocation/
