### ISSUE TITLE
EnterpriseLibrary PolicyInjectionSettings and Unity 4.0 update compilation error

### ISSUE THREAD

**Issue by ahedreville** [unitycontainer/unity#11]
I have update to Unity 4.0 and the code below gives me a compilation error with Enterprise Library 6

var container = new UnityContainer();

var policyInjectionSettings = (PolicyInjectionSettings)source.GetSection(PolicyInjectionSettings.SectionName); policyInjectionSettings.ConfigureContainer(container);

The compilation error is: Enterprise Library The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly Microsoft.Practices.Unity, Version=3.0.0.0

Can some one help me?

Thanks in advance

**Comment by pcibraro** [comment]
Could you please try with the nuget package version 4.0.1 ?. A missing dependency was detected in 4.0.0

Thanks

**Comment by ahedreville** [comment]
I I had updated to 4.0.1 and still have the same issue 
I had attached the picture and listed below the packages.config

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="net46" />
  <package id="EnterpriseLibrary.Common" version="6.0.1304.0" targetFramework="net452" />
  <package id="EnterpriseLibrary.ExceptionHandling" version="6.0.1304.0" targetFramework="net452" />
  <package id="EnterpriseLibrary.PolicyInjection" version="6.0.1304.0" targetFramework="net452" />
  <package id="PostSharp" version="4.1.26" targetFramework="net46" />
  <package id="Unity" version="4.0.1" targetFramework="net46" />
  <package id="Unity.Interception" version="4.0.1" targetFramework="net46" />
</packages>

![snap13](https://cloud.githubusercontent.com/assets/7416613/10471068/908276e2-7212-11e5-948c-d5339a71d714.png)

**Comment by pcibraro** [comment]
The assembly strong name signature has changed in 4.0.0 and 4.0.1. It looks like you still have some dependency with 3.0.0 somewhere. Could you see if you are referencing the incorrect assembly in a config file (in the assembly redirect bindings) ?.

Thanks
Pablo.

**Comment by ahedreville** [comment]
Hi
I had started a blank project from zero, with unity 3 and Enterprise 6. 
And I get it compiled successfully

As soon I had update it to unity 4.0
the syntax parser show an error and the build fails

I tried to "patch" the app.config
but this not solve the issue

Here below the onedrive shared project

https://onedrive.live.com/redir?resid=37ADAF528B4FF16B!211631&authkey=!AGSTYPeEHiYlX_U&ithint=file%2crar

**Comment by ahedreville** [comment]
Even with on a brand simple console application with only those lines I get that error when I update it from Unity 3.5 to Unity 4.0

The compilation error is: Enterprise Library The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly Microsoft.Practices.Unity, Version=3.0.0.0
I have the problem ONLY when the Unity Package is updated to 4.0 or later, on version 3.5 works fine
I had tried to “patch” the app.config bindingRedirect sections, but no success, still same failure

**** example code below ****

Program.cs
using Microsoft.Practices.EnterpriseLibrary.Common.Configuration;
using Microsoft.Practices.EnterpriseLibrary.PolicyInjection.Configuration;
using Microsoft.Practices.Unity;
 
namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var source = ConfigurationSourceFactory.Create();
 
            IUnityContainer container = new UnityContainer();
 
            var policyInjectionSettings = (PolicyInjectionSettings)source.GetSection(PolicyInjectionSettings.SectionName);
 
            policyInjectionSettings.ConfigureContainer(container);
        }
    }
}

Pakages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="net46" />
  <package id="EnterpriseLibrary.Common" version="6.0.1304.0" targetFramework="net45" />
  <package id="EnterpriseLibrary.PolicyInjection" version="6.0.1304.0" targetFramework="net45" />
  <package id="Unity" version="4.0.1" targetFramework="net46" />
  <package id="Unity.Interception" version="4.0.1" targetFramework="net46" />
</packages>

App.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.ServiceLocation" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Unity" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="4.0.0.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Unity.Configuration" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="4.0.0.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Unity.Interception" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="4.0.0.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by ahedreville** [comment]
Hi. I had recompiled the PIAB package [here](http://piab.codeplex.com) upgrading the Unity packages and the new dll (Microsoft.Practices.EnterpriseLibrary.PolicyInjection.dll) works!!. So indeed the owners of package should update the Nugget Package to Unity 4.0
