### ISSUE TITLE
ResolutionFailedException not serializable

### ISSUE THREAD

**Issue by stefanbie** [unitycontainer/unity#116]
Hi
I have a Web Performance and Load Test Project where I use Unity 4.0.1. When I execute a load test I get an error that ResolutionFailedException is not serializable. I downloaded the source code , added [Serializable] to the constructor, compiled and used the dll as a reference instead and it worked fine. Would it be possible to add it to the code?

BR Stefan

**Comment by ENikS** [comment]
There are more that hundred classes and constructors. Which one are you talking about?

**Comment by stefanbie** [comment]
Hi Eugene, thanks for the quick feedback :) What I meant was that the ResolutionFailedException **class** needs to be serializable, i.e.

```
[Serializable]
[SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors",
Justification = "The standard constructors don't make sense for this exception, as calling them will leave out the information that makes the exception useful in the first place.")]
    public partial class ResolutionFailedException : Exception
{....
```

Sorry for the confusion.

BR Stefan

**Comment by stefanbie** [comment]
btw, this is the error message that I get:

Test Error	TestError	7	Unit Test Adapter threw exception: 
Type 'Microsoft.Practices.Unity.ResolutionFailedException' in assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' is not marked as serializable..

**Comment by stefanbie** [comment]
Good question, it has to be related to the way Microsoft runs loadtests. I am able to execute the code separately (outside a load test) without serialization but when I put it in a load test it fails.

**Comment by ENikS** [comment]
I am unable to patch 4.0.1. The original signing certificate is lost and anything I release has to be in 5.0.0.
It will be a while before I do 5.0.0 so you are better off with your local copy for now. But I'll add these in v5.

**Comment by stefanbie** [comment]
Thanks :)

**Comment by ENikS** [comment]
Fixed in Unity.Abstractions v2.0.0-beta1
