### ISSUE TITLE
Port MSDN documentation to GitHub

### ISSUE THREAD

**Issue by eugbaranov** [unitycontainer/unity#117]
Most recent Unity documentation is for version 3 which is not longer maintained on MSDN: [Unity 3 – April 2013](https://msdn.microsoft.com/en-us/library/dn170416.aspx).

It would be great to port that to GitHub using [GitHub Pages](https://pages.github.com/) (as a starting point).

**Comment by ENikS** [comment]
Would you like to help with that?

**Comment by Regent** [comment]
I'd like to, not sure how much time will I have to spare but this might be a starting point: #118 
Thanks for resurrecting the project, by the way!

**Comment by ENikS** [comment]
You might want to update things like this ``Microsoft Unity 3 contains the following:`` to reference latest...

**Comment by GJ2** [comment]
I'm specialised in webscraping, I can make a copy of the documentation if you want

**Comment by Regent** [comment]
Can it be converted to Markdown in the process?

**Comment by ENikS** [comment]
Would appreciate any help in this regard. 

I was hoping to utilize [docfx](https://github.com/dotnet/docfx) to generate Reference documentation but converting original docs into GitHub site would be excellent start.

We might want to contact original authors to secure permission as well...

**Comment by axelgenus** [comment]
[Here](http://download.microsoft.com/download/4/D/B/4DBC771D-9E24-4211-ADC5-65812115E52D/DependencyInjectionWithUnity.pdf) you can find the book PDF about Unity. I can try exporting it to HTML and then to Markdown.

**Comment by ENikS** [comment]
I've seen it in html somewhere. It should be easier than pdf conversion.

**Comment by axelgenus** [comment]
Well, I tried to convert that PDF [here](http://pdf2md.morethan.io/) and it comes out quite well. Obviously it needs some love but it can be done. In HTML format I only found the official MS Tech web page... we can copy/paste it in a GitHub Wiki or a GitHub Page. Also it needs updating. Anyway it is a long work...

**Comment by axelgenus** [comment]
Oh, I also found a CHM file!

**Comment by ENikS** [comment]
You could use [this repe](https://github.com/unitycontainer/unitycontainer.github.io) to add the docs

**Comment by ENikS** [comment]
Gentlemen, I've created [this](https://github.com/unitycontainer/documentation) project to host all documentation related sources. 

The [https://unitycontainer.github.io](https://unitycontainer.github.io/api/index.html) site hosts API documentation derived from source comments and quite detailed. 

You could start contributing to the cause by simply following **Improve this Doc** links on pages...

**Comment by axelgenus** [comment]
Good job @ENikS. In the meanwhile I wrote a converter to get Markdown from the CHM documentation. It works and it misses only the TOC and the index. I will put online today, maybe tomorrow. Alas the documentation I found is about Unity 3.0 so I guess that is going to be updated although it is a good starting point.

**Comment by axelgenus** [comment]
Here it is: https://axelgenus.gitbooks.io/unity-container. It has some rough edges (expecially around tables) and it needs to be reviewed and updated but it's a start. Anyone intrested in helping out is welcomed.

**Comment by ENikS** [comment]
Excellent work Alessandro!! It looks like we are getting somewhere. I love what you did with the [gitbook](https://axelgenus.gitbooks.io/unity-container/)! 

I think we should consolidate all documentation under http://unitycontainer.github.io. The markdown you used for the book could go into [Articles](https://github.com/unitycontainer/documentation/tree/master/articles) directory in [Documentation](https://github.com/unitycontainer/documentation) repository. This is where it will be picked up and compiled into html for the site. 'Articles' is default name of the section the tool generated, we could call it 'Guides' or something...

I am still not very proficient with the tool but you could read about it for yourself [here](https://github.com/dotnet/docfx).

**Comment by axelgenus** [comment]
I would like to give it a full review before publishing it. ;)

**Comment by ENikS** [comment]
Of course, but I wouldn't mind publishing it with note stating that verification is needed and allow more people to participate. There is a link on each page which contributors could use to improve documents.

**Comment by axelgenus** [comment]
Ok then, I am fixing the layout of the documents (I already reviewed the layout of 40% of the pages).

For now I used the presentation by Chris Tavares as README.md but we can replace it with our own and move it back to where it was (before the introduction). As soon as I finish I will provide the PR to include the guide in the main project repo.

Just a side node: [the original guide](https://msdn.microsoft.com/en-us/library/dn223671(v=pandp.30).aspx) seems to be still [selling on Amazon](https://www.amazon.com/gp/product/1621140288/ref=as_li_tf_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1621140288&linkCode=as2&tag=drgrimel-20). Do we have the permission to re-publish it? The [copyright](https://axelgenus.gitbooks.io/unity-container/content/guide-Unity30-201304_0a7ad0ef-6ad9-4ded-b7bd-9b733eef528a.html) page on the guide itself says "_You may copy and use this document for your internal, reference purposes_".

**Comment by ENikS** [comment]
I think we can only use it as a guide for the new description. 

The help file might be different though. If it was released by Microsoft under the same license as the code we could use it without limitations.

**Comment by sdg002** [comment]
Hello All, Please help me understand why is the XML specification for Unity considered to be deprecated?  I have been using XML files for loading up Unity and it works brilliantly well. Not just that , the XML file also serves as a place where I can initialize the property values of our custom objects . e.g. Connection strings to Azure storage container  

I understand that there are many who prefer a strongly typed approach and do the bootstrapping through code. 

Just trying to understand if there is a design paradigm that I have missed. 


Thanks,
Saurabh

**Comment by ENikS** [comment]
The XML speck is still the same. You could use old docs to configure your container. Nothing has changed.

**Comment by ENikS** [comment]
As reference: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/index

**Comment by alexagranov7** [comment]
Is there Unity API reference here or it's not been ported yet?

**Comment by ENikS** [comment]
I've been busy with writing code mostly, didn't have much time for anything else. Waiting for volunteers to port the documentation. Do you want to help?

**Comment by alexagranov7** [comment]
> I've been busy with writing code mostly, didn't have much time for anything else. Waiting for volunteers to port the documentation. Do you want to help?

I wouldn't mind to help, but would need technical direction on where to begin. I tried to clone the wiki git and that didn't succeed.
![image](https://user-images.githubusercontent.com/28403336/52760004-cc582380-2fc2-11e9-8cac-8a50501e79d5.png)

**Comment by ENikS** [comment]
I would be happy to provide any info and answer any questions you might have.

**Comment by alexagranov7** [comment]
Is the intent to port the Microsoft.Practices.Unity Namespace from: 
[Microsoft.Practices.Unity Namespace](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ee650325%28v%3dpandp.10%29)

I've found many broken or circular links there.

**Comment by ENikS** [comment]
I've updated [Documentation project](https://github.com/unitycontainer/documentation) to reference latest version of Unity. Building the project produces [this site](https://unitycontainer.github.io/index.html)

We should use this project to port all documentation.

**Comment by henderni** [comment]
I might be able to throw some time at this. We use Unity in a number of projects and it would be a good exercise for me to learn more about how Unity and IoC containers work in general. Somebody point me in a direction and I'd be happy to start porting the referenced v3 code.

**Comment by ENikS** [comment]
I am forking on v5 container documentation. If you could port docs for configuration or interception it would be a big help

**Comment by henderni** [comment]
Sounds good. I'll fork the documentation project and start cleaning up those two.
