### ISSUE TITLE
How to Inject in WCF ?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [unitycontainer/unity#12]
Prior to the new version (4.0) i could use Unity.WCF for DI in my WCF-services. Due to breaking change in version number that is not an option if i upgrade. Is there are new more convinient way of using DI in WCF, or should I persue the author of Unity.WCF på realease an upgrade ?

Best regards
Thorvald

**Comment by pcibraro** [comment]
Let me convince the author to see if we can upgrade and contribute the library to this github repo

**Comment by ThorvaldAagaard** [comment]
Thank you. The code looks exactly Like the recommended way so otherwise I
Will just makeup a copy.

Thorvald Aagaard
Den 08/10/2015 12.37 skrev "Pablo Cibraro" <notifications@github.com>:

**Comment by ENikS** [comment]
https://msdn.microsoft.com/en-us/library/aa390359(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/aa394611(v=vs.85).aspx

**Comment by ViceIce** [comment]
Hi, I'm currently the owner of [Unity.Wcf](https://www.nuget.org/packages/Unity.Wcf/).

We can move the code from [Me](/ViceIce/unity.wcf) to your organisation. I can give you access to the nuget package.

Regards
Michael

**Comment by ENikS** [comment]
Michael, 

It would be nice if you could do that.

**Comment by ViceIce** [comment]
Who should get owner rights for the unity.wcf package?

You are free to clone my repository to your org or do i have any move rights? 😄 
Should i give you owner rights to my repo to?

**Comment by ENikS** [comment]
It all depends if you still want to work on the repository. You could add move it into unitycontainer organisation but you could still be owner of the repo.

**Comment by ViceIce** [comment]
Ok, lets move it to unitycontainer org. I can then fork that, if i need to.

I can help to improve if there are some wishes.

**Comment by ViceIce** [comment]
@ENikS I saw you forked [wcf](https://github.com/unitycontainer/wcf).

I think issues should be enabled.
The readme should be updated:
* add appveyor badges
* remove changes

**Comment by ENikS** [comment]
@ViceIce  Enabled Wiki and Issues. 
You've got write access in that project, feel free to contribute :)
