### ISSUE TITLE
Merge CommonServiceLocator to main repository/NuGet

### ISSUE THREAD

**Issue by Regent** [unitycontainer/unity#120]
I don't think it makes much sense to keep CommonServiceLocator in a standalone repository/NuGet package.

Can we have everything in just one Git repository/NuGet package?

Also, there are currently lots of small Git repositories, e.g. Configuration, Interception, etc.
I think this would complicate things in a long run and if anything will add unnecessary management overhead  - is there some future strategy for that splitting?

**Comment by ENikS** [comment]
Yes. At present all packages depend on each other and if one of them is updated you need to update them all.

I am planning to separate them into independent packages with different release cycles. It does not make sense to update Unity.ServiceLocation, for example, if Unity.Container has changed. 

I would like to follow a pattern were Unity.Abstractions is the only package users need to link to and it never changes so upgrades to Unity itself do not require refactoring consumer code.

**Comment by Regent** [comment]
It makes sense in .NET to have separate packages for each namespace since each adds independent functionality.

With Unity, e.g. Unity.Configuration/Interception have no value unless used with main assembly.

One of the appealing Unity features is that you don't need to reference dozens of packages to start using it (with ServiceLocator being annoyance for many developers). It also helps with better feature discoverability in my opinion.

Not sure how having separate Unity.Abstractions solves anything easier - to avoid need of refactoring existing interface methods should simply remain unchanged.

**Comment by ENikS** [comment]
Well, consider this configuration experimental. If it creates any negative impact on the project I could always change it back to one solid package.

Since I am the only one who suffers from  ``unnecessary management`` associated with this division I am OK to leave it as is.

**Comment by Regent** [comment]
Sure. Although I would argue what it is not overhead just - anyone referencing would have to maintain references to different NuGet packages too, ensure versions are compatible, etc.
Anyone trying to contribute/raise an issue will have to decide which repository it should go to.

**Comment by ENikS** [comment]
So far there were not that many people who had any issues with it :)

**Comment by ENikS** [comment]
I am just about to do major restructuring of the main repository. If you want to continue with your contributions there is an 'experimental' branch with all the latest. I will merge it to main later...
