### ISSUE TITLE
Potential not thread-safe behaviour in SynchronizedLifetimeManager

### ISSUE THREAD

**Issue by pbaravik** [unitycontainer/unity#121]
To my mind the code of the method SynchronizedLifetimeManager.GetValue() contains potentially unsafe code:

```
public override object GetValue()
{    
  Monitor.Enter(this.lockObj);    
  object obj2 = this.SynchronizedGetValue();    
  if (obj2 != null)    
  {
    Monitor.Exit(this.lockObj);    
  }    
  return obj2;
}
```

The scenario might be the following:
* the thread captures the lock object 
* SynchronizedGetValue() returns null 
  * I did not find that Recovery would be called if null resolved and thus sync block remains captured
* the thread leaves Unity code 
* the thread is terminated for any reason
* the deadlock situation will take place.

Sample output of WinDbg SOS extensions deadlock analysis (real case):

0:045> !dlk
Examining SyncBlocks...
Scanning for ReaderWriterLock(Slim) instances...
Scanning for holders of ReaderWriterLock locks...
Scanning for holders of ReaderWriterLockSlim locks...
Examining CriticalSections...
Scanning for threads waiting on SyncBlocks...
Scanning for threads waiting on ReaderWriterLock locks...
Scanning for threads waiting on ReaderWriterLocksSlim locks...
Scanning for threads waiting on CriticalSections...
*DEADLOCK DETECTED*
CLR Thread 0x14 is waiting for orphaned SyncBlock 0000000012a3f508 OBJ:000000037f47c750[System.Object]
The lock was orphaned by CLR thread 0x2ef, which has since terminated.
CLR Thread 0x14 is waiting at Microsoft.Practices.Unity.SynchronizedLifetimeManager.GetValue()(+0xb IL,+0x12 Native)

1 deadlock detected.

**Comment by ENikS** [comment]
Yes, the whole SynchronizedGetValue() is kind of fishy.  I still have very vague idea how it works and why is it required. If you have suggestion how this could be improved I would love to hear it.

**Comment by ENikS** [comment]
Moving to unitycontainer/container#22
