### ISSUE TITLE
Does the unity associated with Microsoft Enterprise Library 6update to support.Netstandard 2, asp.net core 2?

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/unity#123]
Does the unity associated with Microsoft Enterprise Library 6update to support.Netstandard 2, asp.net core 2?

**Comment by ENikS** [comment]
Unity is not associated with Enterprise Library anymore but it does support .NET Standard 1.0 & 2.0, Core 1+ and latest frameworks.

**Comment by ghd258** [comment]
Microsoft Enterprise Library 6 update to support.Netstandard 2, asp.net core 2?

**Comment by ENikS** [comment]
I do not know.
