### ISSUE TITLE
Missing PerRequestLifetimeManager in Unity 5.0

### ISSUE THREAD

**Issue by axelgenus** [unitycontainer/unity#124]
I upgraded my project from Unity 4.0.1 to 5.0 this morning. Everything went smooth (namespace changes caused 99,9% of the build-time issues), except now I cannot find the PerRequestLifetimeManager which I used before. Has it been removed? What alternative do I get?

PS: I just remembered that that lifetime manager is in the Unity.MVC package and not the main one... is MVC 5 still going to be supported?

**Comment by ENikS** [comment]
You are right, it is indeed missing and I wasn't planning to port MVC package.
I am working on Unity.Microsoft.Extension.DependencyInjection package for all new web based development.

If you think MVC is still required we could add it. If you could convert it to new format and submit a pull request even better.

**Comment by axelgenus** [comment]
I am doing it on a separate repo and I am going to publish them as "compatibility" packages. Unfortunately ASP.NET WebAPI 2.2 and ASP.NET MVC 5 packages are not .NET Standard compliant (only net45 libs are available) so I guess it is better to handle them apart from the main project. I will align the version numbers according to Unity version.

https://github.com/axelgenus/unity-compat

**Comment by ENikS** [comment]
If you are willing to help I could extract original code from v4.0.1 into MVC repo and let you convert it to 5.0.0 API. Once I merge your pull request I will publish these normally as part of Unity library?

**Comment by axelgenus** [comment]
I already did that. I just committed the base code upgraded to Unity 5.0. I tested in my web app and it seems to work just fine. Anyhow, it would be nice to give a hand since I work with it. ;)

**Comment by axelgenus** [comment]
.NET Core has an unified way to resolve dependencies and I am not really that into .NET Core yet but yes, basically it would be good to offer a solution either for old ASP.NET MVC/WebApi and for .NET Core.

**Comment by ENikS** [comment]
I would like to follow same structure as the rest of the repos: tests, package configs and automatic deployment. 
Let me create these repos tonight and we'll start from there

**Comment by ENikS** [comment]
Deployed, it was actually much simpler than what I anticipated

**Comment by axelgenus** [comment]
Perfect. Thank you. Will you also release them as NuGet packages?

PS: My offer still stands: if you need a hand I am available. ;)

**Comment by ENikS** [comment]
It is released already: https://www.nuget.org/packages/Unity.Mvc/

**Comment by ENikS** [comment]
I do need help with [this](https://github.com/unitycontainer/registration-by-convention/blob/master/src/AllClasses.NetCore.cs). If you can help with it would be great.

**Comment by axelgenus** [comment]
Perfect, thank you. I will take a look at that next week.

**Comment by mohamedabdeen** [comment]
IF i install Unity.MVC, i have to remove unity package from my project, also i will use it in WCF project to create new container every request. 

My WCF project is based on entity framework 6.2 + repository pattern.
