### ISSUE TITLE
Missing CLS compliance

### ISSUE THREAD

**Issue by Ichizaki** [unitycontainer/unity#125]
CLS compliance changed between version 4.0.1 and 5.0.0.

My project depends on Unity v4.0.1 requires CLS compliance (assembly level 'CLSCompliant' attribute with value 'true').
After update Unity to v5.0.0 (and resolve some braking changes), compiler reports warning 'CS3001'.

Doesn't Unity keep compliance to the CLS any longer?

**Comment by ENikS** [comment]
Latest MSBuild/Visual Studion 2017 project targets do not automatically mark code as CLS Compliant. 
Theoretically Net Standard should be CLS Compliant by default but apparently it is not.

If you find out how to fix it and submit a pull request I will be more than happy to include it in a patch.

**Comment by ENikS** [comment]
Deployed
