### ISSUE TITLE
FR: Container Registration Validation

### ISSUE THREAD

**Issue by furier** [unitycontainer/unity#126]
Feature Request: Container Registration Validation.

- Validate all registrations can be resolved.
- Validate that all `IHttpControllers` can be resolved.

**Comment by ENikS** [comment]
Really don't think this could be done or worth the effort.

**Comment by furier** [comment]
A lot of other IoC containers have the feature, and we have currently implemented our own unit tests that simply just tries to resolve all registrations and controllers inheriting from `IHttpController`. Just thought it would be great to have the feature included in the container with awesome error messages, but I guess not.

**Comment by ENikS** [comment]
The validation is only possible when entire dependency graph is created and available at the time of validation. Unity does not create nodes for the type until type is requested to be crated. So, to put it simply, it would be as if you enumerate registered types and create them all to verify.

You could do it already, it does not require any additional implementation.
