### ISSUE TITLE
Support for Microsoft.Extensions.DependencyInjection.2.0.0 

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/unity#128]

**Comment by axelgenus** [comment]
Just to keep track of this: [here](https://github.com/unitycontainer/microsoft-dependency-injection) in the repository for Microsoft Dependency Injection.

**Comment by JoelHT-Landmark** [comment]
Looking forward to this so I can retire my in-house compat library.

**Comment by ENikS** [comment]
[Done](https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection/)
