### ISSUE TITLE
RegistrationByConvention

### ISSUE THREAD

**Issue by gunnim** [unitycontainer/unity#129]
Hi, I took a look around the RegistrationByConvention project, built the source, packaged the proj. 
Everything seems fine, was there something specific that was missing before release?

This is a continuation of our discussion here:
https://github.com/unitycontainer/container/issues/27

**Comment by ENikS** [comment]
Need to fix one method under netcoreapp1.0. It is commented out...

**Comment by ENikS** [comment]
Duplicate of unitycontainer/registration-by-convention#2
