### ISSUE TITLE
Resolution of the dependency failed, type = 'System.Web.Mvc.IControllerFactory'

### ISSUE THREAD

**Issue by kopenk** [unitycontainer/unity#133]
i just update Unity and Unity.Mvc to latest version in my project
and then this error appear while trying to run the app

Exception thrown: 'System.InvalidOperationException' in Unity.Container.dll

`
Unity.Exceptions.ResolutionFailedException occurred
  HResult=-2146233088
  Message=Resolution of the dependency failed, type = 'System.Web.Mvc.IControllerFactory', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, System.Web.Mvc.IControllerFactory, is an interface and cannot be constructed. Are you missing a type mapping?
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving System.Web.Mvc.IControllerFactory,(none)

  Source=Unity.Container
  TypeRequested=IControllerFactory
  StackTrace:
       at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides)
  InnerException: 
       HResult=-2146233079
       Message=The current type, System.Web.Mvc.IControllerFactory, is an interface and cannot be constructed. Are you missing a type mapping?
       Source=Unity.Container
       StackTrace:
            at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.ThrowForAttemptingToConstructInterface(IBuilderContext context)
            at lambda_method(Closure , IBuilderContext )
            at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
            at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
            at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
            at Unity.Container.StrategyChain.ExecuteBuildUp(IBuilderContext builderContext)
            at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides)
       InnerException: 
`

app running fine if Unity.Exceptions.ResolutionFailedException is removed from exception break when thrown setting.
i am using MVC 5 

is this normal behavior?

**Comment by ENikS** [comment]
I am not sure. Could you provide Unit Test that demonstrates this behavior? I am not very experienced with MVC

**Comment by dushuaihua** [comment]
![image](https://user-images.githubusercontent.com/17045801/31889907-f9b1965c-b833-11e7-8fe6-645dada1815f.png)

`Resolution of the dependency failed, type = 'System.Web.Mvc.IControllerFactory', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, System.Web.Mvc.IControllerFactory, is an interface and cannot be constructed. Are you missing a type mapping?
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving System.Web.Mvc.IControllerFactory,(none)
`

![image](https://user-images.githubusercontent.com/17045801/31889984-31edfdf8-b834-11e7-891a-a07f50f7b609.png)

I get a same error when i update to the least version.

**Comment by ENikS** [comment]
Well, I believe you there is an error. I need a way of recreating it to fix it.

**Comment by axelgenus** [comment]
That error means that you did not specified a mapping for IControllerFactory. How did you managed to attach Unity to MVC? Did you use the default classes which came with Unity.Mvc? The new package (5.0) misses them: I am talking about UnityConfig.cs and UnityMvcActivator.cs which came with the old version of Unity.Mvc (4.0).

**Comment by ENikS** [comment]
@axelgenus You appear to know about this issue. Care to look deeper into it?
Why these are missing and should they be included? I copied v4 repo without giving it much thought but perhaps I used wrong copy or something.

**Comment by axelgenus** [comment]
I hated those classes when I was using Unity 4.0 becuase Resharper refused to work with them: it detected those classes being part of a NuGet package and code clean-up did not work. I can port them for Unity 5.0 (they should work out-of-box) and provide a pull request or I can write a wiki article about how to manually implement them according to developer's needs.

**Comment by ENikS** [comment]
Look at [these](https://github.com/unitycontainer/unity/tree/Unity.Mvc/source/Unity.Mvc), perhaps it is what you need?

**Comment by axelgenus** [comment]
I am talking about [these classes](https://github.com/unitycontainer/unity/tree/Unity4/source/Unity.Mvc/Src/NuGet).

**Comment by ENikS** [comment]
Never seen these before. I was not sure why it is there and did not include it in the package. I am not sure new project format  will even support these.

What are these?

**Comment by axelgenus** [comment]
They initialize the container before starting the application and attach the Unity DependencyResolver to MVC during the "start" event and dispose of in the "shutdown" event of ASP.NET MVC.

It's the basic wiring of Unity in ASP.NET MVC. Also in Unity.WebApi there were two similar classes.

**Comment by ENikS** [comment]
OK, you seem to know enough to fix it. I'll leave it in your capable hands :)

**Comment by eglauko** [comment]
AspNet MVC 5 get some services from they dependency resolver, if the service does not exists, it must return null.
For use other container in MVC 5 you need implements mvc dependency resolver, and this was implemented in UnityContainer.MVC version 4.0.1
For WebApi there are other implementations.

**Comment by kopenk** [comment]
just update to new version and the error is gone..
is this miracle? lol
thanks for the fast resolution..

**Comment by axelgenus** [comment]
You're welcome. ;)

**Comment by ENikS** [comment]
Thank you for your help Alessandro!
