### ISSUE TITLE
RegisterByConvention?

### ISSUE THREAD

**Issue by s-bauer** [unitycontainer/unity#135]
Hey, since the upgrade to verison 5.X.X I'm unable to access the RegisterByConvention classes like "WithMappings", "WithName", ...
I cannot find any nuget package that contains an assembly which contains these types. 
How am I supposed to use the registration-by-convention features with the 5.X release?
Thanks for your help!

**Comment by ENikS** [comment]
UWP has changed and old code does not work anymore. The issue is covered here unitycontainer/registration-by-convention#2

If you know how it could be fixed you could send a pull request and I'll deploy it to NuGet
