### ISSUE TITLE
The latest version of Unity.5.0.1NuGet, including other branches of DLL version, is not the latest

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/unity#138]
The latest version of Unity.5.0.1NuGet, including other branches of DLL version, is not the latest

Unity.AspNet.WebApi.5.0.2 ； Unity.Abstractions.2.0.2 Unity.ServiceLocation.2.0.1

**Comment by axelgenus** [comment]
What do you mean exactly? Each package has its own version now.

**Comment by ghd258** [comment]
But unity automatically contains other DLL

**Comment by ghd258** [comment]
Installing unity through NuGet automatically contains other DLL

**Comment by axelgenus** [comment]
The Unity package is a meta-package which pulls in all the libraries. If the meta-package is not changes it makes no sense to upgrade it since you can update the single libraries.

**Comment by ghd258** [comment]
The Unity package is a meta package that contains all the libraries. If the metadata package has been changed, it has been updated independently, but this time, if you install Unity once, it will be my latest coverage

**Comment by ghd258** [comment]
Cause no local version exists

**Comment by ghd258** [comment]
Cause different versions of the local existence

**Comment by axelgenus** [comment]
Uhm, maybe it is better to just refer to the other NuGet packages instead of embedding the libraries in a single package. @ENikS what do you think about this?

**Comment by delpher** [comment]
Think this is the same problem as described in #136

**Comment by ENikS** [comment]
I am still trying to come up with best format. I think including only core packages will solve this:
- CommonServiceLocator
- Unity.Abstractions
- Unity.Container
- Unity.ServiceLocation
- Unity.Configuration
- Unity.Interception
- Unity.Interception.Configuration

and leave these packages as add on individually distributed NuGet packages:
- Unity.Mvc
- Unity.AspNet.WebApi

**Comment by axelgenus** [comment]
I agree on ASP.NET packages but the main point is that the Unity package should really have those libraries as dependencies and not embed them.

**Comment by ENikS** [comment]
Well. you get these if you get individual packages. The idea is to get ALL at once and not to think about resolving dependencies.

**Comment by axelgenus** [comment]
What I meant was that with the Unity package you can pull in the project the single NuGet packages for the single libraries. It would be a meta-package which contains nothing but the base libraries' dependencies. This would also make it easier to upgrade to the single libraries later on.

**Comment by ENikS** [comment]
What benefits would it provide compared to packaging all these binaries into the package?

**Comment by axelgenus** [comment]
Having a monolithic package (like it is now) forces us to publish a new Unity package to NuGet every time a single library gets updated. Having a meta-package would require up to publish just the single updated libraries to NuGet even if we don't publish a new version of the meta-package.

Also, if a user wants to migrate to the single libraries later on, s/he would just have to remove the meta-package and the unneeded libraries since NuGet will not uninstall the dependent packages.

**Comment by ENikS** [comment]
I see your point. Lets hear more opinions before we reach the decision. I am pretty sure there will be plenty of these in coming weeks once people start upgrading...

Fixed, deployed v5.0.2
