### ISSUE TITLE
Unity 4 settings 100% icompatible with Unity 5 - setup documentation, please!

### ISSUE THREAD

**Issue by Eclipse-Computing** [unitycontainer/unity#140]
**_Not_** a super-advanced programmer with 10+ years of unity experience under the belt, still trying to figure out all this injection stuff. Have a project due, seconds counting down and the entire project is a sea of red because of Unity 5.

* DotNet 4.6.2
* MVC 5

I need information on how to set up Unity 5 under MVC 5. The files generated by Unity 4 do not work, and cannot work with Unity 5. As just one example, 

`UnityConfig.RegisterComponents();`

in `Global.asax.cs` no longer works because… *drum roll* …`RegisterComponents()` no longer exists in `UnityConfig.cs` with Unity 5

There are 100 other items I could bring up that suddenly went sideways, but I am not even sure if they are related to Unity 5, I am just trying to get one small cog to work right with zero information available. There isn’t even documentation under the wiki!

And attempting to revert back to Unity 4 just broke a dozen other things, causing things like System.Web.Mvc, System.Web.Helpers and other things to be dropped (and not findable/re-referenceable) from the entire system. My controllers can’t even extend `Controller` because System.Web.Mvc is no longer being referenced and v5 is no longer findable _to be_ referenced.

**Comment by ENikS** [comment]
If you have such a tight schedule, I would suggest to stick with v4.0.1 for now. It is tried and true and it works. 

If you insist on v5, I would create issue [here](https://github.com/unitycontainer/aspnet-mvc/issues) and Alessandro will help you.

**Comment by axelgenus** [comment]
The Unity MVC package does not require Global.asax.cs to call RegisterComponents because it is called automatically by WebActivatorEx before the web application is started. About the Microsoft.AspNet.Mvc dependencies I did not experience any kind of trouble upgrading the project I am working on from Unity 4.0.1 to 5.0 except namespaces being renamed.

I understand you are in trouble right now but please, do as Eugene said: open a new bug in the Unity.Mvc project and explain what is not working for you. Also, post the package.json file of your project so I can take a look at it.

**Comment by Eclipse-Computing** [comment]
Thank you all for the quick replies.

-  All I am looking for is documentation. I really don’t want to bug anyone if I can muscle through anything that’s comprehensive for Unity v5 under MVC 5. Even code examples would be real swell.
-  I have temporarily reverted back to 4.0.1 until this project is “done” and shipped to the client, I will be using it as a testbed for a v5 upgrade path on my own time.
-  Since I am using MVC 5, I do not have a package.json to provide. I am still gun-shy about Core v2, and am not willing to commit until I have done a lot more testing with non-critical stuff.

**Comment by axelgenus** [comment]
Unity documentation is very old and we are trying to do our best to update it ASAP. We are few and contributors are welcome.

MVC 5 integration should be really simple: if you create a new MVC project from within Visual Studio just use NuGet to pull in the project the Unity.Mvc package and it should take all the dependencies by itself. Also the Unity.Mvc package adds two files to your project (in App_Start directory): UnityMvcActivator.cs and UnityConfig.cs. The first one is the one which integrates Unity in MVC 5; it uses WebActivatorEx to attach Unity as a dependency resolver before your application is started and dispose of it when the webapp shuts down. The other file is the one you need editing: in the RegisterTypes function you should register extensions and types to resolve or you have to load from a configuration file. The two files have some comments. Just try on a brand new project to test it. I will provide better documentation soon enough.

package.json is the file which is created by NuGet to store your dependencies from NuGet packages. You MUST have it. Check on the project directory.
