### ISSUE TITLE
Where is the static class : `Microsoft.Practices.Unity.AllClasses`?

### ISSUE THREAD

**Issue by KnairWang** [unitycontainer/unity#141]
I am new to C#, and new to Prism/Unity. Thought prism is still using Unity 4.x. I see there is new Unity nuget package, but can not find this static class `AllClasses`. 
I am using this helper to collect all types in my assemblies, and want to know if this helper will be added into (or already existed). Thanks.

**Comment by ENikS** [comment]
Waiting to be fixed: unitycontainer/registration-by-convention#2

Closing as duplicate

**Comment by mehrbat** [comment]
I do not use .Net Core, still use 4.7.2. The referenced forum is for .net core, not sure it addresses my problem.
