### ISSUE TITLE
Compatibility after upgrade

### ISSUE THREAD

**Issue by Azzhag** [unitycontainer/unity#142]
How do I set this up after upgrade from 4.0.1 to 5.0.2 ?
Do i need to register each type separately ?

`            Container.RegisterTypes(
                AllClasses.FromLoadedAssemblies()
                    .Where(t => t.Namespace != null && (t.Namespace.StartsWith(projectNamespaceData) || t.Namespace.StartsWith(projectNamespaceServices)))
                    .Where(t => t.GetInterfaces()
                        .Any(i => i.Namespace != null && (i.Namespace.StartsWith(projectNamespaceData)) || i.Namespace.StartsWith(projectNamespaceServices))),
                WithMappings.FromMatchingInterface,
                WithName.Default,
                WithLifetime.ContainerControlled,
                t => ((typesWithoutCommonInjectionMembers.Contains(t.Name))
                    ? EmptyInjectionMember()
                    : CommnonInjectionMember()));`

**Comment by ENikS** [comment]
You need this package: https://www.nuget.org/packages/Unity.RegistrationByConvention/
