### ISSUE TITLE
NuGet 5.1.0 deletes key references

### ISSUE THREAD

**Issue by jmhongithub** [unitycontainer/unity#145]
When upgrading from 5.0.1 to 5.1.0 the following lines were removed from my web project file (csproj):

    <Reference Include="System.Web.Helpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.Http.WebHost.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.Mvc.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.Razor.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.WebPages.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Deployment, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.WebPages.Deployment.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Unity.5.0.1\lib\net45\System.Web.WebPages.Razor.dll</HintPath>
    </Reference>

I'm assume only the hints should have been removed or updated. The result is that it breaks the app because these references are all needed in an ASP.NET MVC project.

**Comment by ENikS** [comment]
Visual Studio is not under our control.

**Comment by smithkl42** [comment]
I don't understand. Why is it deleting references that are in there from *other packages*? Unless I'm missing something, this is a really horrible experience. I upgraded fro Unity 5.0 to Unity 5.1, and immediately had 407 build errors. That's not the way things should go.

**Comment by jmhongithub** [comment]
Agreed, its is painful. Unity.Abstractions and Unity.Configuration seem to work. I'm guessing there is a bug in the NuGet deployment that is uses a wildcard search but it casting a larger net deleting out the wrong references. I don't know who to report this bug to since NuGet point backs to this repo as the owner.

**Comment by ENikS** [comment]
You are welcome to contribute better experience. We welcome any help.

**Comment by jmhongithub** [comment]
Don't know enough of the NuGet packages to create, I can test if someone posts an update

**Comment by ENikS** [comment]
@jmhongithub  You could file an issue with Visual Studio. It ultimately controls all these nuances.
...and up until couple of weeks ego I knew nothing about NuGet. (Hence these issues)

**Comment by jmhongithub** [comment]
@ENikS are there any Microsoft staff still contributing to Unity or is it just you?

**Comment by ENikS** [comment]
No. No one contributed to this project since 2015. Microsoft stopped supporting it in 2013.

**Comment by jmhongithub** [comment]
Wow, I understand the issue now.

**Comment by ENikS** [comment]
Do you want to help? Plenty of opportunities...

**Comment by smithkl42** [comment]
(And definitely sorry for being grumpy - I had thought I was complaining to MS, which feels a lot different than complaining to a guy who's just doing his best.)

**Comment by ENikS** [comment]
No biggie

**Comment by jmhongithub** [comment]
It sounds like plenty opportunities. Right now I need to get this DI library running configured correctly for our team. I saw the author as "Microsoft.Practices.Unity" in NuGet so I had assumed Microsoft staff was still contributing. Sounds like that is not the case. Was version 3.5.1404 the last one they contributed?

**Comment by ENikS** [comment]
Yes. since than it is only community support.

**Comment by ENikS** [comment]
Anyway, it is stable enough and if you link to individual packages it should work.

**Comment by jmhongithub** [comment]
I would recommend pulling 5.1.0 from NuGet, others are going to receive the same error.

**Comment by ENikS** [comment]
I'll deploy 5.1.1 later. It only breaks in certain conditions.

**Comment by jmhongithub** [comment]
Unfortunately the issue goes back to 5.0.1. When I uninstalled 5.0.1 it deletes those other references as well.  I'm going to to need to manually edit the project files to fix.

**Comment by ENikS** [comment]
This is not the package, it is the new NuGet manager. Package lists these as dependencies and when you delete it manager thinks you no longer need these dependencies as well. 

I do not think it will do it again though. The MVC package had problem with signing certificate and had to be resigned with correct one. For the manager it is completely different package now, hence all the commotion with dependencies.

**Comment by ENikS** [comment]
Deployed 5.1.2
