### ISSUE TITLE
Dependency on Microsoft.Practices.Unity 4.0.0

### ISSUE THREAD

**Issue by kcabral817** [unitycontainer/unity#148]
After upgrading to 5.1.2 I get an error indicating the Microsoft.Practices.Unity library is missing for "Container":
 protected override DependencyObject CreateShell()
        {
            return Container.Resolve<MainWindowView>();
        }
I unable to resolve the Container keyword.  Is there an alternative or is there a dependency?

**Comment by ENikS** [comment]
The namespace Microsoft.Practices.Unity has been changed to Unity.
I would suggest using ReSharper to help you with migration. They offer 30 day free trial.

**Comment by kcabral817** [comment]
I found that PRISM still has the reference to Microsoft.Practices.Unity.  Sorry for the confusion.
