### ISSUE TITLE
Problem when updating from 4.0.1 to 5.2.1

### ISSUE THREAD

**Issue by digitalsigi** [unitycontainer/unity#149]
I am using Unity together with Prism for quite some time now and so far everyting was fine.
When updating the Solution from Unity 4.0.1 to 5.2.1 several things don#t work anymore.

- I have no glue how to initialise ServiceLocator
- TryResolve is missing
- AddExtension to UnityContainer does not work anymore -> compile error
I always get asked to add a reference to Microsoft.Practices.Unity and ServiceLocator.
Where can I find info how ti fix that.

**Comment by ENikS** [comment]
Are you using updated Prism library? You could ask about it in [this thread](https://github.com/PrismLibrary/Prism/issues/1175#issuecomment-342972456).

**Comment by digitalsigi** [comment]
Not sure, will Check tomorrow, I think i am Using 6.3.0

L.G.
Josef Bogad
Von meinem iPhone gesendet

Am 09.11.2017 um 18:03 schrieb Eugene Sadovoi <notifications@github.com<mailto:notifications@github.com>>:


Are you using updated Prism library? You could ask about it in this thread<https://github.com/PrismLibrary/Prism/issues/1175#issuecomment-342972456>.

**Comment by digitalsigi** [comment]
I am using following packages:
CommonServiceLocator {1.3}
Prism.Core {6.3.0}
Prism.Unity {6.3.0}
Prism.Wpf {6.3.0}
Unity  {4.0.1}
Unity.Interception {4.0.1} 
Problem comes up when updating to CommonServiceLocator to 2.0.1, Unity to 5.1.2 and Unity.Interception to 5.0.3. Uncertain whether the issue is related to Prism, as there I am using latest version.
However I observed that Container definition in IUnityContainer refers to Microsoft.Practises.Unity.

**Comment by ENikS** [comment]
Prism 6.3.0 still uses old Unity. You need the new version. Please follow [this thread](https://github.com/PrismLibrary/Prism/issues/1175) for information

**Comment by digitalsigi** [comment]
OK, Thanks for pointing me in this direction. Was not aware that 6.3.0 is using old Unity.
I'll close this issue, because the mentioned thread explaines it.
