### ISSUE TITLE
Issues with changed PublicKeyToken value in v4.x

### ISSUE THREAD

**Issue by Robot1que** [unitycontainer/unity#15]
Actually it has been already mentioned by guys here - #8. But I'm not sure that changing major version of an assembly is the best solution.

Here are steps to reproduce the problem: 

1 . Create "Windows -> Classic Desktop -> WPF Application" project in Visual Studio. 
2 . Add "Prism.Unity" v6.0.1 NuGet package. 
3 . In the "Package Manager Console" run `Update-Package` command. 
4 . Add new class:

```
public class Bootstrapper : Prism.Unity.UnityBootstrapper
{
    protected override DependencyObject CreateShell()
    {
        return new MainWindow();
    }
}
```

5 . In the `App.xaml` file remove the following attribute:

```
StartupUri="MainWindow.xaml"
```

6 . In the `App.xaml.cs` file add the following code:

```
protected override void OnStartup(StartupEventArgs e)
{
    base.OnStartup(e);

    var bootstrapper = new Bootstrapper();
    bootstrapper.Run();

    Application.Current.MainWindow.Show();
}
```

7 . Try to run a project. 

Application crashes with an exception:

```
Could not load file or assembly 'Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
```

I believe it's caused by the new assembly `PublicKeyToken` value. I've made a research and here are assembly full names for all versions of Unity:

```
Unity.4.0.1
Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f

Unity.4.0.0
Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f

Unity.3.5.1404.0
Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Unity.3.0.1304.1
Microsoft.Practices.Unity, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Unity.3.0.1304.0
Microsoft.Practices.Unity, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Unity.2.1.505.2
Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Unity.2.0
Microsoft.Practices.Unity, Version=2.0.414.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

As I can see starting from version 4.0.0 `PublicKeyToken` value has been changed. Now it causes some inconveniences that I have solving this problem. Is it a good practice to change `PublicKeyToken` value of an assembly? If you have to change it then maybe it's a good idea to create a separate NuGet package?

After I've read [this](https://github.com/Particular/NServiceBus.Unity/issues/22) explanation I guess that guys had the same problem with Prism. And they have created a new NuGet package marking old one as deprecated:
- [Old Prism](https://www.nuget.org/packages/Prism/)
- [New Prism](https://www.nuget.org/packages/Prism.Core/)

**Comment by tylerohlsen** [comment]
I would escalate this to more than just an *inconvenience*.  There is no longer a slow migration path to Unity 4.x.  It's an all or nothing migration.  In an enterprise system where we have a large quantity of assemblies that reference Unity, it will be difficult for us big bang migrate them all to 4.x.  

I agree this should probably be a different nuget package, but I would also advocate for a new assembly file name.  A new assembly file name will give us an easier way to deploy the old and new side-by-side and slowly migrate.

**Comment by Robot1que** [comment]
@tylerohlsen I agree. And again, if we take Prism as an example they've done exactly what you suggest -  they've renamed assembly and namespace from `Microsoft.Practices.Prism` to `Prism`.

**Comment by SeetharamShenoy** [comment]
I totally agree that both assembly and namespace should be renamed. This would ensure we don't have any conflicts with the 3.0 version.

**Comment by pcibraro** [comment]
I already asked Microsoft for the original signing key. If the can provide us with the key, our all problems should gone with that. I hope they can make it. Thanks

**Comment by tylerohlsen** [comment]
I'm a Microsoft employee and I have an interest in helping out where I can with Unity.  Please let me know if you want my help and I can try to keep the conversations moving internally.

**Comment by pcibraro** [comment]
I just received an official answer from the previous owner at Microsoft. It's not possible for him to provide the previous signing key. I think we will go the same way as Prism by renaming the assemblies and namespaces, and generating a new set of nuget packages. We will keep it on our roadmap.

**Comment by tylerohlsen** [comment]
So the plan is to rename assemblies, namespaces, and NuGet packages?

If so, then that will be a breaking change from the new 4.0 assemblies.  Which would technically be a break in semantic versioning - unless you plan to increment the major version again.  I would recommend hiding the 4.0 NuGet packages until this change is done.  Otherwise those that go through the headache of upgrading to 4.0 will have to do it again after this change.
