### ISSUE TITLE
Issue with CommonServiceLocator.pdb

### ISSUE THREAD

**Issue by 1dasdave7** [unitycontainer/unity#150]
When using the package and building with MSBuild via TFS we are getting an error. Indexed source information could not be retrieved from ...\CommonServiceLocator.pdb. Error: Symbol indexes could not be retrieved (I've obscured the full path). The file exists so I'm wondering if there is an issue with it.

**Comment by ENikS** [comment]
Are you using latest MSBuild? 

I see no issues during [CI buld](https://ci.appveyor.com/project/IoC-Unity/service-location) which depends on the package. 

Perhaps if you could provide more info...
