### ISSUE TITLE
Load config from specific XML file

### ISSUE THREAD

**Issue by MrSkiv** [unitycontainer/unity#152]
Would be nice if there would be possibility to load configuration from specific (multiple) config file. This would be useful for solutions, where exist multiple dll's from different projects (maybe third party). Combine all DI configuration in single file is uncomfortable. (Or config per dll?)

**Comment by ENikS** [comment]
You could load any number of config files from your local code. Why would you need any extra support from Unity?

**Comment by MrSkiv** [comment]
Can you provide short example? I have one project where dll's over com+ is loaded as plugins. Each dll's needs to have separate unity config. All dll's is loaded in same AppDomain. So loading config from code wasn't so trivial and easy. (I would say: It not worked at all)

**Comment by MrSkiv** [comment]
public static class Globals
    {


        public static IUnityContainer ObjectBuilder { get; set; }

        static Globals()
        {
            var myAssembly = Assembly.GetExecutingAssembly();
            var dllName = myAssembly.CodeBase;
            dllName = dllName.Remove(0, 8); //file://
            var unityConfigAssemblyPath = Path.GetDirectoryName(dllName) + "/" + "Microsoft.Practices.Unity.Configuration.dll";
            var configFilePath = dllName + ".config";

            var tmp = new BuildConfigHelper();
            var section = tmp.GetCustomConfig<UnityConfigurationSection>(unityConfigAssemblyPath, configFilePath, "unity");

            ObjectBuilder = new UnityContainer().LoadConfiguration(section);
        }
    }

internal class BuildConfigHelper
    {
        
        private Assembly _configurationDefiningAssembly;

        public TConfig GetCustomConfig<TConfig>(string configDefiningAssemblyPath,
            string configFilePath, string sectionName) where TConfig : ConfigurationSection
        {
            AppDomain.CurrentDomain.AssemblyResolve += ConfigResolveEventHandler;
            _configurationDefiningAssembly = Assembly.LoadFrom(configDefiningAssemblyPath);
            var exeFileMap = new ExeConfigurationFileMap {ExeConfigFilename = configFilePath};
            var customConfig = ConfigurationManager.OpenMappedExeConfiguration(exeFileMap, ConfigurationUserLevel.None);
            var returnConfig = customConfig.GetSection(sectionName) as TConfig;
            AppDomain.CurrentDomain.AssemblyResolve -= ConfigResolveEventHandler;
            return returnConfig;
        }

        protected Assembly ConfigResolveEventHandler(object sender, ResolveEventArgs args)
        {
            return _configurationDefiningAssembly;
        }
    }

**Comment by ENikS** [comment]
What is wrong with repeating this code for each xml file you wish to load?
How would Unity guess what to do?

**Comment by MrSkiv** [comment]
I don't know what happens internal in Microsoft.Practices.Unity.Configuration.dll, but loading configuration fails. Configuration from one file is applyed to other file. I guess, when loading occurs or System.Configuration, or Unity.Configuration uses static variable and as a result Config1 tries load dependencies from Dll2. One of dll's works ok, but second - no. Pretty interesting situation was, when these dll's uses different versions of Unity. Then configuration loading fails with message that: unable cast Microsoft.Practices.Unity.Configuration to Microsoft.Practices.Unity.Configuration. But these classes from different assembly's.

**Comment by ENikS** [comment]
If you know how this could be improved and fixed please send a pull request. 
Otherwise I really doubt I'll have time for this in near feature.

**Comment by axelgenus** [comment]
@MrSkiv did you tried instanciating multiple child containers, one for each DLL and load configuration separately for each of them?

**Comment by MrSkiv** [comment]
In my case, dll's is isolated from each other: they have own configuration and own container. These containers do not need to share anything. 
I ended up, to wire configuration from code (works ok, it's not what I wanted, but...).

**Comment by axelgenus** [comment]
Well, the basic principle of "container" is that it should be one and eventually have children. I do not know the specs of your project but it seems to me that you're streching the pattern too much. If you need to load assemblies at runtime what comes in my mind is that you could implement an abstraction library containing a plugin interface and call a registering method on each assembly passing a child container to each of them. In this way you would have a centralized control of the container from the main application and you could also resolve dependencies across assemblies.

**Comment by MrSkiv** [comment]
I have third party application (for example, ms office), which supports com+ plugins. So, each plugin/dll from my point of view is isolated application with own configuration, own dependencies and etc. Only one thing in common: context where they are executed. This context is out of my reach: why would I need create one more layer of abstraction and make plugin loading plugins??? Wouldn't it be much simpler: UnityContainer.LoadConfiguration("config1.xml")?

**Comment by wtujvk** [comment]
错误信息>[A]Microsoft.Practices.Unity.Configuration.UnityConfigurationSection 无法强制转换为 [B]Microsoft.Practices.Unity.Configuration.UnityConfigurationSection。类型 A 源自“Microsoft.Practices.Unity.Configuration, Version=4.0.0.0, Culture=neutral, 
I use unity5.3.2 throw error,but unity4.0.1 is ok.
Microsoft.Practices.Unity.Configuration.UnityConfigurationSection  Version is diffrent in 4.0.0.0 and 5.0.1。

**Comment by ENikS** [comment]
Could you post test case I could run to debug this condition?

**Comment by ENikS** [comment]
I've checked current implementation and I see no issues with loading multiple sections with configuration.
If two sections contain registration for the same type, latest registration wins. The old one will be overwritten. This could be prevented by using named registrations.

Am I missing anything?

**Comment by ENikS** [comment]
@wtujvk  Could you post test case I could run to debug this condition?

**Comment by ENikS** [comment]
I guess it is no longer relevant....
