### ISSUE TITLE
5.2.1: Child container creates new instances when resolving concrete class with hierarchical lifetime

### ISSUE THREAD

**Issue by MrGroovy** [unitycontainer/unity#153]
Behaviour of HierarchicalLifetimeManager changed from 5.2.0 to 5.2.1.
The test below passes with 5.2.0 but fails with 5.2.1.
A new instance of Something is created like if it is transient, this has been changed, before it was a single instance in the child container.

```
    interface ISomething
    {
    }

    class Something : ISomething
    {
    }

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            IUnityContainer rootContainer = new UnityContainer();
            rootContainer.RegisterType<ISomething, Something>(new HierarchicalLifetimeManager());

            using (IUnityContainer childContainer = rootContainer.CreateChildContainer())
            {
                Something a = childContainer.Resolve<Something>();
                ISomething b = childContainer.Resolve<ISomething>();

                Assert.AreSame(a, b);
            }
        }
    }
```

**Comment by ENikS** [comment]
This is due to [this bug fix](https://github.com/unitycontainer/container/issues/35). I've added explanation to the [Release](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311)

**Comment by MrGroovy** [comment]
The test indeed passes, but I still run into problems, so i think the behaviour is not exactly the same as before. I will see if i can come up with another test to show what i mean.

**Comment by ENikS** [comment]
I am looking into similar issue with ContainerControlledLifetimeManager. It could be that not all edge cases are handled. Will let you know...

**Comment by ENikS** [comment]
You might want to look at [this issue](https://github.com/unitycontainer/unity/issues/154). It might be what you are looking for.
