### ISSUE TITLE
One singleton with two interfaces

### ISSUE THREAD

**Issue by Haukinger** [unitycontainer/unity#154]
I used to write this

            container.RegisterType<RecordingState>( new ContainerControlledLifetimeManager() )
                     .RegisterType<IRecordingState, RecordingState>()
                     .RegisterType<IRecordingMonitor, RecordingState>();

to register a singleton instance of `RecordingState` to two interfaces (`IRecordingState` and `IRecordingMonitor`), and this used to work on unity 4. But in my current project (android/net standard 2/unity 5) it does not work anymore, that is, I get multiple instances of `RecordingState`. 

What's the recommended way of registering dual-interfaced singletons now?

**Comment by ENikS** [comment]
[This note](https://github.com/unitycontainer/container/releases/tag/5.2.1.235) should explain.

**Comment by Haukinger** [comment]
It _should_, but it _doesn't_ (as far as my breakpoints can see, I hit the constuctor multiple times)

**Comment by ENikS** [comment]
Yes, I see the issue but not quire sure how to fix it.

**Comment by Haukinger** [comment]
I can merge the two interfaces, but I'd prefer that to be a rather temporary measure, as they have totally different consumers and mixing them up is quite ugly design-wise.

**Comment by ENikS** [comment]
Give me few hours...

**Comment by Haukinger** [comment]
No worries, take your time. I'm curious whether we end up with `RegisterType` with two (optional) lifetime managers or `RegisterResolvedInstance` that defers the resolve step :-)

**Comment by ENikS** [comment]
Mapping checks for registered lifetime manager but if singleton was never instantiated before it returns null...

**Comment by ENikS** [comment]
If you do it like this it works:
```C#
IUnityContainer container = new UnityContainer();
container.RegisterType<OtherEmailService>(new ContainerControlledLifetimeManager());
container.RegisterType<IService, OtherEmailService>();
container.RegisterType<IOtherService, OtherEmailService>();

container.Resolve<OtherEmailService>();
Assert.AreSame(container.Resolve<IService>(), container.Resolve<IOtherService>());
```

**Comment by ENikS** [comment]
This seems to be more fundamental than I thought. It all comes down to what this registration means:
```
RegisterType<TFrom, TTo>(params InjectionMember[] injectionMembers) 
... and all other variants of it
```
The idea is to try to create ``TTo`` with all the overloads provided in ``injectionMembers`` **UNLESS** there is a instance of that class already registered with the container. In that case use the instance.
This is the design issue and I cant go around it in this implementation. Perhaps in v6...

So for you to keep using these just register the singleton.

**Comment by Haukinger** [comment]
> So for you to keep using these just register the singleton.

Should I read _resolve the singleton_? Register doesn't make sense to me

**Comment by ENikS** [comment]
``container.RegisterInstance(new RecordingState())`` much faster

**Comment by ENikS** [comment]
Turned out it could be done after all. Will post solution a bit later

**Comment by ENikS** [comment]
> I'm curious whether we end up with RegisterType with two (optional) lifetime managers or RegisterResolvedInstance that defers the resolve step :-)

I ended up doing just that

**Comment by ikriv** [comment]
I ran into the same problem. I did not want to force-resolve the singleton instance. I did this instead:

container.RegisterType<ConcreteType>(new ContainerControlledLifetimeManager())
.RegisterType<IFirstInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType>()))
.RegisterType<ISecondInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType>()));

This is *so much* uglier than the previous implementation though. Also, I am not clear on how to hunt all such cases in my code and fix them reliably.

**Comment by ZmorzynskiK** [comment]
I've also just run into a very similar problem and @ikriv comment helped resolve it for me.

This registrations:
```csharp
container.RegisterType<ConcreteType>(new ContainerControlledLifetimeManager())
.RegisterType<IFirstInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType>()))
.RegisterType<ISecondInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType>()));

container.RegisterType<ConcreteType2>(new ContainerControlledLifetimeManager())
.RegisterType<IFirstInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType2>()))
.RegisterType<ISecondInterface>(new InjectionFactory(c=>c.Resolve<ConcreteType2>()));
```
almost worked because later I'm doing:
```csharp
container.Resolve<IEnumerable<IFirstInterface>>();
```
and it resolved only the `ConcreteType2` while I expected to resolve also `ConcreteType`.

The solution is to add names to registrations:
```csharp
container.RegisterType<ConcreteType>(new ContainerControlledLifetimeManager())
.RegisterType<IFirstInterface>("1", new InjectionFactory(c=>c.Resolve<ConcreteType>()))
.RegisterType<ISecondInterface>("1", new InjectionFactory(c=>c.Resolve<ConcreteType>()));

container.RegisterType<ConcreteType2>(new ContainerControlledLifetimeManager())
.RegisterType<IFirstInterface>("2", new InjectionFactory(c=>c.Resolve<ConcreteType2>()))
.RegisterType<ISecondInterface>("2", new InjectionFactory(c=>c.Resolve<ConcreteType2>()));
```
Which worked as expected.

As a side note, none of the other above solutions work to resolve `IEnumerable<IFirstInterface>`.
@ikriv solution was the closest 👏
