### ISSUE TITLE
ASP.NET WEB API Stop resolving Controllers after Unity upgrade to 5.2

### ISSUE THREAD

**Issue by rjardines** [unitycontainer/unity#155]
I had a working project ASP.NET WEB API 2 with Unity 4.x. I upgrade to unity 5.x the change was smooth only a few namespaces changed, but my system stop working because unity can't resolve my controllers. (My controllers were not registered on unity container, was not necessary before).I was playing around a lot and I discover when the dependency resolver asks unity to resolve my controller, no exception was thrown (the default behavior when something it's not registered, the resolve was inside a try catch) but no response neither the execution just loose, not stackoverflow or any other exception.After register explicitly my controllers all came back to normal.I have not clue what is happening here, any help would be thankful?

**Comment by rjardines** [comment]
I still with many troubles rollback to version 4.01 resolve all my problems

**Comment by QuentinSuckling** [comment]
I had exactly the same problem when I updated from 5.2.0 to 5.2.1.
Rolled back to 5.2.0 and they're working again.

When I get time I'll update again and do some more testing.

**Comment by axelgenus** [comment]
You should not register the containers manually. Did you added a dependency to https://github.com/unitycontainer/aspnet-webapi?

**Comment by QuentinSuckling** [comment]
Hi Axel,

No, didn't know it existed.

Is there any documentation on how to set it up?
It wasn't mentioned in the MS guide (https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/dependency-injection) which I think most people would use when starting out.

I'll try it out.
Thanks

**Comment by rjardines** [comment]
Hi @axelgenus a piece of my code

using Unity.WebApi;
....

//ObjectDependency.Container is my container already configured
config.DependencyResolver = new UnityDependencyResolver(ObjectDependency.Container);

**Comment by QuentinSuckling** [comment]
Ok, so I added a reference to Unity WebApi and moved all my registrations out of WebApiConfig to the UnityConfig.
Most of my registrations use HierarchicalLifetimeManager so changed UnityWebApiActivator to use this line  -
            var resolver = new UnityHierarchicalDependencyResolver(UnityConfig.Container);


Tried my web services and nothing was resolving.

Reverted back to 5.2.0 and moved my registrations back to WebApiConfig (using my own resolver that creates a child container) and everything is working again.

I'm not getting any exceptions so I can't send you anything. Calls are just timing out.

Something definitely broken with WebApi HierarchicalLifetimeManager in 5.2.1.

**Comment by axelgenus** [comment]
I know @ENikS was working on that piece of code. Maybe he know better how to fix this problem.

**Comment by ENikS** [comment]
I will deploy v5.2.2 shortly

**Comment by ENikS** [comment]
Try with the latest. Just deployed numerous fixes...

**Comment by QuentinSuckling** [comment]
Just tried it with 5.3.0 and everything seems to be working fine again now.

Thanks for your help!

**Comment by ENikS** [comment]
Thank you for your feedback

**Comment by QuentinSuckling** [comment]
No probs.

Better wait till the other guy that opened the issue reports back before you close it though ;)

**Comment by ENikS** [comment]
I guess it is safe to close it, been a while...
