### ISSUE TITLE
Resolve order should not be important

### ISSUE THREAD

**Issue by rokleM** [unitycontainer/unity#156]
Hello, after I upgraded to version 5.2.1 I had some failures on previously working code. I debugged it and learned that the problem can be reproduced with the following test (which passes on 5.1.1):

	interface ITestData
	{
	}

	class TestData : ITestData
	{
	}

	[Test]
	public void
	ResolveOrderDoesntMatter()
	{
		using(var container = new UnityContainer()) {
			var td = new TestData();

			container.RegisterType<TestData>(new ContainerControlledLifetimeManager(), new InjectionFactory(_ => td));
			container.RegisterType<ITestData, TestData>();

			Assert.AreSame(td, container.Resolve<ITestData>());
			Assert.AreSame(td, container.Resolve<TestData>());
		}
		using(var container = new UnityContainer()) {
			var td = new TestData();

			container.RegisterType<TestData>(new ContainerControlledLifetimeManager(), new InjectionFactory(_ => td));
			container.RegisterType<ITestData, TestData>();

			Assert.AreSame(td, container.Resolve<TestData>());
			Assert.AreSame(td, container.Resolve<ITestData>());
		}
	}

**Comment by ENikS** [comment]
Thank you for reporting this. The issue has been fixed [(See this thread)](https://github.com/unitycontainer/unity/issues/154). 
I will deploy new version this weekend.

**Comment by rokleM** [comment]
Great! I'm not familiar with the code, but should I be worried that the issue didn't appear in 5.1.1? Your fix doesn't seem to be a reversal to old ways, but a new feature...

**Comment by ENikS** [comment]
It all relates to [this but fix](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311)
