### ISSUE TITLE
Support for Dependency Injected Collections

### ISSUE THREAD

**Issue by stesieber** [unitycontainer/unity#16]
_issue was migrated from the codeplex site_

There should be support for injecting collections into constructors through Unity.

Still forcing the clients to design their classes with arrays instead of more decent collections is an invitation for bugs.
We're usually never using arrays without a good reason, thus it requires a comment in the constructor that it's there for unity. Otherwise the next developer will get rid of it.

Is there maybe a way to change the behavior of unity in our solutions to support more than just arrays there?

**Comment by JohnTasler** [comment]
I thought it supports IEnumerable<>.

**Comment by bezysoftware** [comment]
Using following 
container.RegisterType&lt;IEnumerable&lt;T>, T[]>()
Your classes can have IEnumerable as constructor dependency

**Comment by stesieber** [comment]
Sorry for not being enough specific. The problem is when registering multiple types for the same interface:

    container.RegisterType<IMyInterface, Implementation1>("first registration");
    container.RegisterType<IMyInterface, Implementation2>("second registration");

I cannot resolve a class with the following constructor out of the box:

    MyClient(IEnumerable<IMyInterface> implementations){...}

whereas this is possible:

    MyClient(IMyInterface[] implementations){...}

**Comment by bezysoftware** [comment]
I think that behavior is correct - the framework cannot know how to resolve IEnumerable interface unless you tell it explicitely to use for example array:

container.RegisterType<IEnumerable<T>, T[]>();

**Comment by stesieber** [comment]
Well, I guess for the array version to work, it also does some magic behind the scenes - remember I just registered the same type multiple times and it is able to automatically resolve the array.

I just think it should support IEnumerable<T> out of the box for these multiple registrations as well.

**Comment by ENikS** [comment]
This actually became a requirement to implement Microsoft.Extensions.DependencyInjection.

**Comment by ENikS** [comment]
Done in bea67abc6007c2bec586fae88590921216c19d87
