### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' or one of its dependencies. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by spandthat** [unitycontainer/unity#160]
I'm getting:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' or one of its dependencies. The system cannot find the file specified.'

at Bootstraper.Run()

**Comment by ENikS** [comment]
Judging by Bootstrapper.Run() you probably wanted to file this with [Prism project](https://github.com/PrismLibrary/Prism)?

**Comment by spandthat** [comment]
Yeah you are right, sorry
