### ISSUE TITLE
RegisterInstance isn't thread-safe and sometimes attempts to create a new instance instead of returning the one we registered

### ISSUE THREAD

**Issue by yitzhaks** [unitycontainer/unity#161]
We found a race condition in RegisterInstance where the container will try to create an instance of the type we registered an instance of instead of returning the registered instance.

Looking at the code, we suspect that the following lines are in the wrong order:
[UnityContainer.cs#L157](https://github.com/unitycontainer/container/blob/ad53a5136a57854b44100ac7cb58eee456a36c26/src/UnityContainer.cs#L146)
  `SetLifetimeManager(type, name, lifetime);`
  `lifetime.SetValue(instance);`

**Comment by yitzhaks** [comment]
We found the problem. We were using an ExternallyControlledLifetimeManager, which held a weak reference to our instance which was subsequently GC'd.

**Comment by yitzhaks** [comment]
Actually, the problem is both. once we switched to using a different lifetime manager, we still had the problem until we called SetValue on it before calling RegisterInstance.

**Comment by ENikS** [comment]
Thank you, Completely makes sense. I'll switch these lines.

**Comment by yitzhaks** [comment]
Thanks! Any chance to get the fix ported to v4 as well? We still haven’t upgraded, and I want to pick up the fix without all the work and validation required when upgrading a major version.

**Comment by ENikS** [comment]
Unfortunately V4 is off limits. The signing certificate is lost and no compatible assemblies could be generated. [This explains it.](https://github.com/unitycontainer/unity#roadmap)
