### ISSUE TITLE
Overwriting Registration

### ISSUE THREAD

**Issue by dcomartin** [unitycontainer/unity#164]
Fairly certain this is changed behavior from v3. Not sure if this is intended or not.

Here's a gist of the issue. The last two tests fail.

https://gist.github.com/dcomartin/6cc581c36cee7ac0cdd79af6d3d42257

It appears that if you specify T2 in RegisterType, an injection factory isn't used.
If you then try and overwrite that registration, it won't.

**Comment by dcomartin** [comment]
Is this related issue that was resolved in this release? https://github.com/unitycontainer/container/releases/tag/5.2.1.235

**Comment by ENikS** [comment]
Sometimes it pays to look at other issues for the answer :)
Duplicates: unitycontainer/container#35, unitycontainer/unity#159, unitycontainer/unity#163, unitycontainer/container#38

Yes, these related to the fix you mentioned. 

As explained [here](https://github.com/unitycontainer/container/issues/38) and [here](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311) registration ``container.RegisterType<IFoo, Foo>(new InjectionFactory(x => foo1));`` does not make sense from Unity standpoint.

I should probably add code to capture this condition and report error.

**Comment by dcomartin** [comment]
I did mention the resolved issue, and that does explain `container.RegisterType<IFoo, Foo>(new InjectionFactory(x => foo1));`.  

However my last tests I do not see a related issue nor does it explain to to me.  Maybe I'm not understanding correctly.

**Comment by ENikS** [comment]
Yes, there is an issue. The Mapping from first registration is not cleared properly. 
Will fix shortly.

**Comment by ENikS** [comment]
Fixed in v5.3.2

**Comment by ENikS** [comment]
Added exception for registering container.RegisterType<IFoo, Foo>(new InjectionFactory(x => foo1));
