### ISSUE TITLE
In 5.3.2 I cannot define InjectionFactory with HierarchicalLifeTimeManager. It works in 5.3.1

### ISSUE THREAD

**Issue by TRSynthro** [unitycontainer/unity#165]
The following code causes an excetion in 5.3.2. In 5.3.1 it is still working:
            container.RegisterType<IServiceLocator>(
            new HierarchicalLifetimeManager(),
            new InjectionFactory(
                c =>
                {
                    logger.Info("InjectionFactory of IServiceLocator invoked with container: " + c.GetHashCode());
                    var locator = new UnityServiceLocator(c);
                    c.RegisterInstance<IServiceLocator>(locator, new HierarchicalLifetimeManager());
                    return locator;
                }));

![unity_error](https://user-images.githubusercontent.com/28567890/33554258-4858238c-d8fc-11e7-9d12-61363a68bf95.png)

**Comment by ENikS** [comment]
I am running this test and it passes:
```C#
[TestMethod]
public void unitycontainer_unity_165()
{
    var container = new UnityContainer();
    container.RegisterType<ILogger>( new HierarchicalLifetimeManager(),
                                     new InjectionFactory( c => new MockLogger()));

    Assert.AreSame(container.Resolve<ILogger>(), container.Resolve<ILogger>());
    Assert.AreNotSame(container.Resolve<ILogger>(), container.CreateChildContainer().Resolve<ILogger>());
}
```
Am I missing something?

**Comment by ENikS** [comment]
Looking more into it I see you are overriding registration of ``IServiceLocator`` with the instance. 
So it will no longer be a Hierarchical, it will always be that instance.

Registering instance with HierarchicalLifetimeManager does not make sense. Unity does not know how to create a new instance.

**Comment by TRSynthro** [comment]
You are correct.
 I was trying to solve the following issue with this code: http://unity.codeplex.com/workitem/12727
But sometimes thinking before copying code would better.
Thank you.
