### ISSUE TITLE
How to use a factory method?

### ISSUE THREAD

**Issue by GibSral** [unitycontainer/unity#166]
I want to delegate the construction of a type to a factory method.
In another DI container (included in MvvmCross) i can do the following:

`container.LazyConstructAndRegisterSingleton<IDummyObject>(() => new DummyObject());`

We are hiding the container behind our own interface and i want to implement an adapter for unity.
Is this possible?
I tried this:
```C#
public void LazyConstructAndRegisterSingleton<TInterface>(Func<TInterface> factory) where TInterface : class
{
    _container.RegisterType<TInterface>(new ContainerControlledLifetimeManager(), new InjectionFactory(container => factory()));
}
```
But this results in a stackoverflow.

Thx in advance

Lars

**Comment by ENikS** [comment]
I see nothing wrong with this. Perhaps your factory() has _container.Resolve(typeof(TInterface) ...) or something has dependency of type  ``TInterface``

**Comment by GibSral** [comment]
Thanks for the answer!
To clarify: 
these are the methods in my adapter:
```C#
public void LazyConstructAndRegisterSingleton<TInterface, TImpl>() where TInterface : class where TImpl : TInterface
{
    LazyConstructAndRegisterSingleton<TInterface>(() => IocConstruct<TImpl>());
}

public void LazyConstructAndRegisterSingleton<TInterface>(Func<TInterface> factory) where TInterface : class
{
    _container.RegisterType<TInterface>(new ContainerControlledLifetimeManager(), new InjectionFactory(container => factory()));
}

public T IocConstruct<T>()
{
    return (T)IocConstruct(typeof(T));
}

public object IocConstruct(Type typeToBeConstructed)
{
    return _container.Resolve(typeToBeConstructed);
}
```
And this is my test case which results in a stackoverflow during Resolve:
DummyObjectWithInjectedInterface needs IDummyObject via constructor injection

```C#
[Test]
public void LazyRegisterSingleton_WithObjectHasDependencies_ReturnsInstanceOnResolve()
{
     var systemUnderTest = new UnityDependencyInjectionContainer();
     systemUnderTest.LazyConstructAndRegisterSingleton<IDummyObject>(() => new DummyObject());
     systemUnderTest.LazyConstructAndRegisterSingleton<DummyObjectWithInjectedInterface, DummyObjectWithInjectedInterface>();

     var constructedObject = systemUnderTest.Resolve<DummyObjectWithInjectedInterface>();

     constructedObject.Should().BeOfType<DummyObjectWithInjectedInterface>();
}
```

**Comment by ENikS** [comment]
I see ``var systemUnderTest = new UnityDependencyInjectionContainer();`` is being tested but you are using _container in your methods to register types.  How are these connected and what exactly is ``UnityDependencyInjectionContainer``?

Can you give me a sample I can actually run? Perhaps add a test case to [this project](https://github.com/unitycontainer/container/tree/master/tests/Unity.Tests)? 

You don't need to  send a pull request, just use types and interfaces from the project so I can debug it.

**Comment by ENikS** [comment]
I guess it is not relevant anymore.

**Comment by GibSral** [comment]
Oh it is still relevant. I just was ill the last days and could not reply.
UnityDependencyInjectionContainer is our Adapter that hides the DependencyInjection container behind our own interface because we use different containers for different scenarios but still share code (UWP-App with MVVM-Cross using IoC-Container of MVVMCross / Server-Application with Unity as IoC).

I updated my post above with the complete code sample.

All we want to do is delegate the construction logic of certain objects to a factory method.
Maybe we have done it wrong but it would be very nice if someone could tell me how to achieve this :)

G

**Comment by ENikS** [comment]
Did you run your sample yourself? 
Here is your problem: 
- You register your singleton here:
```
public void LazyConstructAndRegisterSingleton<TInterface>(Func<TInterface> factory) where
TInterface : class
{
    _container.RegisterType<TInterface>(new ContainerControlledLifetimeManager(), 
                                        new InjectionFactory(container => factory()));
}
```
You start resolving like this: ``_container.Resolve(typeToBeConstructed)``

While resolving **<TInterface>** it executes ``factory()`` which internally calls  
LazyConstructAndRegisterSingleton<TInterface>(() => ``IocConstruct<TImpl>()``); which in turn calls 
return (T)``IocConstruct(typeof(T)``). 
You define ``IocConstruct(Type typeToBeConstructed)`` as:
```
public object IocConstruct(Type typeToBeConstructed)
{
    return _container.Resolve(typeToBeConstructed); <-- Go into infinite loop here
}
```
