### ISSUE TITLE
Error CS0012 The type 'IUnityContainer' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by kwcoffee1** [unitycontainer/unity#167]
[Screen-Shot Detail](https://stackoverflow.com/questions/47707336/error-cs0012-the-type-iunitycontainer-is-defined-in-an-assembly-that-is-not-re)

The IUnityContainer property "Container" exist in intellisense but the implementation reference is not found. The fix is pointing to an earlier version of Unity, (4.0.0.0). I'm using Unity version 5.3.2. Is there an additional reference I can Add to fix the error? See the link above for screen-shot details

**Comment by ENikS** [comment]
IUnityContainer is defined in Unity.Abstractions assembly. it is available either [here](https://www.nuget.org/packages/Unity.Abstractions/) or as part of composite package [here](https://www.nuget.org/packages/Unity/) 

I am assuming you are using other library that references Unity internally?
