### ISSUE TITLE
Updated windows, Unity says method not implimented

### ISSUE THREAD

**Issue by MikeFromBA** [unitycontainer/unity#169]
I updated my windows pro dev machine last night, and when I came in this morning and tried to debug a project visual studio spits out this error:

    Method 'GetVisitorDbProfile' in type 'MyDLL.Services.Location.ProfileService' from assembly 'MyDLL.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b9f7c69b7e2ca3xb' does not have an implementation.

This method does have an implementation, and has had one for years now.  The error seems to be coming when I register my services with Microsoft's Unity DI library.

the weird things:

1.  I put a breakpoint on the first line of the method it says is throwing the error (the method I use to register all my services in Unity), and it never gets hit.  Not even the constructor for the service gets called.

2.  I have had 2 customers with this same error when they installed our software.  Cust 1, fired up a new VM and error never appeared.  With Cust 2, our support guys uninstalled .NET 4.7, and all the related hotfixes and re-installed .NET 4.6.2 and this caused the error to go away.

3.  If I remove the line that registers the `ProfileService` in Unity from the method mentioned in 1 above, everything boots up fine and runs fine.

4.  The method it says is not implemented, isn't even called at startup.  So why would registration of the service care?

I am using Unity v5.3.2.

**Comment by ENikS** [comment]
There are no method called ``GetVisitorDbProfile`` in Unity library.

**Comment by MikeFromBA** [comment]
Correct.  Thats a method in my service.  The stacktrace indicates the error is happening when I try to register my Profile service (the RegisterServices method of my program).  If put a breakpoint on the line that calls 'RegisterServices', it is hit, but if i put a break point inside of 'RegisterServices' method on line 1, it never gets hit.

**Comment by ENikS** [comment]
Post registration code, stack trace, etc.

**Comment by MikeFromBA** [comment]
this is the method i use for registration:

`public void RegisterServices(IUnityContainer container, string sqlConnection, int sqlCommandTimeOut, bool enableLogging){
            try {
                _unityContainer = container;
                _unityContainer.RegisterInstance<IChatBeaconResolver>(this);

                _unityContainer.RegisterType<ILogService, LoggingService>(new ContainerControlledLifetimeManager(), new InjectionConstructor(enableLogging));



                _unityContainer.RegisterType<IProfileService, ProfileService>(new PerResolveLifetimeManager());
            }
            catch(Exception ex) {
                throw;
            }          

        }`

stacktrace:

`   at ChatBeacon.Core.Utility.ChatBeaconResolver.RegisterServices(IUnityContainer container, String sqlConnection, Int32 sqlCommandTimeOut, Boolean enableLogging)
   at ChatBeacon.Core.Initialization.Initialize.RegisterTypes() in C:\Users\mgorney\Source\Workspaces\ChatBeacon\ECS\Trunk\sightmax\SmartMax.SightMax.Core.Service\Initialization\Initialization.cs:line 260`

this is the constructor to my profile service:

`public ProfileService(ILogService logger, IChatBeaconResolver resolver) {
_logger = logger;
_resolver = resolver;
}`

**Comment by ENikS** [comment]
Why are you using PerResolveLifetimeManager()?

I need full stack trace. This one does not show the actual error. What is ``C:\Users\mgorney\Source\Workspaces\ChatBeacon\ECS\Trunk\sightmax\SmartMax.SightMax.Core.Service\Initialization\Initialization.cs:line 260``?

Do you have a repo I can look at?

**Comment by MikeFromBA** [comment]
the actual error is in the very first post.  No I do not have a repo to look at.  I use PerResolve because I dedicate the service on a customer account level.

**Comment by ENikS** [comment]
With info you give me I have no idea how to help you. Nothing you describe looks like Unity error. Either provide more info so I could guess better what is going on or you are on your own.
