### ISSUE TITLE
Resolve fails for singleton with Interface interception

### ISSUE THREAD

**Issue by tdworshak** [unitycontainer/unity#170]
Hi,

We are trying to upgrade our application from an older version of Unity to the current version.  Our application works fine with Unity 3.5, but we have run into a problem with Unity 5.3.2.  We would greatly appreciate any help or insight that you folks can provide.  Details of our problem are below:

When we try to resolve a type (in this case a singleton with interface interception), we get the following error/exception:

    Exception occurred while: while resolving.
    Exception is: ArgumentException - The type MessageRouter is not interceptable. Parameter name: interceptedType
    -----------------------------------------------
    At the time of the exception, the container was: 
      Resolving IMessageRouterInitializer,MessageRouter
        Resolving MessageRouter,MessageRouter

      ----> System.ArgumentException : The type MessageRouter is not interceptable.
    Parameter name: interceptedType

The exception is thrown by this method in InterfaceInterceptor:

    public bool CanIntercept(Type t)
    {
        Guard.ArgumentNotNull(t, "t");
        return t.IsInterface;
    }

Here is our code that makes the failing call to IUnityContainer.Resolve():

    IUnityContainer container;
    ...

    // Create a component which aggregates all of the interfaces which compose the message router
    return new MessageRouterComponent(
        container.Resolve<IComponent>("MessageRouter"),
        container.Resolve<IMessageRouterInitializer>("MessageRouter"),
        container.Resolve<IMessageRoutingService>("MessageRouter"));

Here is our configuration for "MessageRouter":

  
  <container name="MessageRouter">
    <extension type="Interception" />

    <RegisterSingleton Type="MessageRouter">
      <RegistrationNames>
        <Add Name="MessageRouter" />
      </RegistrationNames>
      <RegisterAs>
        <Add Type="IComponent"/>
        <Add Type="IMessageRoutingService" />
        <Add Type="IMessageRouterInitializer" />
      </RegisterAs>
      <constructor>
        <param name="logger" dependencyType="ILogger" />
        <param name="logAndRethrowHandler" dependencyName="LogAndRethrowHandler" />
      </constructor>

      <interceptor type="InterfaceInterceptor" />
      <interceptionBehavior type="ComponentStateInterceptor" />
      <interceptionBehavior type="ComponentLoggingInterceptor" />
    </RegisterSingleton>
  </container>

This configuration results in our code making the following registration calls:

    IUnityContainer.RegisterType([type for IComponent], [type for MessageRouter], "MessageRouter", [Unity.Lifetime.TransientLifetimeManager], [injectionMembers]);
    IUnityContainer.RegisterType([type for IMessageRoutingService], [type for MessageRouter], "MessageRouter", [Unity.Lifetime.TransientLifetimeManager]);
    IUnityContainer.RegisterType([type for IMessageRouterInitializer], [type for MessageRouter], "MessageRouter", [Unity.Lifetime.TransientLifetimeManager]);

Resolution works correctly if we remove the interceptors.  The problem appears to result from trying to resolve a singleton *with* interface interception.  As a test we replaced InterfaceInterceptor with VirtualMethodInterceptor, and resolution works.  Unfortunately, VirtualMethodInterceptor causes some behavior problems for us that make it unsuitable for our use case.

It seems like InterfaceInterceptor doesn't work correctly when trying to resolve a singleton, at least the way we are trying to use it.

Any suggestions?

Thanks

**Comment by ENikS** [comment]
Could you create a test case I can run to debug the issue?

**Comment by tdworshak** [comment]
Will do...

**Comment by tdworshak** [comment]
[Unity5Problem.zip](https://github.com/unitycontainer/unity/files/1568949/Unity5Problem.zip)

Here is a simple example that demonstrates the problem.  Let me know if you have any trouble with it.  This code works with Unity 3.5, but fails with 5.3.2.  Thanks!

**Comment by ENikS** [comment]
Your problem is in these two lines:
```C#
container.RegisterType(typeof(IInterface1), typeof(MyClass), "MyClass", new ContainerControlledLifetimeManager(), new InjectionMember[]{ interceptor, interceptionBehavior });
container.RegisterType(typeof(IInterface2), typeof(MyClass), "MyClass", new ContainerControlledLifetimeManager(), null);
```
Your second line overrides registration with your interceptors with plain type mapping. See [this issue](https://github.com/unitycontainer/container/issues/35).
For this to work try changing your registration like this:
```C#
container.RegisterType(typeof(IInterface1), typeof(MyClass), "MyClass", new ContainerControlledLifetimeManager(), new InjectionMember[]{ interceptor, interceptionBehavior });
container.RegisterType(null, typeof(MyClass), "MyClass", new ContainerControlledLifetimeManager(), null);
```

**Comment by tdworshak** [comment]
Hi, thanks for the feedback.  I tried your suggestion, but the first call to Resolve() throws an exception:

```
Unity.Exceptions.ResolutionFailedException
  HResult=0x80131500
  Message=Resolution of the dependency failed, type = 'Unity5Problem.IInterface1', name = 'MyClass'.
Exception occurred while: while resolving.
Exception is: ArgumentException - The type Unity5Problem.MyClass is not interceptable.
Parameter name: interceptedType
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving Unity5Problem.IInterface1,MyClass
    Resolving Unity5Problem.MyClass,MyClass

  Source=Unity.Container
  StackTrace:
   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides) in C:\projects\unity\Container\src\UnityContainer.cs:line 228
   at Unity.UnityContainer.Resolve(Type type, String name, ResolverOverride[] resolverOverrides) in C:\projects\unity\Container\src\UnityContainer.cs:line 176
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, String name, ResolverOverride[] overrides) in C:\projects\unity\Abstractions\src\Utility\UnityContainerExtensions.cs:line 615
   at Unity5Problem.Program.Main(String[] args) in C:\temp\Unity5Problem\Unity5Problem\Unity5Problem\Program.cs:line 73
```

Here is the modified code:

        static void Main(string[] args)
        {
            var container = new UnityContainer();
            container.AddNewExtension<Interception>();
            
            var interceptor = new Interceptor<InterfaceInterceptor>();
            var interceptionBehavior = new InterceptionBehavior<ComponentInterceptor>();

            container.RegisterType(null, typeof(MyClass), "MyClass", new ContainerControlledLifetimeManager(), new InjectionMember[] { interceptor, interceptionBehavior });
            container.RegisterType(typeof(IInterface1), typeof(MyClass), "MyClass");
            container.RegisterType(typeof(IInterface2), typeof(MyClass), "MyClass");

            var myclass1 = container.Resolve<IInterface1>("MyClass"); // <- Exception thrown here
            var myclass2 = container.Resolve<IInterface2>("MyClass");
            myclass1.MyMethod1();
            myclass2.MyMethod2();
        }

Thoughts?

**Comment by ENikS** [comment]
This is how Unity interprets your registration :
```C#
var container = new UnityContainer();
container.AddNewExtension<Interception>();
            
var interceptor = new Interceptor<InterfaceInterceptor>();
var interceptionBehavior = new InterceptionBehavior<ComponentInterceptor>();

// Register a singleton of type MyClass
container.RegisterType<MyClass>(new ContainerControlledLifetimeManager());

// Register mapping between IInterface1 and MyClass. 
// Once resolved this interface is stored as singleton 
// and all subsequent resolutions will resolve same instance.
// While resolving intercept interface and add behavior.
container.RegisterType<IInterface1, MyClass>(new ContainerControlledLifetimeManager(), 
                                             new InjectionMember[]{ interceptor, interceptionBehavior });

// Register mapping between IInterface2 and MyClass. 
// Once resolved this interface is stored as singleton 
// and all subsequent resolutions will resolve same instance.
container.RegisterType<IInterface2, MyClass>(new ContainerControlledLifetimeManager());

// Validating container.RegisterType<MyClass>(new ContainerControlledLifetimeManager(), null);
var sameMyClass = ReferenceEquals(container.Resolve<MyClass>(),     
                                  container.Resolve<MyClass>());

var sameMyClass1 = ReferenceEquals(container.Resolve<IInterface1>(),
                                   container.Resolve<IInterface1>());

var sameMyClass2 = ReferenceEquals(container.Resolve<IInterface2>(),
                                   container.Resolve<IInterface2>());

// IInterface2 is not wraped into proxy and should resolve to MyClass
var same = ReferenceEquals(container.Resolve<MyClass>(),
                           container.Resolve<IInterface2>());


var myclass1 = container.Resolve<IInterface1>();
var myclass2 = container.Resolve<IInterface2>();
myclass1.MyMethod1();   // Is intercepted
myclass2.MyMethod2();   // Is NOT intercepted
```
