### ISSUE TITLE
Unity 5.4.0 introduces breaking change

### ISSUE THREAD

**Issue by ramonsmits** [unitycontainer/unity#171]
Unity 5.4.0 introduces breaking change from 5.3.2

```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.String Unity.Registration.IContainerRegistration.get_Name()'.
``` 

Is Unity not following SemVer?

**Comment by ENikS** [comment]
It is not intentional. I'll release fix shortly.

**Comment by flafonta** [comment]
Another breaking change: System.InvalidOperationException: Injection factory can not be used in combination with type mapping (RegisterType<To, From>() or RegisterType<To>(new [Delegate]InjectionFactory()) ). Downgraded to 5.3.2 and it worked as expected.

**Comment by ENikS** [comment]
That one is legitimate, see [this release note](https://github.com/unitycontainer/container/releases/tag/5.2.1.235)

**Comment by ENikS** [comment]
Released Unity.5.5.0 and Abstractions.3.0.0

**Comment by quarion** [comment]
I have migrated to 5.5.6 version from 4.0.1, and I am also getting "Injection factory can not be used in combination with type mapping" exception. This is a breaking change for us, potentially without any workaround.
In our low-level library we rely on a behavior, that a registration can replace a previous registration. But to do this, they both need to be registered with the same signature (providing both "from" and "to" types).

This used to work, but will now throw exception:
```
 _container.RegisterType(@interface, type, lifetimeManager);

 _container.RegisterType(
                @interface,
                type,
                lifetimeManager,
                new InjectionFactory(container => factoryMethod.Invoke())
                );
```

If I replace it with this, it wont throw, but the replacement of registration wont work:
```
 _container.RegisterType(@interface, type, lifetimeManager);

 _container.RegisterType(
                @interface,
                lifetimeManager,
                new InjectionFactory(container => factoryMethod.Invoke())
                );
```

**Comment by ENikS** [comment]
The solution is described [here](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311)
I would recommend reading all of these [notes](https://github.com/unitycontainer/unity/releases)

**Comment by quarion** [comment]
I am not sure if I understand. If you are referring to "More strict use of InjectionFactory" paragraph, it is not a solution for this use case, as using the "new" syntax to register a factory wont allow to override previous registrations.

**Comment by ENikS** [comment]
There is nothing new about the syntax.  Did you see [this](https://github.com/unitycontainer/unity/issues/164)?

**Comment by quarion** [comment]
Sorry, I cannot see how it would allow to override type registration with a factory.
Here is a reproduction with an unit test.
```
[Test]
            public void Container_GivenTypeWasAlreadyRegistered_ShouldOverrideItWithANewRegistration()
            {
                _container.RegisterType(typeof(IEchoInterface), typeof(NormalEcho));

                var echoInstance = new LoudEcho();
                _container.RegisterType(typeof(IEchoInterface), new InjectionFactory(container => echoInstance));


                var resolvedClass = _container.Resolve<IEchoInterface>();


                resolvedClass.Should().Be(echoInstance);
            }
```

It fails on 5.5.6 with
```
Expected object to be 
LoudEcho
, but found 
NormalEcho
```

**Comment by ENikS** [comment]
I am running this code:
```C#
[Fact]
public void Container_GivenTypeWasAlreadyRegistered_ShouldOverrideItWithANewRegistration()
{
    var _container = new UnityContainer();
    _container.RegisterType(typeof(IEchoInterface), typeof(NormalEcho));

    var echoInstance = new LoudEcho();
    _container.RegisterType(typeof(IEchoInterface), new InjectionFactory(container => echoInstance));

    var resolvedClass = _container.Resolve<IEchoInterface>();
            
    Assert.Same(echoInstance, resolvedClass);
}

public interface IEchoInterface
{ }

public class NormalEcho : IEchoInterface
{ }

public class LoudEcho : IEchoInterface
{ }

```
and it passes

**Comment by quarion** [comment]
Oh, sorry, you are right. It was not fully isolated in my test. We have a custom `UnityContainerExtension` for the container, that allows to create decorators, that seems to work incorrectly with this approach. 

One strange thing I notice - after calling `_container.RegisterType(typeof(IEchoInterface), new InjectionFactory(container => echoInstance));` then `IEchoInterface` is passed as `typeFrom` argument to the extension, instead of `typeTo`. Is it a correct behavior?

The extension is quite complex, so getting to the bottom of this would be quite difficult...

**Comment by ENikS** [comment]
Yes, this is correct behavior. Registration is always associated with TypeFrom

**Comment by quarion** [comment]
I am sorry, I have miss-typed my comment. It is edited now.

Really, the situation is that when you register a type, then you get argument `typeFrom=IFoo, typeTo=Foo`. While you register a factory with the new interface, you get `typeFrom=null, typeTo=IFoo` in `UnityContainerExtension.AddRegistration` method.

**Comment by ENikS** [comment]
Thinking about it, you are right. Unfortunately this is the legacy we have to live with. 
If you know better way of doing it open the issue and submit your proposal.

**Comment by ENikS** [comment]
Created this [issue](https://github.com/unitycontainer/unity/issues/191)
