### ISSUE TITLE
System.Configuration.ConfigurationErrorsException：There was an error when creating the configuration section processing program of unity: failed to load the file or assembly "Microsoft.Practices.Unity.Configuration" or one of its dependencies. The system can not find the specified file

### ISSUE THREAD

**Issue by v-wiil** [unitycontainer/unity#176]
<section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection,Microsoft.Practices.Unity.Configuration" />

The version of Unity is 5.0.0. If i Downgrade to 4.0.0.1. It's will OK.  If i want to the latest stable version，how to modify the type.

**Comment by v-wiil** [comment]
section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection,Microsoft.Practices.Unity.Configuration"

**Comment by ENikS** [comment]
Change it to: ``section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Unity.Configuration"``

**Comment by v-wiil** [comment]
OK,thanks.
