### ISSUE TITLE
Multiple instances of singleton type created

### ISSUE THREAD

**Issue by dos36** [unitycontainer/unity#177]
Hi,

Please take a look into this:
If we have multiple interfaces registered for one singleton type, and this type has configured InjectionConstructor, than new object will be created for each interface we resolve.

This behavior can also be reproduced with other InjectionMember such as InterceptionBehavior.
If no InjectionMember configured, Unity works as expected. And only one singleton object can be created.

This issue is blocking us from migrating to latest Unity version.
We would really appreciate your help.

See attached solution for more details.
[Unity5Problem.zip](https://github.com/unitycontainer/unity/files/1589750/Unity5Problem.zip)

Thanks,
Oleg

**Comment by ENikS** [comment]
[This note](https://github.com/unitycontainer/unity/releases/tag/5.2.1.311) explains the logic. [This issue](https://github.com/unitycontainer/unity/issues/170) has explanation of the fix.

**Comment by dos36** [comment]
This does not explain my issue.
Why objects behave differently if they have InjectionMember or not?
Can you please take a look into my attachment?

**Comment by ENikS** [comment]
Did you actually read the note?
This code runs with no issues:
```C#
static void Test_NoInjectionMember()
{
    var container = new UnityContainer();
    container.RegisterType<MyClassNoConstructor>(new ContainerControlledLifetimeManager());
    container.RegisterType<IInterface1, MyClassNoConstructor>();
    container.RegisterType<IInterface2, MyClassNoConstructor>();

    var myclass1 = container.Resolve<IInterface1>();
    var myclass2 = container.Resolve<IInterface2>();

    Debug.Assert(ReferenceEquals(myclass1, myclass2));
}
static void Test_WithInjectionMembers()
{
    var container = new UnityContainer();
    var constructor = new InjectionConstructor(new object[] { "value1", "value2" });
    var injectors = new InjectionMember[] { constructor };

    container.RegisterType<MyClassWithConstructor>(new ContainerControlledLifetimeManager(), injectors);
    container.RegisterType<IInterface1, MyClassWithConstructor>();
    container.RegisterType<IInterface2, MyClassWithConstructor>();

    var myclass1 = container.Resolve<IInterface1>();
    var myclass2 = container.Resolve<IInterface2>();

    Debug.Assert(ReferenceEquals(myclass1, myclass2));
}

```

**Comment by dos36** [comment]
Thanks for the quick reply. 

I see what you mean. But what if I want to add interceptor to my interface. I would need to put InjectionMember to each interface registration to make it work. Correct?

Updated code (Fails on Assert):

```
static void Test()
{
    var container = new UnityContainer();
    container.AddNewExtension<Interception>();
    var constructor = new InjectionConstructor(new object[] { "value1", "value2" });
    var interceptor = new Interceptor<InterfaceInterceptor>();
    var interceptionBehavior = new InterceptionBehavior<ComponentInterceptor>();

    var injectors = new InjectionMember[] { constructor, interceptor, interceptionBehavior };

    container.RegisterType<MyClass>(new ContainerControlledLifetimeManager(), injectors);
    container.RegisterType<IInterface1, MyClass>(injectors);
    container.RegisterType<IInterface2, MyClass>(injectors);

    var myclass1 = container.Resolve<IInterface1>();
    var myclass2 = container.Resolve<IInterface2>();

    myclass1.M1();
    myclass2.M2();
            
    Debug.Assert(ReferenceEquals(myclass1, myclass2));
}
```

I also updated [Unity5ProblemUpdated.zip](https://github.com/unitycontainer/unity/files/1591355/Unity5ProblemUpdated.zip)


I would really appreciate your help
Thanks.

**Comment by ENikS** [comment]
This example shows how to setup interceptors: https://github.com/unitycontainer/unity/issues/170

**Comment by dos36** [comment]
This example actually reproduces my issue!

```
var myclass1 = container.Resolve<IInterface1>();
var myclass2 = container.Resolve<IInterface2>();
myclass1.MyMethod1();   // Is intercepted
myclass2.MyMethod2();   // Is NOT intercepted
```
`myclass1` and `myclass2 `are two different objects, in spite of been configured as singletons.

**Comment by ENikS** [comment]
Correct. They are two different mappings.
Each interface is registered as different **types** and resolved as independent registrations. If you need centralized place than register all your interceptors on ``MyClass``.

**Comment by dos36** [comment]
I cannot register my interceptors on MyClass and access them by interface? Correct?

**Comment by ENikS** [comment]
What exactly are you trying to accomplish?

**Comment by dos36** [comment]
I am trying to have multiple interfaces mapped to one singleton type and I need to include interceptors for each interface. 
All these interfaces should resolve to single object (only one instance of singleton is created).
This functionality was working on v3.5 and this blocks us from upgrading to latest Unity.

**Comment by dos36** [comment]
What I can see now, is that we have two scenarios:
- Interceptors added to interfaces - each interface resolve to separate objects (multiple singleton objects created)
- No interceptors added to interfaces - all interfaces resolve to the same object (only one singleton object created)

I suppose it is not an expected behavior

**Comment by ENikS** [comment]
YOU GOT IT :)

**Comment by ENikS** [comment]
You could have singleton and individual interface wrappers for each interface you register. These could be singletons as well.

**Comment by dos36** [comment]
not sure I understand... What do you mean by "interface wrappers"? Can you give an example?
Will prevent from creating multiple objects?

**Comment by ENikS** [comment]
When you register interceptor on the interface it creates wrapper around instance as I presented above

**Comment by dos36** [comment]
Oh, I see. But each of those wrappers will reference to different objects, even if it is an singleton type. That is my problem....

**Comment by ENikS** [comment]
Let's say you want structure like this:
```
MyClassInstance (Singleton) ----> Interface1
                            \---> Interface2
                            \--->InterceptorWrapper (Singleton)  ----> Interface3
```
You register it like this:
```C#
container.RegisterType<MyClass>(new ContainerControlledLifetimeManager());

container.RegisterType<IInterface1, MyClass>();
container.RegisterType<IInterface2, MyClass>();
container.RegisterType<IInterface3, MyClass>(new ContainerControlledLifetimeManager(),
                                             new Interceptor<InterfaceInterceptor>(),
                                             new InterceptionBehavior<ComponentInterceptor>());
```
You want ``IInterface3`` to be singleton so it will not create wrapper every time it is resolved.

**Comment by dos36** [comment]
yes, but what I need is to have 
```
var myclass1 = container.Resolve<IInterface1>();
var myclass2 = container.Resolve<IInterface2>();
```
To be resolved into single object instance.

**Comment by ENikS** [comment]
As you can see in diagram they all resolve into the same singleton object.

**Comment by dos36** [comment]
```
container.RegisterType<MyClass>(new ContainerControlledLifetimeManager());

            container.RegisterType<IInterface1, MyClass>(new ContainerControlledLifetimeManager(),
                new Interceptor<InterfaceInterceptor>(),
                new InterceptionBehavior<ComponentInterceptor>());
            container.RegisterType<IInterface2, MyClass>(new ContainerControlledLifetimeManager(),
                new Interceptor<InterfaceInterceptor>(),
                new InterceptionBehavior<ComponentInterceptor>());
            

            var myclass1 = container.Resolve<IInterface1>();
            var myclass2 = container.Resolve<IInterface2>();
            myclass1.MyMethod1();
            myclass2.MyMethod2();
```

If we execute this code, _MyClass_ constructor will be called twice. Two different objects instances will be created. Regardless of been configured as a singleton

**Comment by dos36** [comment]
Yes, myclass1 and myclass2 are the same instances. 
But interceptor invokes only if I make a call to IInterface3

**Comment by ENikS** [comment]
This is by design

**Comment by dos36** [comment]
So I cannot have singleton object with multiple interfaces and interceptors?

**Comment by ENikS** [comment]
It looks like there is a bug. It should not call constructor twice.

**Comment by dos36** [comment]
yes, my point

**Comment by ENikS** [comment]
Will look into it

**Comment by dos36** [comment]
Thank you!
Can you, please, provide fix version, when it is possible?

**Comment by ENikS** [comment]
If all is well should release v5.5.1 by this weekend

**Comment by dos36** [comment]
Great! Thanks! 
Thank you for your time
