### ISSUE TITLE
Pass a type parameter in InjectionConstructor

### ISSUE THREAD

**Issue by MSRY** [unitycontainer/unity#178]
Hi,

Suppose I have a class with constructor defined as below:

public Dummy(Type type)
        {
            this.type= type;
        }

If I want to register it with 
unityContainer.RegisterType<IDummy, Dummy>(new InjectionConstructor(
                    typeof(Dummy)));

It will say Dummy does not have a constructor that takes the parameters (Dummy)

**Comment by ENikS** [comment]
Your constructor takes Type, not Dummy. Am I missing anything?

**Comment by MSRY** [comment]
Yes, I want to pass typeof(Dummy) which is a type.

________________________________

**Comment by ENikS** [comment]
This [note](https://github.com/unitycontainer/abstractions/releases/tag/2.2.0.102) explains the concept.
