### ISSUE TITLE
IndexOutOfRangeException when using HierarchicalLifetimeManager

### ISSUE THREAD

**Issue by guncho** [unitycontainer/unity#179]
Hi,

Recently we migrate from Unity 4 to Unity 5.5.0. Everything looked fine during testing but on our production environment one or two times a day the unity container completely crashes with IndexOutOfRangeException when resolving types registered using HierarchicalLifetimeManager.
Once this issue happen it starts to appear very often so we need to stop / start the web app. Then everything is back to normal.

We have an ASP.NET API 2.0 app and we create child container for each request. We use .net framework 4.7.1

During the period, there are no extraordinary requests. I assume that it is multithreading issue related with child containers. We are NOT registering any new types in the child containers.

Here is the exception:

Resolution of the dependency failed, type = 'SomeService', name = '(none)'.Exception occurred while: while resolving.Exception is: IndexOutOfRangeException - Index was outside the bounds of the array.-----------------------------------------------At the time of the exception, the container was:   Resolving SomeService,(none)  Resolving parameter 'asyncLockProvider' of constructor SomeService, SomeAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](SomeNamesplace.asyncLockProvider asyncLockProvider)    Resolving SomeNamesplace.AsyncLockProvider,(none)

Where the AsyncLockProvider is registered using HierarchicalLifetimeManager in the root container and is resolved from the child container.

We would really appreciate your help.
If we reproduce the exact scenario I will let you know.

Thanks,
Ivo

**Comment by ENikS** [comment]
It would help if you could capture full stack trace as well.

**Comment by ENikS** [comment]
I have a suspicion that Dictionary in HierarchicalLifetimeManager is being corrupted by operating on multiple threads. I've replaced it with ConcurrentDictionary and published it in Abstractions.3.1.1

You need to update to Container 5.5.2 and force Abstractions.3.1.1

**Comment by guncho** [comment]
Thank you very much for the fast fix. Everithing is working fine for around 20 hours now, so I assume thtat the issue is fixed.
