### ISSUE TITLE
Unity 5.5.0 results in MissingMethodException on Unity.Extension.ExtensionContext.get_Strategies()

### ISSUE THREAD

**Issue by ramonsmits** [unitycontainer/unity#180]
```
 System.MissingMethodException: Method not found: 'Unity.Strategy.IStagedStrategyChain`1<Unity.Builder.UnityBuildStage> Unity.Extension.ExtensionContext.get_Strategies()'.
```

**Comment by ENikS** [comment]
The method is no longer on the interface. It is Extension Method now: [Release Note](https://github.com/unitycontainer/abstractions/releases/tag/2.4.0.150) explains it.

**Comment by ramonsmits** [comment]
@ENikS That is a breaking change, it requires a recompile.

**Comment by ramonsmits** [comment]
Isn't Unity following Semver?

**Comment by ENikS** [comment]
I messed up v5.4.0. It was supposed to be a part of  Abstractions.3.0.0/Container.5.5.0 release

**Comment by ramonsmits** [comment]
@ENikS so dependencies now require a recompile for 5.4+

Seems you do not stick to SemVer and can introduce breaking changes? Does that mean we should restrict to the minor version and not to the major for Unity?

**Comment by ENikS** [comment]
I would do it this time. 
In feature I will try to follow SemVer better.
