### ISSUE TITLE
Could not load file or assembly 'Microsoft.Practices.Unity.Configuration' When unityContainer.LoadConfiguration() is used.

### ISSUE THREAD

**Issue by sidiki30** [unitycontainer/unity#181]
Hi, 
I have created a very simple console application to test the Unity IoC by using unity container configuration from the app.config. 

During the application initialization (unityContainer.LoadConfiguration();) the unity throws an exception: **"Could not load file or assembly 'Microsoft.Practices.Unity.Configuration'"**

The same application works with Unity 3.5 but not with Unity 5.5.0 with .NET 4.6.2.

**Applicaton structure**:

```
namespace ConsoleApp1
{
    public interface ILogger    {   }
    public class EventLogLogger : ILogger    {   }
}
```

**App.config**
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration" />
  </configSections>
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <namespace name="ConsoleApp1" />
    <container>
      <register type="ILogger" mapTo="EventLogLogger" />
    </container>
  </unity>
</configuration>
```
[Unity_IoC_With_App.Config.zip](https://github.com/unitycontainer/unity/files/1593198/Unity_IoC_With_App.Config.zip)

**Comment by ENikS** [comment]
DLL name has changed. You should use this:
```
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, 
Unity.Configuration" />
  </configSections>
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <namespace name="ConsoleApp1" />
    <container>
      <register type="ILogger" mapTo="EventLogLogger" />
    </container>
  </unity>
</configuration>
``````

**Comment by sidiki30** [comment]
Thanks, indeed it solved the problem.
