### ISSUE TITLE
Encountering Cast error after migrating to version 5 ...

### ISSUE THREAD

**Issue by perfectduffer** [unitycontainer/unity#182]
I just have migrated to version 5 and the project is broken now .. 
When i try to get configuration section by 

`var unitySection = (UnityConfigurationSection)configuration.GetSection("unity");`

I am doing this because container.LoadContainer() still seems to be coming from `microsoft.practices.unity.configuration` and i don't know where else to find it ...

My code is right here ...

 ```
var filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "unity.config");
            var fileMap = new ExeConfigurationFileMap { ExeConfigFilename = filePath };
            System.Configuration.Configuration configuration = ConfigurationManager.OpenMappedExeConfiguration(fileMap, ConfigurationUserLevel.None);
            var unitySection = (UnityConfigurationSection)configuration.GetSection("unity");
            _container = new UnityContainer();
            try
            {
                _container.LoadConfiguration(unitySection);
            }
            catch (Exception ex)
            {

                throw;
            }
```
my config file is like ..

```
<configuration>
  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration"/>
    <!--, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f-->
  </configSections>
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <sectionExtension type="Microsoft.Practices.Unity.InterceptionExtension.Configuration.InterceptionConfigurationExtension, Microsoft.Practices.Unity.Interception.Configuration" />

```

and i am getting the following exception at runtime... 

`[A]Microsoft.Practices.Unity.Configuration.UnityConfigurationSection cannot be cast to [B]Microsoft.Practices.Unity.Configuration.UnityConfigurationSection. Type A originates from 'Microsoft.Practices.Unity.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' in the context 'Default' at location 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\e30d3389\8432fb4f\assembly\dl3\78d8056a\00a0911a_8cffd001\Microsoft.Practices.Unity.Configuration.dll'. Type B originates from 'Unity.Configuration, Version=5.1.3.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' in the context 'Default' at location 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\e30d3389\8432fb4f\assembly\dl3\e9231b90\008be962_cd80d301\Unity.Configuration.dll'.`

**Comment by ENikS** [comment]
DLL names have changed to Unity.* . Change your configs like this:
```
<configuration>
  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Unity.Configuration"/> <------

  </configSections>
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <sectionExtension type="Microsoft.Practices.Unity.InterceptionExtension.Configuration.InterceptionConfigurationExtension, Unity.Interception.Configuration" /> <----------

```
