### ISSUE TITLE
RegisterInstance<TInterface>(this IUnityContainer container, string name, TInterface instance, LifetimeManager lifetimeManager) fails with ArgumentNullException

### ISSUE THREAD

**Issue by QuentinSuckling** [unitycontainer/unity#183]
Hi,

I've just updated from 5.3.0 to 5.5.2 and I've started getting a ArgumentNullException when I'm registering a named instance with a HierarchicalLifetimeManager;

This is my code -
_unityContainer.RegisterInstance<DbContext>(AwareDataContextNames.SystemConfigDbContext, context, new HierarchicalLifetimeManager());

Exception is at the bottom.

It looks like the issue is in HierarchicalLifetimeManager SynchronizedSetValue.
It looks like it's supposed to handle a null container parameter (it defaults to null) but it fails if it is -

        protected override void SynchronizedSetValue(object newValue, ILifetimeContainer container = null)
        {
            _values[container ?? throw new ArgumentNullException(nameof(container))] = newValue;
            container.Add(new DisposableAction(() => RemoveValue(container)));
        }

In RegisterInstance(Type toType, string name, object instance, LifetimeManager manager) it passes in null -

    public IUnityContainer RegisterInstance(Type toType, string name, object instance, LifetimeManager manager)
    {
       ....
      lifetimeManager.SetValue(instance, (ILifetimeContainer) null);

Exception -

`Resolving Aware.Server.Common.DataAccess.DBContext.DataAccessProvider`1[Aware.Enterprise.DataEntities.SystemConfig.EntityTypeCache],(none) (mapped from Aware.Server.Common.DataAccess.Interfaces.IDataAccessProvider`1[Aware.Enterprise.DataEntities.SystemConfig.EntityTypeCache], (none))        Resolving Aware.Server.Common.DataAccess.DBContext.DataAccessProvider`1[Aware.Enterprise.DataEntities.SystemConfig.EntityTypeCache],(none)        Calling constructor Aware.Server.Common.DataAccess.DBContext.DataAccessProvider`1[[Aware.Enterprise.DataEntities.SystemConfig.EntityTypeCache, Aware.Enterprise.DataEntities.SystemConfig, Version=1.1.6571.19985, Culture=neutral, PublicKeyToken=null]](Aware.Server.Common.DataAccess.Interfaces.IEntityContextFactory entityContextFactory, Aware.Server.Common.Interfaces.IEntityValidationService entityValidationService, Aware.Server.Common.DataAccess.Interfaces.IDataAuditService dataAuditService, System.Data.Common.DbConnection currentDbConnection) ---> System.ArgumentNullException: Value cannot be null.Parameter name: container   at Unity.Lifetime.HierarchicalLifetimeManager.SynchronizedSetValue(Object newValue, ILifetimeContainer container)   at Unity.Lifetime.SynchronizedLifetimeManager.SetValue(Object newValue, ILifetimeContainer container)   at Unity.UnityContainer.RegisterInstance(Type toType, String name, Object instance, LifetimeManager manager)   at Aware.Server.Controller.EntityContextFactory.CreateSystemConfigContext(DbConnection existingConnection) in D:\SourceControl\AwareNext\dev\Server\AwareEnterpriseServer\AwareEnterpriseServer\Business\AwareServerController\EntityContextFactory.cs:line 970   at Aware.Server.Controller.EntityContextFactory.GetAwareSystemConfigContext(DbConnection existingConnection) in D:\SourceControl\AwareNext\dev\Server\AwareEnterpriseServer\AwareEnterpriseServer\Business\AwareServerController\EntityContextFactory.cs:line 259   at Aware.Server.Controller.EntityContextFactory.GetEntityContext(Type type, DbConnection existingConnection) in D:\SourceControl\AwareNext\dev\Server\AwareEnterpriseServer\AwareEnterpriseServer\Business\AwareServerController\EntityContextFactory.cs:line 434   at Aware.Server.Common.DataAccess.DBContext.DataAccessProvider`1..ctor(IEntityContextFactory entityContextFactory, IEntityValidationService entityValidationService, IDataAuditService dataAuditService, DbConnection currentDbConnection) in D:\SourceControl\AwareNext\dev\Server\AwareEnterpriseServer\AwareEnterpriseServer\Common\AwareServerCommonDataAccess\DBContext\DataAccessProvider.cs:line 50   at lambda_method(Closure , IBuilderContext )   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)   at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)   at Unity.ObjectBuilder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)   at Unity.ObjectBuilder.Policies.ResolveBuildUpPolicy.BuildUp(IBuilderContext context)   at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)   at Unity.ObjectBuilder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)   at lambda_method(Closure , IBuilderContext )   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)   at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)   at Unity.ObjectBuilder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)   at Unity.ObjectBuilder.Policies.ResolveBuildUpPolicy.BuildUp(IBuilderContext context)   at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides)   --- End of inner exception stack trace ---   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, ResolverOverride[] resolverOverrides)   at Unity.UnityContainer.Resolve(Type type, String name, ResolverOverride[] resolverOverrides)   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)   at Aware.Server.Controller.BusinessServiceFactory.GetEntityBusinessService[T]() in
`

**Comment by ENikS** [comment]
Theoretically it should never be null. I'll take a look.
