### ISSUE TITLE
Registered types are not disposed

### ISSUE THREAD

**Issue by dos36** [unitycontainer/unity#185]
Dispose method is not invoked for registered types on UnityContainer.Dispose()
For singleton types it works as expected.

See attached [example](https://github.com/unitycontainer/unity/files/1615034/Unity5Problem.zip)

**Comment by ENikS** [comment]
Would be so much easier if you can create test case I can run without downloading and installing anything. Something like this:
```C#
        [TestMethod]
        public void ...TestMethod()
        {
            IUnityContainer container = new UnityContainer();

            container.RegisterType<...>();
            Assert.ThrowsSomething<...>(...);
        }
```

**Comment by ENikS** [comment]
Anything?

**Comment by ENikS** [comment]
Added [this request](https://github.com/unitycontainer/abstractions/issues/37) to resolve this.
