### ISSUE TITLE
Support async initialization

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/unity#186]
@imanushin Suggested this feature

Short: support ability to register factory which can load services in the asynchronous mode.

Why: Some complex application uses asynchronous loading logic. As an example, huge enterprise WPF application can do different http calls to load actual data. Financial applications load the actual market data (spots, etc.). These applications use the following warm up logic: 1. Open Splash screen to show user, what is happening for current moment. 2. Start creation main service/main screen, etc. 3. Main service requires to create tree of dependent services, so cascade creation is started 4. After main service loading finish - close splash screen and show main window.

Some of services uses asynchronous method to load configuration (from file or network), to load workspace, etc. Moreover, some of services can be created in parallel: user's avatar can be loaded in the same time with workspace creation. So, what we have: 1. Loading method can be asynchronous (e.g. splash screen window can use Task-based method simple) 2. Some of services works better in async mode 3. Some of services can be warmed up in parallel with other

Proposed design: 1. Support loading factory with method like "Task CreateAsync(IFirstDependency firstDependency, ISecondDependency secondDependency)". Some of services will use this method for creation 2. Support async methods in IUnityServiceLoader - they will be used by asynchronous factories and by global splash screen

Proposed implementation: 1. Services resolution logic can be the same. 2. Services initialization should work in the different ways of parallelism: 2.1. By default all services should be created one-by-one, without any parallel invocation. 2.2. In case, when factory implements special interfact IUnityInitializationContextProvider { object InitializationLock { get; } }, then: 2.2.1. If object is null - then factory methods should be called in the same way, as in item "2.1" 2.2.1 Otherwise, InitializationLock should be used for initialization task grouping. So, all initialization tasks should be groped by the resulting objects. This is the same, with using Synchronization Context in .Net. 3. I tried to show the simplest idea. Of course, we should not use object type for InitializationLock: we have to use interface with several members, to describe parallelism ways, etc.

**Comment by ENikS** [comment]
I am still not sure what this async should do. Any insights?

**Comment by imanushin** [comment]
@ENikS , I saw only one async-based IoC container, so I'll describe logic of code:

# Initialization

Default object creation for IoC uses the following idea: you should implement method like:

```
public IInterface CreateSettings(IDependency1 d1, IDependency2 d2)
{
      return new Implementation(d1, d2);
}
```

Or by using another way:

```
public IInterface CreateSettings(IContainer c)
{
      var d1 = c.Resolve<IDependency1>();
      var d2 = c.Resolve<IDependency2>();

      return new Implementation(d1, d2);
}
```

So, for current moment we should create factory method to initialize dependency. The example of initialization of Settings class:
```
public ISettings CreateSettings(IRemoveUrlResolver resolver)
{
      var settingsUrl = resolver.GetSettingsUrl();
   
      var userSettings = new HttpClient(...).Get(settingsUrl).StringContent; // this line can work in async mode

      var settingsData = Deserializer.Deserialize(userSettings);

      return Settings(settingsData);     
}
```

As you can see in the example above, for current moment Unity library allow us to create factory method for ISettings resolving, however **factory method should be synchronous only**.

However, for me it is better to allow the following factory method:
```
[UnityInitializationThreadContext(....)]
public async Task<ISettings> CreateSettings(IRemoveUrlResolver resolver)
{
      var settingsUrl = resolver.GetSettingsUrl();
   
      var userSettings = (await new HttpClient(...).GetAsync(settingsUrl)).StringContent; // <--- current code can work async

      var settingsData = Deserializer.Deserialize(userSettings);

      return Settings(settingsData);     
}
```

Code above has two major differences:
1. Developer can initialize dependencies using async non-blocking way
2. By using ```UnityMultithreadingInitialization``` developer can mark his code if it can work in parallel with another initialization. For example: application can do different remote calls during start, moreover - all of them can be executed in parallel. 

# What API I'd like to see

Please see my async settings initialization as example. What I'd like to see:
1. Ability to write asynchronous initialization, to avoid thread blocking during remote call
2. Ability to initialize several components in parallel
3. Next phase - ability to get instance from ServiceLocator by using async method, such ```var service = await serviceLocator.GetInstanceAsync()```

# Benefits:
1. Faster application initialization
2. Unblocking initialization (e.g. initialization task unlocks thread during awaiting for remote service)

**Comment by ENikS** [comment]
To boil it down to one phrase you want an ability to create async factory methods? Why couldn't you just request/register: ``Func<Task<T>>`` ?

**Comment by ENikS** [comment]
If it is easier, you could write in Russian.

**Comment by ENikS** [comment]
What about this way of doing it?
public async Task<ISettings> CreateSettings(Func<Task<T>> method)
{
   var settings = await method();
   ...
}

**Comment by imanushin** [comment]
> To boil it down to one phrase you want an ability to create async factory methods? Why couldn't you just request/register: Func<Task<T>> ?
> 
> Am I missing something?

Yes, just async factory methods. For current moment I'm unable to create async factory method, however then request dependency in sync mode.

E.g. if ISettings are initialized in async way, then I'm unable to inject them into such ctor:

```
public class SomeService(ISettings settings)
{
     ...
}
```

**Comment by ENikS** [comment]
Can you create a test case with this idea in mind? 
Demonstrate your idea with code, doesn't need to be Unity based.

**Comment by imanushin** [comment]
@ENikS , agree, will do this on the nearest weekend

**Comment by imanushin** [comment]
@ENikS , please see here - https://github.com/imanushin/unity-async-container-example

**Comment by ENikS** [comment]
I have a feeling it is easier to implement async functionality as extension methods on top of IUnityContainer interface.
There is nothing Unity needs to do internally to accommodate any of that. Wrapping everything in Task<> and running it on the thread pool could be done externally with no Unity modification. Standard parallel library stuff.

It is debatable if context switching cost is justifiable for these resolutions but you wouldn't know until you try it in real life scenario.

I wouldn't bother with Register[Type/Instance]Async because it is fast as it is and would add a lot of 
context switching overhead. Perhaps something like Container.[ConfigureAsync(...)](https://github.com/unitycontainer/configuration) or similar.

Task<T> ResolveAsync<T>(this IUnityContainer ... ) should be trivial to implement as extension. I would just add it to [this](https://github.com/unitycontainer/abstractions/blob/master/src/Utility/UnityContainerExtensions.cs) class.

Would you like to try?

**Comment by hanabi1224** [comment]
ref: https://github.com/unitycontainer/unity/issues/196 
Is it possible to turn off potential exception when disposing Task?  Otherwise ppl always need to and try catch around  using(container) to avoid crash

**Comment by ENikS** [comment]
I am thinking about v6 of Unity and I am considering adding async functionality as well. How about we start from scratch and do requirements first? 

The first question is how interface should look like with addition of async methods and should it use Task or [ValueTask](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#generalized-async-return-types)?

**Comment by ENikS** [comment]
IUnityContainerAsync

**Comment by ENikS** [comment]
Added new interface:
```C#
using System;
using System.Threading.Tasks;
using Unity.Lifetime;
using Unity.Registration;
using Unity.Resolution;

namespace Unity
{
    public interface IUnityContainerAsync : IUnityContainer
    {
        IUnityContainer RegisterTypeAsync(Type registeredType, string name, Type mappedTo, LifetimeManager lifetimeManager, params InjectionMember[] injectionMembers);

        Task<object> ResolveAsync(Type type, string name, params ResolverOverride[] resolverOverrides);
    }
}
```

**Comment by ENikS** [comment]
Addressed [here](https://github.com/unitycontainer/abstractions/issues/57)
