### ISSUE TITLE
Should I use Unity or Unity.AspNet.WebApi for Web API application?

### ISSUE THREAD

**Issue by skylee91** [unitycontainer/unity#187]
What is the differences of [Unity](https://github.com/unitycontainer/) vs [Unity.AspNet.WebApi](https://github.com/unitycontainer/aspnet-webapi)?

Based on the [documentation from Microsoft](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/dependency-injection), it used Unity. 

However, I found a [blog, Codeclimber](http://codeclimber.net.nz/archive/2015/02/20/using-entity-framework-within-an-owin-hosted-web-api-with/) which introduced how to use Unity.AspNet.WebApi.

I am confused...

**Comment by ENikS** [comment]
Use Unity.AspNet.WebApi

**Comment by skylee91** [comment]
@ENikS What is the differences between Unity and Unity.AspNet.WebApi?

**Comment by ENikS** [comment]
Just different packaging, these are the same from functionality point of view
