### ISSUE TITLE
could not get unity release source code

### ISSUE THREAD

**Issue by oleksabor** [unitycontainer/unity#188]
Please help me to get unity release source code. I'd like to check 5.5.3 Unity container 5.5.3 release source code.
So I click on https://github.com/unitycontainer/unity/releases  and then on https://github.com/unitycontainer/unity/archive/5.5.3.421.zip

But the problem is that archive is empty - there are only top-level directories (like Abstractions, CommonServiceLocator etc) but without content.

I've tried to do it with git like 
git clone https://github.com/unitycontainer/unity.git
git checkout v5.x
but the result is the same - no .cs files are available.

**Comment by ENikS** [comment]
Unity repository is a links (submodules) only repo. 
If you want to get complete build tree you need:
- Clone Unity repo
- update and init submodules
- if you need certain release prior to updating sub-modules you need to checkout that release

This workflow is very common and described in detail elsewhere.
