### ISSUE TITLE
System.MethodAccessException when trying to instantiate new UnityContainer

### ISSUE THREAD

**Issue by qmfrederik** [unitycontainer/unity#19]
Hi,

I'm moving [this](https://unity.codeplex.com/workitem/12780) issue over from Codeplex:

The following code: 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Practices.Unity;

namespace ConsoleApplication3
{
    class Program
    {
        static void Main(string[] args)
        {
            var container = new UnityContainer();
        }
    }
}
```

Causes the following exception:

```
System.MethodAccessException: Attempt by security transparent method 'Microsoft.Practices.ObjectBuilder2.StagedStrategyChain1<TStageEnum>.NumberOfEnumValues()' to access security critical method 'System.Linq.Enumerable.Where<System.Reflection.FieldInfo>(System.Collections.Generic.IEnumerable1<System.Reflection.FieldInfo>, System.Func2<System.Reflection.FieldInfo,Boolean>)' failed.
at Microsoft.Practices.ObjectBuilder2.StagedStrategyChain1.NumberOfEnumValues()
at Microsoft.Practices.ObjectBuilder2.StagedStrategyChain`1..ctor()
at Microsoft.Practices.Unity.UnityContainer.InitializeBuilderState()
at Microsoft.Practices.Unity.UnityContainer..ctor(UnityContainer parent)
at Microsoft.Practices.Unity.UnityContainer..ctor()
```

in at least some conditions. The original reporter says:

> Works on Win7, Win8 with Unity 3.504 or 3.505_prerelease 
> With Win8.1 the exception occurs

We seem to have the code running on Win 8.1 but it fails for at least one of our customers.

Any thoughts?

**Comment by xtratio** [comment]
Hi. I had the same problem.
I've updated the Unity in the project to 4.0.1 and some other packages and got the error.
My solution:
- I removed all Nuget packages files from the catalog packages. 
- Run the project and made rebuilding. The packages were loaded again and the error disappeared.

**Comment by qmfrederik** [comment]
For at least one of our customers, upgrading from .NET 4.5 to .NET 4.6 on Windows 8.1 seems to have fixed this problem.

**Comment by ENikS** [comment]
It could be safely assumed it is fixed by now
