### ISSUE TITLE
Is it possible to have a lifetimemanager that build object on demand

### ISSUE THREAD

**Issue by hanabi1224** [unitycontainer/unity#190]
(AFAIK, this is not achievable right now please correct me if I'm wrong :)
The idea is similar to how many javascript MVVM library works (knockoutjs, vuejs, angularjs, reactjs),  object are only refreshed when any of its dependency get changed.  Thanks!

**Comment by ENikS** [comment]
I am not sure what you mean. Once object is created Unity is not involved anymore. Can you provide mode details?

**Comment by hanabi1224** [comment]
@ENikS  thanks for the reply, however, DeferredResolveBuildPlanPolicy is an internal class, how can I use it? Or is it registered by default?  Regarding my ask, consider below example,  please let me know if it does not make sense

container.Register<IA, A>(new MyLifeTimeManager())  (  A depends on IB)
container.Register<IB>(b1);
container.Register<IC, C>(new MyLifeTimeManager());  (C depends on IA)

var a1 = container.Resolve<IA>();
var a2 = container.Resolve<IA>();
a1.Should().Be(a2);

var c1 = container.Resolve<IC>();
var c2 = container.Resolve<IC>();
c1.Should().Be(c2);

container.Register<IB>(b2);
var a3 = container.Resolve<IA>();
var c3 = container.Resolve<IC>();

a3.Should().NotBe(a2);
c3.Should().NotBe(c2);

var a4 = container.Resolve<IA>();
var c4 = container.Resolve<IC>();

a4.Should().Be(a3);
c4.Should().Be(c3);

**Comment by ENikS** [comment]
I don't think this could work.

**Comment by hanabi1224** [comment]
@ENikS  Can you be more specific? Is the idea not making sense or the feature is not feasible?

**Comment by ENikS** [comment]
Correct me if I am wrong, as I understand your lifetime manager must know if registration has updated and update based on that?

**Comment by hanabi1224** [comment]
@ENikS  You are right, and actually I can achieve this by looking at dependencies from ILifetimeContainer,  the only problem I have is in if dependencies are registered in parent container, there's no way to get its lifetimecontainer from child container

**Comment by ENikS** [comment]
I don’t think we could go around this

**Comment by hanabi1224** [comment]
@ENikS  Is it possible to pass ancestor ILifetimeContainers to abstract functions in LifetimeManager?  That's all I need.

**Comment by ENikS** [comment]
It would be possible in Unity 6

**Comment by hanabi1224** [comment]
@ENikS That's sweet, thx!

**Comment by ENikS** [comment]
OK, you are in luck. I think current implementation has all you need to get it working. 
When GetValue or SetValue of LifetimeManager (ILifetimePolicy) is called it gets [reference to ILifetimeContainer](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/ILifetimePolicy.cs).  If you look at [ILifetimeContainer](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/ILifetimeContainer.cs) you will see it now includes reference to the owner Container. Getting the parent of it is trivial...

**Comment by hanabi1224** [comment]
@ENikS  Is it possible to provide a built-in lifetime manager to support this?  Some other IoC frameworks do provide this out of box.
e.g. 
https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#instance-per-dependency

**Comment by ENikS** [comment]
I do not understand, how is it different from transient and what is the purpose of it?
