### ISSUE TITLE
Exception in container dispose

### ISSUE THREAD

**Issue by hanabi1224** [unitycontainer/unity#196]
I saw 'A task may only be disposed if it is in a completion state' exceptions in container dispose function, is it by design or should it be handled internally?  Thanks!

**Comment by ENikS** [comment]
This is something outside of Unity control. Unity has no code dealing with Tasks.

**Comment by hanabi1224** [comment]
@ENikS  I don't think this is outside of Unity,  registration type here is Task<T>, and during unity container disposal it tries to dispose that task object and get this error when task is started but not completed, thus 
using(container) pattern will throw exception

**Comment by ENikS** [comment]
Well, isn’t it how it supposed to be?
Please provide test case so I can replicate it

**Comment by hanabi1224** [comment]
@ENikS  I think it's OK to throw exceptions from Dispose if that is by design, the thing I worry about is if it's disposing objects in sequence, some disposable objects may not get chance to be disposed thus causes memory leak when there's error.

**Comment by ENikS** [comment]
I need a test case to check it out.

**Comment by hanabi1224** [comment]
@ENikS  Here you go

using (var container = new UnityContainer())
            {
                container.RegisterInstance<Task>(Task.Run(async () => await Task.Delay(TimeSpan.FromMinutes(1))));
                container.Resolve<Task>();
            }

**Comment by ENikS** [comment]
Well, this is by design. To prevent it from disposing the task you need to register it with ExternallyControlledLifetimeManager(). Abviously you need to keep reference to Task somewhere

**Comment by hanabi1224** [comment]
@ENikS I understand exception is by design, but I think the memory leak part needs to be fixed

**Comment by ENikS** [comment]
If it is disposed, what memory leak are you talking about?

**Comment by hanabi1224** [comment]
@ENikS  also it's useful in many cases to use Task as registration type because async await is not officially supported in API level (which is being discussed in other threads)

**Comment by hanabi1224** [comment]
@ENikS  e.g. I have registered 10 disposable objects, 1 of them is task, when this exception happens, the other 9 objects might not get change to be disposed, does that make sense?

**Comment by ENikS** [comment]
I see, you are saying that is exception happened it will not dispose the rest?

**Comment by ENikS** [comment]
Thinking about it a bit more I see it is a desired behavior. You do not want to hide exception in Dispose method. 
In your case the Task must be canceled before disposing the container or cancellation should be part of Disposing the Task. It is your responsibility to make sure it is handled.

**Comment by hanabi1224** [comment]
@ENikS  You don't necessarily need to hide any exception,  the IoC framework should grantee disposable objects are disposed, are throw all exceptions at the end, which is a more robust design that does not leak  memory unexpected without hiding any exceptions

**Comment by ENikS** [comment]
@hanabi1224 Would you like to send a pull request?

**Comment by hanabi1224** [comment]
@ENikS   PR is created https://github.com/unitycontainer/container/pull/55
