### ISSUE TITLE
Payload contains two or more files with the same destination path 'CommonServiceLocator.dll'. 

### ISSUE THREAD

**Issue by j-fritsch** [unitycontainer/unity#197]
I'm getting the following error:

> Payload contains two or more files with the same destination path 'CommonServiceLocator.dll'. 
> 
> Source files: 
> C:\Users\me\\.nuget\packages\commonservicelocator\2.0.2\lib\netstandard1.0\CommonServiceLocator.dll
> C:\Users\me\\.nuget\packages\unity\5.5.8\lib\netstandard1.0\CommonServiceLocator.dll

I am using the latest full [Unity package](https://www.nuget.org/packages/Unity/) but I am also using the latest [MvvmLightLibs package](https://www.nuget.org/packages/MvvmLightLibs/) that has a dependency to [CommonServiceLocator](https://www.nuget.org/packages/CommonServiceLocator/).

What are my options here? Must I install each of the necessary Unity components individually instead of using the single package?

**Comment by ENikS** [comment]
Try individual packages for Abstractions and Container. Complete package includes CommonServiceLocator which creates the conflict.

**Comment by j-fritsch** [comment]
Sounds good. I will go that route. Thanks!
