### ISSUE TITLE
Why not support  netcoreapp2.0 and netstandard2.0

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/unity#198]
Why not support  netcoreapp2.0 and netstandard2.0

**Comment by ENikS** [comment]
Both netcoreapp and netstandard are capable of linking to netstandard1.0
What is it that you are trying to accomplish by adding these frameworks?

**Comment by ghd258** [comment]
cross platform

**Comment by ENikS** [comment]
Unity implements the lowest denominator framework to be compatible across all platforms. I am not sure it will add any value by adding these unless there are issues. Do you have any issues linking to Container library in these?

**Comment by witskeeper** [comment]
why Unity.Interception not support  netstandard or .NETCoreApp 
but Unity.Abstractions support netstandard and .NETCoreApp 
https://www.nuget.org/packages/Unity.Interception/

**Comment by ghd258** [comment]
Need Unity.Interception not support netstandard or .NETCoreApp

**Comment by ENikS** [comment]
Interception requires API not available in netstandardXX. It is only available in desktop frameworks netXX

**Comment by ghd258** [comment]
netstandard or .NETCoreApp Which intercepts API

**Comment by xcap2000** [comment]
Is the support for dotnet core/standard interception planned to be addressed in future releases of unity?

**Comment by ghd258** [comment]
yes

**Comment by ghd258** [comment]
Someone has already implemented the support of support netstandard and.NETCoreApp address as follows https://github.com/Chavoshi/Unity.NetCore, why is the official not able to achieve it?

**Comment by ghd258** [comment]
https://github.com/Chavoshi/EnterpriseLibrary.NetCore  he time which I have uploaded these packages there where no official version of Unity and specifically Unity.Interception so I ported the Unity 4.0 libraries all by myself to .Net Core 2.0.
As I checked they still do not ported Unity.Interception (or maybe it's not part of their plan at all) So as I wanted to port the Enterprise Library as well to .Net Standard I needed both packages together.

**Comment by ENikS** [comment]
I offered @Chavoshi to help with the porting, will see what he will decide

**Comment by Chavoshi** [comment]
https://github.com/Chavoshi/Unity.NetCore/issues/2

**Comment by swisscoder** [comment]
Is this the reason behind version 5.8.7 onwards depending on .netcoreApp and .netStandard? As those dependencies are there, it's kind of a breaking change for older setups, isn't it?
