### ISSUE TITLE
ArgumentNullException in DefaultUnityConstructorSelectorPolicy

### ISSUE THREAD

**Issue by thomaslevesque** [unitycontainer/unity#2]
In some cases, `ParameterInfo.GetCustomAtributes` returns null; `DefaultUnityConstructorSelectorPolicy.CreateResolver` doesn't account for that, and passes the result to `OfType` without checking for null, which throws an `ArgumentNullException`.

Note: I saw it happen only in a very specific case: when trying to resolve a type that had been generated dynamically with Reflection.Emit, and the constructor parameters had not been properly defined with `DefineParameter`.

(technically, the bug was in my codegen rather than in Unity, but Unity could easily handle that case)

**Comment by Maxwe11** [comment]
@thomaslevesque could you say what bug was in your codegen? Seems I'm getting same error.

**Comment by Maxwe11** [comment]
My sample repro
```c#
var name = new AssemblyName("BarAssembly");
var assembly = AppDomain.CurrentDomain.DefineDynamicAssembly(name, AssemblyBuilderAccess.Run);
var module = assembly.DefineDynamicModule("BarModule");
var ctorParameterTypes = new Type[] {typeof (IUnityContainer)};
var typeBuilder = moduleBuilder.DefineType("Bar", TypeAttributes.Public, typeof(Foo));
var ctorBuilder = typeBuilder.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, ctorParameterTypes);
var ilGen = ctorBuilder.GetILGenerator();
var baseTypeCtor = typeof(Foo).GetConstructor(BindingFlags.Instance | BindingFlags.NonPublic, null, ctorParameterTypes, null);

ilGen.Emit(OpCodes.Ldarg_0);
ilGen.Emit(OpCodes.Ldarg_1);
ilGen.Emit(OpCodes.Call, baseTypeCtor);
ilGen.Emit(OpCodes.Nop);
ilGen.Emit(OpCodes.Nop);
ilGen.Emit(OpCodes.Nop);
ilGen.Emit(OpCodes.Ret);

Type type = typeBuilder.CreateType();
var container = new UnityContainer();
container.Resolve(type);
```

**Comment by thomaslevesque** [comment]
@Maxwe11, I had just forgotten to define the parameters with `.DefineParameter(...)`. Your code seems to have the same issue.

**Comment by Maxwe11** [comment]
@thomaslevesque great thanks :+1:
