### ISSUE TITLE
Summary documentation for 4.0?

### ISSUE THREAD

**Issue by JohnTasler** [unitycontainer/unity#20]
With the major version change to 4, it seems there should be something in the README.md (or a sibling file) that describes what's been fixed, added, optimized, etc. in this new version.

Is there such a document?

**Comment by xperiandri** [comment]
+1

**Comment by reader-man** [comment]
+3 from me :)

**Comment by nrogoff** [comment]
Agreed. Seems crazy not to say what's changed. Especially as the update has just broken my project and there are clearly breaking changes here!

As this project is now managed fully by 'the community', has anyone thought about starting to populate the wiki too? One of Unity's best aspects was great documentation and this is now very lacking here on GitHub.

**Comment by rafakwolf** [comment]
+1

**Comment by DavidDeSloovere** [comment]
Release notes are a must have.

**Comment by nelsonmorais** [comment]
+1

**Comment by Peak-Tsui** [comment]
+1  i want some detail documents

**Comment by arielszklarkiewicz** [comment]
Hi,

We're working to publish a CoreClr-compatible version soon. It will come with the release notes too.

Thanks for the patience.

**Comment by mdonatas** [comment]
+1 please add the changelog

**Comment by sr258** [comment]
+1 This is really important.

**Comment by bobingham** [comment]
+5 beginner problems.

**Comment by edmondtang** [comment]
+1 Would like to know of any breaking changes.

**Comment by ENikS** [comment]
Duplicate #117
