### ISSUE TITLE
A change log would be helpful

### ISSUE THREAD

**Issue by kcragin** [unitycontainer/unity#202]
Is there a change log?

If not, one would be helpful. Periodically we get updates via NuGet, but there is no indication about what was fixed or changed. We can certainly diff the code, but that's time consuming as you could imagine.

**Comment by ENikS** [comment]
It pays to do little search:

https://github.com/unitycontainer/unity/releases
https://github.com/unitycontainer/abstractions/releases
https://github.com/unitycontainer/container/releases

If this is not enough you could **contribute** more comprehensive release notes.

**Comment by kcragin** [comment]
Fair enough. Often I see open source with dedicated websites or links from the readme.md. I tried several web searches and didn't turn up the notes. But thank you for the links.

**Comment by ENikS** [comment]
This is ongoing epic struggle detailed in [this thread](https://github.com/unitycontainer/unity/issues/117). Unfortunately I just don't have bandwidth to do it all at once.
