### ISSUE TITLE
Resolution returning null every 200 requests

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [unitycontainer/unity#203]
I registered my type like this:

`container.RegisterType<IUnitOfWork, MainDataContext>(new PerRequestLifetimeManager(), new InjectionMember[] { new InjectionConstructor("") });`

and i try to resolve it like this:

`_unitOfWork = container.Resolve<IUnitOfWork>(new ParameterOverride("connectionString", currentConnection));`

but at a alarming rate (1 every 200) this resolution returns null! retrying to resolve does not work...

Details:
- Problem first detected on Unity version 5.6 but persist on 5.7
- Using .net 4.7 with 4.7 runtime
- If I inspect the container registrations, the one I'm hoping to get is there!

**Comment by ENikS** [comment]
Could you create Unit test I could run?

**Comment by Leonardo-Ferreira** [comment]
let me see what i can do

**Comment by Leonardo-Ferreira** [comment]
this is very strange... i just ran a small-scale load test on my local machine (avg 500 concurrent requests per second) nothing failed, everything worked as expected... stopped the app, and remembered one more test i could do, fired-up the app again and now things are failing like 1 in 5...

**Comment by ENikS** [comment]
So, is it broken or not?

**Comment by Leonardo-Ferreira** [comment]
i think it is... i'm trying to find out if there's any correlation to new sessions being open, or wether the app is hot/cold and other variables

**Comment by ENikS** [comment]
Let me know...

**Comment by Leonardo-Ferreira** [comment]
yeah... ok, the problem persisted... i even updated to the latest version (5.7.3) but the resolution fails every now and then...

it's does not seem to be bound to concurrency or memory exhaustion or other regular issues...

How do you recommend me to create such test? would you like me to send our code? you will need a sql server instance to get it working... i can provide a database...

**Comment by ENikS** [comment]
Can you replicate the issue without SQL server, With just mock data?

**Comment by ENikS** [comment]
A am assuming this is no longer relevant?
