### ISSUE TITLE
Unity and .Net Core 2 and forward

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [unitycontainer/unity#205]
Is there any chance for us to get a example/tutorial on how to hook this with Asp.Net Core 2+? tks a lot...

**Comment by ENikS** [comment]
I am a bit busy with v6 at the moment. 
Do you want to try to create it yourself? I will help if you get stuck..

**Comment by Leonardo-Ferreira** [comment]
yeah sure! i actually have been trying for a day or more to do so... i've been trying to do so like this: https://stackoverflow.com/questions/39173345/unity-with-asp-net-core-and-mvc6-core/39173346?noredirect=1#comment85597225_39173346
right now i'm stuck on 2 parts: 

- `IsRegistered()` is yielding false positives for registrations such as "IServer" and other MVC registrations, therefore not using the fallback and then breaking...

- After blunt forcing a `|| !Type.FullName.Contains("MyProject")` that forces the fallback, i get a parameter null exception that i can't seem to track back...

Here's a link to a sample code: https://wetransfer.com/downloads/cd1bc4dff43f0cd3a03f312dc414fe5c20180315133154/d28259a05122f4166a8b08b41a49854420180315133155/5934fd

**Comment by Leonardo-Ferreira** [comment]
@ENikS the link above is now expired... when you get a chance ping me here and ill re-upload...

**Comment by ENikS** [comment]
Done
