### ISSUE TITLE
i hope Unity.Configuration could support .net framework4.0

### ISSUE THREAD

**Issue by skyimp2017** [unitycontainer/unity#207]
我现有项目所有类库均是framework4.0（为了支持xp），在引入Unity后发现无法引用Unity.Configuration，因为它不支持4.0，希望以后能支持framework4.0，万分感谢！

**Comment by skyimp2017** [comment]
All of my existing project libraries are framework4.0 (in order to support XP), I found it impossible to reference Unity.Configurationafter introducing Unity because it doesn't support 4.0, I hope it can support framework4.0 in the future. Thank you very much!

**Comment by ENikS** [comment]
Would you like to port it into .Net 4 and send a pull request?

**Comment by ENikS** [comment]
Fixed in https://github.com/unitycontainer/configuration/commit/091d5cc43526a5006ca6bbc372ad187f08cef3ce
