### ISSUE TITLE
Unable to resolve type registered dynamically in a strategy

### ISSUE THREAD

**Issue by rikrak** [unitycontainer/unity#208]
I noticed this in v5.7.3.  It appears to be a regression from v5.5.0
Replication project: https://github.com/rikrak/UnityResolutionBug

I've just upgraded to v5.7.3 from v5.5.0 and I'm finding that the container will no longer resolve types that are registered dynamically as part of a strategy.  (Unfortunately I'm not overly familiar with the way Unity works, so I may be mis-using some terminology here).

At runtime the exception is:
```
Test method UnityBuildStrategyDemo.V573.DynamicDependencyTests573.ShouldResolveILogWithInstanceDependentOnResolvingType threw exception: 
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'UnityBuildStrategyDemo.Stub.ClassWithLogDependency', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, log4net.ILog, is an interface and cannot be constructed. Are you missing a type mapping?

At the time of the exception, the container was: 
  Resolving UnityBuildStrategyDemo.Stub.ClassWithLogDependency,(none)
  Resolving parameter 'logger' of constructor UnityBuildStrategyDemo.Stub.ClassWithLogDependency(log4net.ILog logger)
    Resolving log4net.ILog,(none)
 ---> System.InvalidOperationException: The current type, log4net.ILog, is an interface and cannot be constructed. Are you missing a type mapping?
    Test method UnityBuildStrategyDemo.V573.DynamicDependencyTests573.ShouldResolveILogWithInstanceDependentOnResolvingType threw exception: 
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'UnityBuildStrategyDemo.Stub.ClassWithLogDependency', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, log4net.ILog, is an interface and cannot be constructed. Are you missing a type mapping?

At the time of the exception, the container was: 
  Resolving UnityBuildStrategyDemo.Stub.ClassWithLogDependency,(none)
  Resolving parameter 'logger' of constructor UnityBuildStrategyDemo.Stub.ClassWithLogDependency(log4net.ILog logger)
    Resolving log4net.ILog,(none)
 ---> System.InvalidOperationException: The current type, log4net.ILog, is an interface and cannot be constructed. Are you missing a type mapping?

```

I've created a project with tests that illustrates the problem, and how the same code worked with v5.5.0.

**Comment by ENikS** [comment]
Yes, the way types are registered has changed.

If you want to use log4net, you could use [this](https://github.com/unitycontainer/log4net) package. There is no need to reinvent the wheel.

**Comment by ENikS** [comment]
It does as well. 
If you want to see how it could be done with the latest, loot at [this](https://github.com/unitycontainer/microsoft-logging/blob/master/src/LoggingExtension.cs) of [this](https://github.com/ENikS/NLog/blob/master/src/NLogExtension.cs) implementations.

**Comment by rikrak** [comment]
Ta,  I'll take a look at those references.  Thanks for the feedback :-)

**Comment by ENikS** [comment]
Look at the unit tests for examples

**Comment by rikrak** [comment]
Good news!  The[ microsoft-logging](https://github.com/unitycontainer/microsoft-logging) example looks like it works for me with some minor changes to my code.

Thanks again for the help! :-)
