### ISSUE TITLE
Publish Unity.WebApi as NuGet package

### ISSUE THREAD

**Issue by josundt** [unitycontainer/unity#21]
I noticed that the source code in this repo contains a project "Unity.WebApi". 
If this implementation is stable, I'd appreciate if it was published to the NuGet server. 
I have till now been using a NuGet package with the excact same name(https://github.com/devtrends/Unity.WebAPI), but this unfortunately does not support Unity 4.

**Comment by davidbreyer** [comment]
I believe what you are looking for has been published under Unity.AspNet.WebApi (https://www.nuget.org/packages/Unity.AspNet.WebApi/).

**Comment by josundt** [comment]
Thanks! 
Tip: I think this NuGet package needs some improved keywords tagging or similar, because it does not appear high in the list when searching for "Unity" in the NuGet explorer window inside Visual Studio and it is a bit hard to discover!

**Comment by ENikS** [comment]
The functionality will be provided in ``Unity.Microsoft.DependencyInjection`` package
