### ISSUE TITLE
Updating to 5.8 with netstandard breaks build

### ISSUE THREAD

**Issue by dansiegel** [unitycontainer/unity#212]
It seems that at some point you've either added a dependency on System.IServiceProvider or accidentally removed the dependency from your NuGet. After upgrading to 5.8.(1,2) from 5.5.5 this results in a build error for netstandard projects which require a reference to System.ComponentModel.

**Comment by ENikS** [comment]
You lost me. Is it causing conflict or is it required but missing?

**Comment by dansiegel** [comment]
Apparently it's required but missing. Prism has no requirement for it but apparently Unity 5.8 does....

**Comment by ENikS** [comment]
It has [reference](https://github.com/unitycontainer/container/blob/032e176a407502e5da6bdc2425701fe4624b48a8/src/Unity.Container.csproj) to System.ComponentModel 4.3.0 for net standard 1.0

Is it not restoring? Could you be more specific? Or perhaps point me to breaking code?

**Comment by dansiegel** [comment]
If you look on [NuGet](https://www.nuget.org/packages/Unity) your generated package has NO dependencies for any targets. The result is that Unity does have a dependency that isn't automatically resolved by consuming projects.

**Comment by ENikS** [comment]
I'll release fixed package a bit later...

**Comment by ENikS** [comment]
Deployed v5.8.3, should be available in a few
