### ISSUE TITLE
Dispose method of a service is called twice on child container dispose.

### ISSUE THREAD

**Issue by eglauko** [unitycontainer/unity#213]
If i register something like this:

Container.RegisterType<IChildContainerDisposeService, ChildContainerDisposeService>(new HierarchicalLifetimeManager());

works fine;

but, if i register something like this:

Container.RegisterType<IChildContainerDisposeService, ChildContainerDisposeService>(new HierarchicalLifetimeManager());
Container.RegisterType< ChildContainerDisposeService >(new HierarchicalLifetimeManager());

then, the dispose method of ChildContainerDisposeService is called twice.

UnitTest
----------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Unity;
using Unity.Lifetime;

namespace Unity.Test
{
    [TestClass]
    public class ChildContainerDisposeTest
    {
        IUnityContainer Container;

        [TestInitialize]
        public void Init()
        {
            Container = new UnityContainer();
            Container.RegisterSingleton<ChildContainerDisposeLogger>();
            Container.RegisterType<IChildContainerDisposeService, ChildContainerDisposeService>(new HierarchicalLifetimeManager());
            Container.RegisterType<ChildContainerDisposeService>(new HierarchicalLifetimeManager());
        }

        [TestCleanup]
        public void Clean()
        {
            Container?.Dispose();
        }

        [TestMethod]
        public void ChildContainerDisposeServiceTest()
        {
            var logger = Container.Resolve<ChildContainerDisposeLogger>();
            logger.Clear();

            var rootService = Container.Resolve<IChildContainerDisposeService>();

            Assert.AreEqual(1, logger.Construtor, "Construtor log must be 1. First resolve on Root Container.");
            Assert.AreEqual(0, logger.Dispose, "Dispose log must be 0. First resolve on Root Container.");

            var childContainer = Container.CreateChildContainer();
            var childService = childContainer.Resolve<IChildContainerDisposeService>();

            Assert.AreEqual(2, logger.Construtor, "Construtor log must be 2. First resolve on Child Container.");
            Assert.AreEqual(0, logger.Dispose, "Dispose log must be 0. First resolve on Child Container.");

            var childService2 = childContainer.Resolve<IChildContainerDisposeService>();

            Assert.AreEqual(2, logger.Construtor, "Construtor log must be 2. Second resolve on Child Container.");
            Assert.AreEqual(0, logger.Dispose, "Dispose log must be 0. Second resolve on Child Container.");

            childContainer.Dispose();

            Assert.AreEqual(2, logger.Construtor, "Construtor log must be 2. Disposed Child Container.");
            Assert.AreEqual(1, logger.Dispose, "Dispose log must be 1. Disposed Child Container.");

            Container.Dispose();

            Assert.AreEqual(2, logger.Construtor, "Construtor log must be 2. Disposed Root Container.");
            Assert.AreEqual(2, logger.Dispose, "Dispose log must be 2. Disposed Root Container.");
        }
    }

    #region logger

    public class ChildContainerDisposeLogger
    {
        public int Construtor { get; private set; }

        public int Dispose { get; private set; }

        public void ConstrutorCalled()
        {
            Construtor++;
        }

        public void DisposeCalled()
        {
            Dispose++;
        }

        public void Clear()
        {
            Construtor = 0;
            Dispose = 0;
        }
    }

    #endregion

    #region IChildContainerDisposeService

    public interface IChildContainerDisposeService { }
    public class ChildContainerDisposeService : IChildContainerDisposeService, IDisposable
    {
        private ChildContainerDisposeLogger _logger;

        public ChildContainerDisposeService(ChildContainerDisposeLogger logger)
        {
            _logger = logger;
            _logger.ConstrutorCalled();
        }

        public void Dispose()
        {
            _logger.DisposeCalled();
        }
    }

    #endregion

}

**Comment by ENikS** [comment]
When you register types like this:
```
container.RegisterType<IChildContainerDisposeService, ChildContainerDisposeService>(new HierarchicalLifetimeManager());
container.RegisterType<ChildContainerDisposeService>(new HierarchicalLifetimeManager());
```
You create two distinct registrations which handled separately. Read [this article](https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-v5.2.1) for more info.

To fix your issue register it like this:
```
container.RegisterType<IChildContainerDisposeService, ChildContainerDisposeService>();
container.RegisterType<ChildContainerDisposeService>(new HierarchicalLifetimeManager());
```
