### ISSUE TITLE
Unity.Interception support for UWP

### ISSUE THREAD

**Issue by mjsabin01** [unitycontainer/unity#22]
Are there any plans to add support for the Unity.Interception library for UWP apps?  When I add it to my UWP application via NUGet and it fails.

**Comment by bezysoftware** [comment]
As far as I know this isn't possible due to missing API - namely missing Reflection.Emit(). IMHO the only way to support interception would be to make it compile time - I'm thinking some xml configuration and T4.

**Comment by Michael-DST** [comment]
FWIW, there is also PostSharp.  If you run an open source project you get a free professional license: https://www.postsharp.net/

**Comment by ENikS** [comment]
@Mike-EEE 
Could you explain how post sharp could help running interception in UWP?
