### ISSUE TITLE
How to build from sources locally?

### ISSUE THREAD

**Issue by mykolav** [unitycontainer/unity#220]
Hi,

Could you please give a hint on building from the sources locally?

What I tried:
- Cloned `abstractions` and `container` into `c:\...\src\unity\abstractions` and `c:\...\src\unity\container` respectively.
- Built `abstractions`. Build succeeded.
- Building `container` fails.

I'm using VS Community 2017 Ver. 15.6.6
Here are the errors that VS reports (abbreviated for clarity):
```
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Rebuild All started: Project: Unity.Container, Configuration: Debug Any CPU ------
1>c:\...\src\unity\container\src\Unity.Container.csproj : error NU1105: Unable to find project information for 'c:\...\src\unity\Abstractions\src\Unity.Abstractions.csproj'. The project file may be invalid or missing targets required for restore.
1>c:\...\src\unity\container\src\Unity.Container.csproj : error NU1105: Unable to find project information for 'c:\...\src\unity\Abstractions\src\Unity.Abstractions.csproj'. The project file may be invalid or missing targets required for restore.
1>Done building project "Unity.Container.csproj" -- FAILED.

...

2>------ Rebuild All started: Project: Unity.Tests, Configuration: Debug Any CPU ------
2>c:\...\src\unity\container\tests\Unity.Tests\Unity.Tests.csproj : error NU1105: Unable to find project information for 'c:\...\src\unity\Abstractions\src\Unity.Abstractions.csproj'. The project file may be invalid or missing targets required for restore.
2>ChildContainer\ChildContainerInterfaceChangeFixture.cs(7,13,7,21): error CS0234: The type or namespace name 'Lifetime' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
2>CollectionSupport\CollectionSupportFixture.cs(5,13,5,21): error CS0234: The type or namespace name 'Lifetime' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
2>CollectionSupport\ConfigurationTestClass.cs(4,13,4,23): error CS0234: The type or namespace name 'Attributes' does not exist in the namespace 'Unity' (are you missing an assembly reference?)

[About 500 more similar errors]

```

Is there a way to get `container` to build?
Maybe I'm missing something obvious.

Thank you!
Mykola.

**Comment by mykolav** [comment]
It looks like this [Core projects fail to build when they reference other projects not included to solution](https://github.com/dotnet/project-system/issues/2759) may be relevant.

**Comment by ENikS** [comment]
- You need to clone [Unity v5](https://github.com/unitycontainer/unity/tree/v5.x)
- Update sub modules 
- Build

**Comment by mykolav** [comment]
The solution builds successfully now.
Thank you.

Do you think it would make sense to expand master's readme a little:
- At the top of v5.x section add a note along the lines of

> To build v5.x locally please follow these steps:
> `git clone https://github.com/unitycontainer/unity.git`
> `git checkout v5.x && git submodule update --init --recursive`
> open `package.sln` in Visual Studio and build.

- And at the top of v6.x section

> To build v6.x locally please follow these steps:
> `git clone https://github.com/unitycontainer/unity.git`
> `git checkout v6.x && git submodule update --init --recursive`
> open `package.sln` in Visual Studio and build.

I can create a pull request.

**Comment by ENikS** [comment]
Sure, please do.

**Comment by mykolav** [comment]
Hi @ENikS 
Here is the PR -- https://github.com/unitycontainer/unity/pull/221
