### ISSUE TITLE
Setting an ILifeTimePolicy on the PersistentPolices of a, IBuilderContext in a BuilderStrategy no longer works

### ISSUE THREAD

**Issue by mlaily** [unitycontainer/unity#227]
Hi,

I'm trying to update my code from Unity 4.x to the latest 5.8.6.

It looks like I've got everything working, except a custom `UnityContainerExtension` that adds a custom `BuilderStrategy` whose job is to return fake instances of injected dependencies in the unit tests.

(This is a slightly modified version of [this](https://www.thomaslevesque.com/2015/06/14/create-an-auto-mocking-container-with-unity-and-fakeiteasy/))

The part of interest is the overridden `PreBuildUp` method of the custom `BuilderStrategy`:
```csharp
public override void PreBuildUp(IBuilderContext context)
{
    if (context.Existing == null)
    {
        var type = context.BuildKey.Type;
        if (type.IsInterface || type.IsAbstract)
        {
            var fake = CreateFake(type);
            // EDIT: my original question included the following commented line, but I made a mistake. The working code in 4.0.1 used the subsequent line, with PersistentPolicies instead of just Policies. Sorry.
            // context.Policies.Set(context.BuildKey.Type, context.BuildKey.Name, typeof(ILifetimePolicy), new ContainerControlledLifetimeManager());
            context.PersistentPolicies.Set<ILifetimePolicy>(new ContainerControlledLifetimeManager(), context.BuildKey);
            context.Existing = fake;
            context.BuildComplete = true;
        }
    }
    base.PreBuildUp(context);
}
```

The line `context.PersistentPolicies.Set<ILifetimePolicy>(new ContainerControlledLifetimeManager(), context.BuildKey);` does not seem to work anymore: each time a dependency is resolved, the `PreBuildUp` method is called, even if the same interface was already resolved.

With Unity 4.x, this was not the case. All resolved dependencies where effectively singletons, and the `PreBuildUp` method was called once per resolved type.

**Is this the expected behavior with the current version of Unity?**

**What would be the correct way to do what I want?** (That is, resolve all the dependencies going through this strategy as singletons)

Thanks.

**Comment by mlaily** [comment]
Actually the problem is more serious than I initially thought: `PreBuildUp` is called with `context.Existing` set to `false` even when my container actually has a manually registered dependency.

I don't know how to return a fake instance of my dependency only when a manually registered dependency is not present.

What is the correct way to deal with that situation for the current version of Unity?

**Comment by ENikS** [comment]
I been thinking about creating a package for testing that generates and creates mock objects. It looks like you bit me to it.

See if [this](https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-5.8.x) might answer some of your questions.

**Comment by mlaily** [comment]
> See if this might answer some of your questions.

Thanks, I will look into the example. (I can't edit the wiki. May I suggest you change the links to them at the bottom of the page so that the displayed text actually reflects the link target? This is currently not the case)

> Unity changed how it registers types and singletons.

I don't know much about the internals of Unity, so I'm not sure how I'm supposed to use this information.

**Comment by ENikS** [comment]
To fix your code replace line:
```
context.PersistentPolicies.Set<ILifetimePolicy>(new ContainerControlledLifetimeManager(), context.BuildKey);
```
with this one:
```
context.Container.RegisterInstance(...)
```

**Comment by mlaily** [comment]
Ok thanks, this part is working now, my fakes are singletons as desired.

`PreBuildUp` is still called for manually registered dependencies though.

I added the following check to take care of that:
```csharp
if (context.OriginalBuildKey is ContainerRegistration)
{
	base.PreBuildUp(context);
	return;
}
```
Is this the proper way to do this?

I have another problem. All but one of my unit tests pass. The failing test fails with the following exception when calling `BuildUp` on my test class:
```
Exception thrown: 'Unity.Exceptions.ResolutionFailedException' in Unity.Container.dll
Resolution of the dependency failed, type = 'X.ViewModel.Tests.MainWindowViewModelTests', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - Value of ContainerControlledLifetimeManager can only be set once
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving X.ViewModel.Tests.MainWindowViewModelTests,(none)
  Resolving value for property MainWindowViewModelTests.MainWindowViewModel
    Resolving X.ViewModel.MainWindowViewModel,(none)
    Resolving value for property MainWindowViewModel.Settings
      Resolving X.ViewModel.Settings.SettingsViewModel,(none)
      Resolving value for property SettingsViewModel.SharingSettings
        Resolving X.ViewModel.Settings.SharingSettingsViewModel,(none)
        Resolving value for property SharingSettingsViewModel.RemoteBrowser
          Resolving X.Mvvm.IFolderPicker`1[X.Core.Business.ItemInfo],(none)
```

I don't see anything special about this type, and nothing has changed in the code beside my `BuilderStrategy` and going from Unity 4.0.1 to Unity 5.8.6.

Any idea on what could cause that? :/

**Comment by mlaily** [comment]
I figured that much, but I don't understand how this is possible, especially just for this type.

Anyway, I have a dirty workaround, and you answered my initial question. I will close this issue.
