### ISSUE TITLE
RegisterType should not need InjectionMembers for facultative arguments

### ISSUE THREAD

**Issue by dc-p8** [unitycontainer/unity#230]
given a ProductRepository that implements the IProductRepository interface.
Ths ProductRepository have one facultative arguments with a default value.

```
public class ProctRepository{
  public ProductRepository(string base_name="production.sqlite"){
    ...
  }
  ...
}
```

it would be natural to use RegisterType the basic way : 
`container.RegisterType<IProductRepository, ProductRepository>();`

> "ExceptionMessage": "The type String cannot be constructed. You must configure the container to supply this value.",ç

Instead, we need to use a **InjectionConstructor** for RegisterType which I think could be avoided
In addiction, if the default string change in the constructor of ProductRepository, we also need to change it's value in RegisterType.

`container.RegisterType<IProductRepository, ProductRepository>(new InjectionConstructor("production.sqlite"));`

**Comment by ENikS** [comment]
At present Unity does not know how to handle default values, but I like your idea. 
I will try to implement this feature in v6.

**Comment by ENikS** [comment]
@dc-p8 Moved to [unity/abstractions#65](https://github.com/unitycontainer/abstractions/issues/65)
