### ISSUE TITLE
Unexpceted exception when resolving more than once

### ISSUE THREAD

**Issue by hanabi1224** [unitycontainer/unity#231]
Here is a repro, the exception says 'InvalidOperationException - Value of ContainerControlledLifetimeManager can only be set once',  is it bug or expected? And what is the correct usage
```
[TestMethod]
        public void ResolveFactory_ShowNotThrowOnResolve()
        {
            IUnityContainer container = new UnityContainer();
            container.RegisterType<object>("key", new ContainerControlledLifetimeManager(), new InjectionFactory(c => null));
            container.Resolve<object>("key");
            container.Resolve<object>("key");
        }
```

**Comment by hanabi1224** [comment]
This works in at least 5.5.5

**Comment by ENikS** [comment]
Your injection factory returns null ``... new InjectionFactory(c => null)``.
Value ``null`` is not a valid object. Next time you try to resolve it, container calls your factory again and attempts to set it on the lifetime container second time via SetValue. But since it is already initialized with ``null`` in first resolve it throws.

To fix your test do this instead:
```
[TestMethod]
public void ResolveFactory_ShowNotThrowOnResolve()
{
    IUnityContainer container = new UnityContainer();
    container.RegisterType<object>("key", new ContainerControlledLifetimeManager(), new InjectionFactory(c => new object()));
    container.Resolve<object>("key");
    container.Resolve<object>("key");
}
```

**Comment by hanabi1224** [comment]
@ENikS  I would argue this is a regression,  it is a valid scenario that a factory will conditionally return null,  and the case worked for previous versions.   If you insist this is by design, I would say Unity does not have consistent and valid design and will have to move away from it

**Comment by ENikS** [comment]
Typically situation when lifetime manager is set twice indicative of abnormal condition and requires attention, hence the exception. 

If you insist on ``null`` being valid object just copy lifetime manager from [here](https://github.com/unitycontainer/abstractions/blob/90b624a3348f2f0b4896b9f06cf004136987c89b/src/Lifetime/ContainerControlledLifetimeManager.cs), rename it and use away...
