### ISSUE TITLE
ServiceLocator registertion with container

### ISSUE THREAD

**Issue by NarinderMittal** [unitycontainer/unity#234]
We are trying to do somthing like starting with below
UnityContainer container = new UnityContainer();
            UnityServiceLocator locator = new UnityServiceLocator(container);
            container.RegisterInstance<IServiceLocator>(locator, new ContainerControlledLifetimeManager());

then we register our interfaces and in between by mistake we issue the below statement again
 container.RegisterInstance<IServiceLocator>(locator, new ContainerControlledLifetimeManager());

This just clears container Registrations. Any idea why...this code was working before we upgraded from Microsoft.Practices.ServiceLocation

**Comment by ENikS** [comment]
When you re register ``UnityServiceLocator`` old instance, when being disposed, also disposes container it references and wipes out all previous registrations.
Old version of Unity did not dispose overwritten registrations, the new Unity does ([See the code](https://github.com/unitycontainer/container/blob/7df8bdb55590c5ea1db35b6d9ce5f9c62e247eb9/src/UnityContainer.Registration.cs#L58-L65)).

**Comment by NarinderMittal** [comment]
Thanks for confirmation that previous version didn't have this code.
