### ISSUE TITLE
A way to use unity.configuration in asp.net core

### ISSUE THREAD

**Issue by luizfbicalho** [unitycontainer/unity#240]
I'm having problems to use unity.configuration in asp.net core.

Are there plans to convert the unity.config to the json format?
Anyone have an example os aspnet core application with unity.configuration working?

**Comment by luizfbicalho** [comment]
Thanks, 

And the old format, as unity.config? does it work? do you have an example of it?

**Comment by ENikS** [comment]
It should work in Core 2.0+

**Comment by luizfbicalho** [comment]
[TestAspnetCore1.zip](https://github.com/unitycontainer/unity/files/2310435/TestAspnetCore1.zip)
I Made this example and didn't make it work, it should work but it's not clear why it doens't.

**Comment by ENikS** [comment]
What is the error?

**Comment by luizfbicalho** [comment]
The line `var unitySection = (UnityConfigurationSection)ConfigurationManager.GetSection("unity");` returns null

**Comment by ENikS** [comment]
There are no Unity code in this line. Did you add <unity> section to app.config? 
I would suggest to learn how to use ConfigurationManager on MSDN site.

**Comment by luizfbicalho** [comment]
That's the problem that I'm trying to solve, this code works in asp.net and doesn't work in aspnet core, this line is the one that I use to get the configuration from web.config, the web.config has the unity part copied from a project that is working.

If someone has one aspnet core project that loads the unity.config and can send me the project startup i would be very grateful.

**Comment by ENikS** [comment]
This is not the Unity issue. You might want to ask this question at Microsoft ASP Core repo. I do not know how to fix it.

**Comment by luizfbicalho** [comment]
The problem was solved in this post

https://stackoverflow.com/questions/51971934/aspnet-core-web-config-not-loading

**Comment by RiteshKo** [comment]
Any development to support unity config in JSON format?

**Comment by ENikS** [comment]
It is in the plan, but no eta.
