### ISSUE TITLE
Updating from 5.8.6 > 5.8.9 getting "Inheritance security rules violated while overriding member"

### ISSUE THREAD

**Issue by harisuru** [unitycontainer/unity#244]
### Description

I have updated the Unity library from 5.8.6 version to 5.8.9 version i am getting the following exception.

System.TypeLoadException
  HResult=0x80131522
  Message=Inheritance security rules violated while overriding member: 'Unity.RegistrationByConvention.Exceptions.DuplicateTypeMappingException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
  Source=Unity.RegistrationByConvention
  StackTrace:
   at Unity.RegistrationByConvention.RegistrationByConventionExtensions.RegisterTypes(IUnityContainer unityContainer, IEnumerable`1 types, Func`2 getFromTypes, Func`2 getName, Func`2 getLifetimeManager, Func`2 getInjectionMembers, Boolean overwriteExistingMappings)

```C#

public class ConvensionBasedResolverRegistration
    {
        public void Init(UnityContainer pUnityContainer)
        {
            var resolverAssemblies = ConfigurationManager.AppSettings["shared:ioc:convensionAssmblies"];
            var appAssembly = AppDomain.CurrentDomain.GetAssemblies().Where(pX =>
                resolverAssemblies.Split(';').Contains(pX.FullName.Split(',')[0]));

            var types = appAssembly.SelectMany(a => a.GetExportedTypes()).Where(pX => !pX.IsInterface).ToArray();
            pUnityContainer.RegisterTypes(
                types,
                WithMappings.FromMatchingInterface,
                WithName.Default,
                WithLifetime.Hierarchical);
        }
    }

**Comment by ENikS** [comment]
Duplicate [#8](https://github.com/unitycontainer/registration-by-convention/issues/8)
