### ISSUE TITLE
XML configuration file for Unity - where is the documentation?

### ISSUE THREAD

**Issue by sdg002** [unitycontainer/unity#246]
**Is your feature request related to a problem? Please describe.**
Not a feature request. Not a bug. Just seeking some assistance

**Describe the solution you'd like**
Is there a MSDN like site where I can find the detailed documentation of the XML specification used for configuring Unity. I would like to configure my container using a XML file.

**Describe alternatives you've considered**
This used to be available in earlier versions. But, I can't find the link any more.

**Comment by ENikS** [comment]
Links to all kinds of old documentation could be found in [this thread](https://github.com/unitycontainer/unity/issues/117).

**Comment by sdg002** [comment]
Thank you
________________________________
