### ISSUE TITLE
Is Unity still Alive?

### ISSUE THREAD

**Issue by sravansurabhi** [unitycontainer/unity#250]
We are heavily using Spring.NET today and thinking of replacing it  with a different DI tool as Spring.NET seems to be dead.  our first preference was Unity but looks like Microsoft is not supporting this any more . I see very little activity on this and we don't want end up in a situation which we are in now with Spring.NET.
Appreciate any feedback.

**Comment by ENikS** [comment]
Microsoft stopped working on Unity in 2014. Since then it is community supported.
Unity repository has been split into [all these](https://github.com/unitycontainer) repositories and all development is done in individual projects.

It is being actively supported and developed. Hope that helps.

**Comment by sravansurabhi** [comment]
Thank you ENikS for quick response. Appreciate your help. This definitely helps.
