### ISSUE TITLE
Declaring type's with nested generics by shorthand format in configuration

### ISSUE THREAD

**Issue by atagirov** [unitycontainer/unity#26]
When declaring type's with nested generics in shorthand format, nested generics arguments is ignored.

For example:

```
<register type="IEventBus[IEvent[long], long]" mapTo="EmptyEventBus[IEvent[long], long]" />
```

first argument IEvent[long] resolved as IEvent`1 instead IEvent[long], because arguments for nested generics is ignored.

Currently, problem resolved by using aliases with .NET type format for arguments:

```
<alias alias="IEventLong" type="Namespace.IEvent`1[System.Int64], Assembly" />
...
<register type="IEventBus[IEventLong, long]" mapTo="ConsoleEventBus[IEventLong, long]" />
```

But using "IEventBus[IEvent[long], long]" is more friendly and logical. Also, using alises is hard, when we must declare generics more than second level.

I create a pull-request, they can resolve this, without using aliases - https://github.com/unitycontainer/unity/pull/25

**Comment by ENikS** [comment]
Not sure what needs to be done here. Closing for now...

**Comment by ENikS** [comment]
Moved to unitycontainer/configuration#1
