### ISSUE TITLE
error container.RegisterType<DbContext, StoreContext>(new PerRequestLifetimeManager(), null); 

### ISSUE THREAD

**Issue by neozhu** [unitycontainer/unity#266]
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Unity.AspNet.Mvc.PerRequestLifetimeManager' to 'Unity.Injection.InjectionMember'	WebApp	D:\tfsonline\opensource\SmartCode-Engine\CustomBasicScaffolder\Demo\WebApp\App_Start\Mvc.UnityConfig.cs	78	N/A

### To Reproduce

```C#
container.RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerRequestLifetimeManager(), null);
container.RegisterType<DbContext, StoreContext>(new PerRequestLifetimeManager(), null);
```

**Additional context**

ver 5.9

**Comment by ENikS** [comment]
Duplicate [unitycontainer/aspnet-mvc#10](https://github.com/unitycontainer/aspnet-mvc/issues/10)
