### ISSUE TITLE
Unable load configuration from web.config

### ISSUE THREAD

**Issue by quintonn** [unitycontainer/unity#267]
Previously i was able to setup my configuration by reading the **unity**  section of the web.config file by calling this: **Container.LoadConfiguration();**
But after upgrading unity to 5.9.0 from 5.5.0, it does not work because the namespace Microsoft.Practices.Unity.Configuration; is no longer available.

Do I have to include a different package or something maybe to get this feature back?

**Comment by ENikS** [comment]
`Microsoft.Practices.Unity.Configuration` has been changed to `Unity.Configuration`. You need to refactor your code accordingly.

**Comment by quintonn** [comment]
Hi, 
I figure out I had to add a **new** nuget package.
So it wasn't just an easy refactor. It wasn't easy to figure out the new package i had to use. I had to do a bit of guess work.

**Comment by ENikS** [comment]
Would you like to do a PR and add some documentation to make it easier for others?

**Comment by quintonn** [comment]
I can do that.
In which repo is the documentation? Same one?

**Comment by ENikS** [comment]
It would be appreciated

https://github.com/unitycontainer/unity/wiki
This is the [issue](https://github.com/unitycontainer/unity/issues/241)

**Comment by quintonn** [comment]
How do I make changes to the wiki for a PR?

**Comment by ENikS** [comment]
I am not that familiar with it either, documentation is not my strongest skill. 
Perhaps post it here, I'll update wiki?

**Comment by quintonn** [comment]
I wanted to add a new section on your wiki : **Upgrading to Release 5.9.x**
And there I would mention the Issue you pointed out and that to be able to use **Container.LoadConfiguration()** which loads from app or web.config files, one needs to include Unity.Configuration nuget package. 
But likely there might be other extension methods like this also moved to separate nuget packages?
This was the only issue I had when upgrading from 5.5.0 to 5.9.0

**Comment by quintonn** [comment]
Basically the namespace Microsoft.Practices.Unity.Configuration has moved to Unity.Configuration

**Comment by ENikS** [comment]
Yes, all of these are correct

**Comment by ENikS** [comment]
Did you try to fork Unity and try adding it to wiki?

**Comment by quintonn** [comment]
I did try to fork it, but it doesn't fork the wiki.

**Comment by ENikS** [comment]
Post it here and I'll cut/paste it

**Comment by quintonn** [comment]
I think this will do it:

# Upgrading to Unity 5.9.x

Starting with version 5.9.0 Unity package will only contain Unity.Abstractions and Unity.Container packages. 

All other packages will be available as individual NuGet packages

## Breaking change

Some extension methods have been moved out of the Unity nuget package and have been moved into their own individual packages.

For example, the following code will no longer work
```C#
Container = new UnityContainer();
Container.LoadConfiguration();
```
You will receive an error that the namespace **Microsoft.Practices.Unity.Configuration** no longer exists in your using statements.

## The Fix

To fix this and similar problems, add the required nuget packages separately.

For the example above, add nuget package **Unity.Configuration**

**Comment by ENikS** [comment]
https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-5.9.x


For feature references: https://labs.inn.org/2014/05/19/applying-git-to-github-wikis/
