### ISSUE TITLE
Unity.Abstractions 4.0.0.0 new PublicKeyToken ???

### ISSUE THREAD

**Issue by MatzeG** [unitycontainer/unity#269]
Hi 

is it correct that the Unity.Abstractions got a new publicKeyToken ???

Thx4Support
Matthias

Unity.Abstractions, Version=3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f
Unity.Abstractions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0

**Comment by ENikS** [comment]
Yes, it has been changed to use the same certificate as the rest of the packages.
