### ISSUE TITLE
Problems with protected properties dependency injection

### ISSUE THREAD

**Issue by Ezkerro** [unitycontainer/unity#272]
I updated from 5.8.11 to 5.9.3 and protected properties dependency injection stop working.

Any suggestions?

**Comment by ENikS** [comment]
It is by design. Supposedly only public members should be injectable.
Later version does much better job at enforcing these rules.

**Comment by demirag** [comment]
Same problem here. @ENikS Could you please explain why it is by design? I have no reasonable explanations on forcing people to use only public properties.

**Comment by ENikS** [comment]
While building pipeline Unity creates this expression:
```C#
var existing = new SomeType
{
  Field1 = "xx",
  Property1 = "yy"
}
```
If fields or properties are protected it will not compile and will not create pipeline. 

Up until last version Unity used reflection to set member values but now it uses expressions which make it faster but initialization of protected members impossible.

**Comment by atomgregg** [comment]
Hi, the reasoning behind the decision (to be faster) whilst sacrificing consumers class design choices doesn't really sit clearly with me. Great, you made it faster, at what cost though?

In our code shop we have design constraints on our classes to ensure these properties are not increasing our surface area. Now we cannot inject these dependencies and are forced to remain with an older (slower) but functional version.

Perhaps you could inspect the access modifier of the property and keep the performance benefits for public modifiers, whilst still retaining support for a reflection approach over protected modifiers?

**Comment by ENikS** [comment]
Gregg,

The constraint is not based on my arbitrary decision. It was implemented because of technical requirement.

Unity 4 used reflection to get setter methods and called them directly to set property values. It worked with all properties. Although in all Unity documentation is said it works only with public properties, the constraint was not strictly enforced.

Unity 5 creates and compiles an expression tree like this:

```C#

var Instance = new SomeType(c.Resolve(x), c.Resolve(y) )

{

    Prop1 = c.Resolve(z)

}

```

Non accessible properties and fields would not compile. So, this is why the limitation has been enforced.

**Comment by jmussman** [comment]
Having stumbled across this I have to agree with Gregg. It is unfortunate that you didn't read his post more carefully. It's great you found a new faster way to implement injection, but in many applications the field receiving the injected value actually needs to be private. So I would say you found a nifty new hammer, but not every problem is your kind of nail.

**Comment by ENikS** [comment]
The beautiful thing about Unity is that you have a choice. Use whatever works for you and override whatever doesn’t.

The source is available for both implementations. You could even contribute an extension if you think it is that valuable

**Comment by atomgregg** [comment]
Can you please share how one would produce such an extension. Should this be the correct/only way forwards then I will take a closer look.

**Comment by ENikS** [comment]
Yes, this is the only way.

I am working on a manual for creating extensions and etc. I will post a link when it is available.
