### ISSUE TITLE
Multiple-Constructor Injection using Unity IOC : Behavior has changed

### ISSUE THREAD

**Issue by Speedplay** [unitycontainer/unity#275]
I updated to version 5.9.3 from 5.3.1 and the behavior is not the same when I inject a class with multiple constructors. The previous behavior was the use of the constructor with the most parameters. Now, by default, it use the constructor with the less parameters.

Is it the new expected behavior?

If I use this attribute [InjectionConstructor], I can force Unity to use a specific constructor but if I'll have to do that, it will be a lot of work for me.

Regards,

Marco

**Comment by ENikS** [comment]
@Speedplay 
Unity uses 'smart' algorithm where it selects longest constructor it could satisfy with dependencies. As you correctly stated, you could mark constructors with attribute and it will guarantee proper selection. 

The [legacy algorithm](https://github.com/unitycontainer/container/blob/86d419737750e3d9557af3534645bb86349e4e8e/src/Processors/Constructor/ConstructorProcessor.cs#L104-L129) is still available but you would have to create extension to install it as default.

**Comment by MatzeG** [comment]
Hi 

can you provide me with a small sample to change the ConstructorProcessor in a Extension to the legacy algorithm or give me a hint to the documentation. I know how to write and use an extension but didn´t know how to change it. I think I must change SelectMethod = SmartSelector; to SelectMethod = LegacySelector. A little help would be perfect.

Thx Matthias

**Comment by ENikS** [comment]
I will try to add this extension in next release. If you think of other legacy items to include please let me know.

**Comment by ENikS** [comment]
Added extension ``Legacy``. To use legacy selection algorithm just add the extension to container:
```C#
var container = new UnityContainer();
container.AddExtension(new Legacy());
```

**Comment by MatzeG** [comment]
Thx ENikS
