### ISSUE TITLE
Legacy InjectionParameterValue

### ISSUE THREAD

**Issue by xcap2000** [unitycontainer/unity#278]
### Description

InjectionParameterValue do not exist anymore. I have some legacy code that uses this class in order to allow resolving contructor arguments generically by order based on the following article:

https://mikaelkoskinen.net/post/unity-passing-constructor-parameters-to-resolve

I would like an alternative way of doing that on current version (5.x).

### To Reproduce

Try using InjectionParameterValue.

**Comment by ENikS** [comment]
It was renamed to [ParameterValue](https://github.com/unitycontainer/abstractions/blob/master/src/Dependency/Injection/Abstracts/ParameterValue.cs)

**Comment by xcap2000** [comment]
@ENikS Thank you for the fast reply. I will take a look and try to adapt the code using this new classes.

**Comment by xcap2000** [comment]
@ENikS I upgraded my code with your help and it worked like a charm. Thank you!

**Comment by ershad65** [comment]
@xcap2000 @ENikS do you guys have a solution on how you modified orderred parameters override?

**Comment by xcap2000** [comment]
@ershad65 take a look at the following gist and tell me whether it helped you:

https://gist.github.com/xcap2000/2d264960cae55cf131edaa907a1a3eae

**Comment by ershad65** [comment]
Thanks @xcap2000. That helps

**Comment by xcap2000** [comment]
@ershad65 you are welcome!
