### ISSUE TITLE
Document Unity Release versioning strategy

### ISSUE THREAD

**Issue by danrien** [unitycontainer/unity#279]
**Is your feature request related to a problem? Please describe.**

Unity releases with minor version bumps introduce breaking changes. Many libraries use a wildcard when including a dependency (i.e `<PackageReference Include="Unity.Container" Version="[5.8.6, 6.0.0)" />`), so that consumers of the library are free to upgrade Unity without needing a new version of *their* library. In short, introducing breaking changes on a minor version bump breaks dependent libraries (see [here](https://github.com/Particular/NServiceBus.Unity/issues/100)).

**Describe the solution you'd like**

Document versioning strategy, so consumers can properly configure wildcards when relying on this library.

**Describe alternatives you've considered**

Switch to [Semantic Versioning](https://semver.org/), the de facto industry standard for versioning, and release breaking changes with a major version bump.

**Comment by ENikS** [comment]
Unity API is controlled by Unity.Abstractions assembly. The version was increased from 3.3.0 to 4.0.0.

**Comment by danrien** [comment]
@ENikS understood, however, this update to `Unity.Abstractions` `4.0.0` does introduce a breaking change on the 5.* series of Unity assemblies, which is not documented in the new version number. It's fine to have a versioning strategy different from SemVer (which would state in this case that the library dependent on `Unity.Abstractions` should receive a version bump), however, is there documentation that could be added if that's the case?

**Comment by danrien** [comment]
@ENikS I just saw your comment - thanks! Let me know if there's anything I could do to help.

**Comment by ENikS** [comment]
SemVer does not guarantee API stability between minor version changes. Transitioning from v5.8 to v5.9 is one of these.

What kind of help do you have in mind, I have a lot of things I need help with :)

**Comment by ENikS** [comment]
As for including Unity this should be much safer:
```
<PackageReference Include="Unity.Container" Version="5.9.*" />
```

**Comment by danrien** [comment]
SemVer does state that minor version changes should only include backwards compatible changes:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

https://semver.org/#spec-item-7

Again, it's fine if SemVer isn't followed, but if not, then the version strategy employed should be stated. Thanks for the tip on the proper reference to use.

**Comment by danrien** [comment]
And I can help with documenting the versioning strategy used by Unity, or I can hack at some code when I have time.

**Comment by ENikS** [comment]
Any help would be appreciated. 

Documentation is one of these areas where I am not at my strongest. English being my third language does not help either. If you feel you could lend a hand with documenting new stuff I am sure there will be a lot of grateful developers.

**Comment by danrien** [comment]
Sounds good - I will open a PR where appropriate to document versioning for v5 (judging by your comments in the linked issue, v6 will follow SemVer more closely?).
