### ISSUE TITLE
Field not found: object Unity.Lifetime.LifetimeManager.NoValue

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [unitycontainer/unity#289]
### Description

This code if from a Xamarin Forms application. The container is not able to resolve applicationContextService. 

Exception - 

Unhandled Exception:

Unity.ResolutionFailedException: Field not found: object Unity.Lifetime.LifetimeManager.NoValue Due to: Could not find field in class

Exception occurred while:

•resolving type: 'IApplicationContextService' mapped to 'ApplicationContextService'

### To Reproduce

```C#
var unityContainer = new UnityContainer();
unityContainer.AddExtension(new Diagnostic());
ServiceLocator.SetLocatorProvider(() => new UnityServiceLocator(unityContainer));

unityContainer.RegisterType<IApplicationContextService, ApplicationContextService>(new ContainerControlledLifetimeManager());

var applicationContextService = unityContainer.Resolve<IApplicationContextService>();

```

**Additional context**

Below is the version with which it's giving the exception
Unity Version="5.10.3"
Unity.ServiceLocation Version="5.10.0"

When I downgrade the Unity Version to ="5.10.0", it's working.

**Comment by ENikS** [comment]
Did you upgrade Unity.Abstractions as well?

**Comment by sawankumarbundelkhandi** [comment]
No, I have not updated the Abstraction. Actually, I have installed from here -https://www.nuget.org/packages/Unity/

And in nuget packages manager, it's not showing Unity.Abstractions as a standalone nuget.

**Comment by ENikS** [comment]
I would need a Unit Test to replicate this issue

**Comment by ENikS** [comment]
I am guessing it is no longer relovant. Closing this for now. Feel free to reopen if you decide to add unit tests

**Comment by tytusse** [comment]
I also had this issue. What helped was to uninstall "Unity" nuget package and use "Unity.Container" instead. I am guessing, that "Unity" package bundles older "Unity.Abstractions.dll" version, while "Unity.Container" uses nuget dependency mechanism to reference this lib and gets proper version. Hope it helps.
