### ISSUE TITLE
ASP.NET 5 MVC 6 

### ISSUE THREAD

**Issue by damienbod** [unitycontainer/unity#29]
Have you any plans for MVC 6? 

Greetings Damien

**Comment by pcibraro** [comment]
We are working on it. It should be available soon this month. Thanks

**Comment by damienbod** [comment]
thanks
Greetings Damien

**Comment by reader-man** [comment]
This means that it will support Xamarin by design, is that true?

Regards.

**Comment by pcibraro** [comment]
Xamarin should be supported with the current implementation of the Portable Library, have you tried that one ? Thanks

**Comment by reader-man** [comment]
No, but i need too, thanks a lot.
