### ISSUE TITLE
Introduce changelog wiki page

### ISSUE THREAD

**Issue by GSPP** [unitycontainer/unity#290]
The patch attached introduces a new changelog wiki page. The existing upgrade pages have been merged into this one. Also, my personal experience from upgrading and the content from https://github.com/unitycontainer/abstractions/issues/97.

[0001-Introduce-changelog-wiki-page.zip](https://github.com/unitycontainer/unity/files/3077181/0001-Introduce-changelog-wiki-page.zip)

**Comment by ENikS** [comment]
[Patched up](https://github.com/unitycontainer/unity/wiki/Upgrading-Unity-Container-to-the-latest-(Changelog))

Thank you for your help

**Comment by ENikS** [comment]
Could you create a PR and add your page to this [dir](https://github.com/unitycontainer/documentation/tree/master/articles) as well?
