### ISSUE TITLE
Operation could destabilize the runtime and PEVerify errors

### ISSUE THREAD

**Issue by ggingras** [unitycontainer/unity#296]
Hi, 

Since version 5.9.X some changes to the Unity codebase trigger a System.Security.VerificationException: Operation could destabilize the runtime.

This prevents me from profiling my application using Red-Gate Performance Profiler. 

Here are the PEVerify reports for 3 releases : 

- 5.8.11 (The only one verified successfully)
- 5.9.8
- 5.10.2

Are you aware of this problem? Do you know a way to fix it ?

Regards

Gaetan

```
Unity.Container 5.8.11
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

All Classes and Methods in Unity.Container.dll Verified.
```

```
Unity.Container 5.9.8
[IL]: Error: [...\Unity.Container.dll : Unity.UnityContainer::<ContextValidatingPlan>g__GetPerResolveValue|108_0][offset 0x00000016] Unable to resolve token.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000040][found address of Int32] Expected numeric type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000036][found Native Int][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000042] Unmanaged pointers are not a verifiable type.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000040][found address of Int32] Expected numeric type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000036][found Native Int][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000042] Unmanaged pointers are not a verifiable type.
[IL]: Error: [...\Unity.Container.dll : Unity.Builder.BuilderContext::Resolve][offset 0x00000086] Unable to resolve token.
8 Error(s) Verifying Unity.Container.dll
```

```
Unity.Container 5.10.2
[IL]: Error: [...\Unity.Container.dll : Unity.UnityContainer::ContextValidatingResolvePlan][offset 0x0000001E][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.UnityContainer::ContextValidatingResolvePlan][offset 0x00000118][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.UnityContainer::<ContextValidatingExecutePlan>g__GetPerResolveValue|106_0][offset 0x00000016][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000040][found address of Int32] Expected numeric type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000036][found Native Int][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.HashRegistry::.ctor][offset 0x00000042] Unmanaged pointers are not a verifiable type.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000040][found address of Int32] Expected numeric type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000036][found Native Int][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [...\Unity.Container.dll : Unity.Storage.Registrations::.ctor][offset 0x00000042] Unmanaged pointers are not a verifiable type.
[IL]: Error: [...\Unity.Container.dll : Unity.Builder.BuilderContext::Resolve][offset 0x00000098][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
10 Error(s) Verifying Unity.Container.dll
```

**Comment by ENikS** [comment]
Unity uses `unsafe` blocks for some performance optimizations. If you need to use CLR `safe` version link to .NET40 platform of the Unity.

**Comment by ggingras** [comment]
Thanks for the response. 

Everything works fine in production mode. I only have problems when profiling. Is unsafe code new to version 5.9.X or it was already used in version 5.8.X? 

Regards

**Comment by ENikS** [comment]
It is a relatively new addition.

**Comment by Jeromino** [comment]
I also get this NullReferenceException after upgrading to 5.11.1: 

   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|123_0(IntPtr parent, Type registrationType, String name)
   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|123_0(IntPtr parent, Type registrationType, String name)
   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|123_0(IntPtr parent, Type registrationType, String name)
   at Unity.UnityContainer.ContextValidatingExecutePlan(BuilderStrategy[] chain, BuilderContext& context)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration)
   at Unity.UnityContainer.ResolveEnumerable[TElement](Func`4 resolve, Type generic, String name)+MoveNext()
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)

You confirm this was already fixed?

**Comment by ENikS** [comment]
I never seen this one. Can you provide test case so I could debug it

**Comment by Jeromino** [comment]
I am still swamped right now but I will get back to you as soon as I have time to look into the other 2 open issues with Unity.Microsoft.DependencyInjection.

Could you please reopen this issue until I can get back with more information?
