### ISSUE TITLE
Lifetime management of generic interfaces on child containers

### ISSUE THREAD

**Issue by Rfaering** [unitycontainer/unity#298]
### Description
When registering instances to child containers, the behavior of resolving generic services changes

In our code, we expect the behavior of the second test, which also works. 

But we have an external library that registers instances on the child containers, which breaks the behavior. 

https://github.com/unitycontainer/microsoft-dependency-injection

This seems to be a bug

### To Reproduce

Run the two tests below, the first will fail and the second will pass. Note that the only difference is that instances are registered on the child container

I have attached a zip of the project

```C#
[Fact]
        public void TestGenericSingletonWithInstances()
        {
            var container = new UnityContainer();
            container.RegisterSingleton(typeof(IFakeOpenGenericService<>), typeof(FakeOpenGenericService<>));

            var rootContainer = container as IUnityContainer;

            var childContainer1 = rootContainer.CreateChildContainer();
            var childContainer2 = rootContainer.CreateChildContainer();

            childContainer1.RegisterInstance<IFakeService>(new FakeService());
            childContainer2.RegisterInstance<IFakeService>(new FakeService());

            var test1 = childContainer1.Resolve<IFakeOpenGenericService<object>>();
            var test2 = childContainer2.Resolve<IFakeOpenGenericService<object>>();

            Assert.Same(test1, test2);
        }

        [Fact]
        public void TestGenericSingletons()
        {
            var container = new UnityContainer();
            container.RegisterSingleton(typeof(IFakeOpenGenericService<>), typeof(FakeOpenGenericService<>));

            var rootContainer = container as IUnityContainer;

            var childContainer1 = rootContainer.CreateChildContainer();
            var childContainer2 = rootContainer.CreateChildContainer();

            // childContainer1.RegisterInstance<IFakeService>(new FakeService());
            // childContainer2.RegisterInstance<IFakeService>(new FakeService());

            var test1 = childContainer1.Resolve<IFakeOpenGenericService<object>>();
            var test2 = childContainer2.Resolve<IFakeOpenGenericService<object>>();

            Assert.Same(test1, test2);
        }
```

[TestUnity.zip](https://github.com/unitycontainer/unity/files/3220179/TestUnity.zip)

**Comment by Rfaering** [comment]
It seems that doing any kind of registrations on the sub container, causes this issue

**Comment by ENikS** [comment]
This is correct behavior. When instance is registered in child container it overrides registration in paren.
In your case you are registering two distinct instances and getting them back when resolving. Obviously they are not the same when compared.

**Comment by Rfaering** [comment]
@ENikS  - I am not sure I understand your response.

Please be aware that in both my tests I do **not** resolve the registered instance on the child container. I only resolve the registered generic service on the parent container. 

I do not understand how registering something on the child container, should change that behavior of resolving services on the parent container?

**Comment by ENikS** [comment]
It is not true according to the sample you provided:
```C#
var test1 = childContainer1.Resolve<IFakeOpenGenericService<object>>();
var test2 = childContainer2.Resolve<IFakeOpenGenericService<object>>();
```

**Comment by Rfaering** [comment]
@ENikS - Sorry I was not clear

What I meant was, that the type I am resolving has **not** been registered on the child container. The registrations on the child containers, are for a different type. 

In the example, I have registered `IFakeOpenGenericService<>` as a global singleton on the parent container only

The registration on the child containers are not related to this type. 

So when I resolve `IFakeOpenGenericService<>` on any container (child or parent) I would expect to receive the global singleton I have registered

**Comment by ENikS** [comment]
The problem could be related to [this issue](https://github.com/unitycontainer/unity/issues/293)

**Comment by Rfaering** [comment]
@ENikS - Could be, not sure

We have currently upgraded our code from Asp.net, to Asp.net core

In that upgrade we now use https://github.com/unitycontainer/microsoft-dependency-injection and have report https://github.com/unitycontainer/microsoft-dependency-injection/issues/46 due to the fact that the library do registrations on the child containers. 

Because of this bug, we have now broken code, all the places that we use generic registrations on parent containers. What do you suggest that we do ?
