### ISSUE TITLE
[Performance] Creating UnityContainer is slow

### ISSUE THREAD

**Issue by s-bauer** [unitycontainer/unity#299]
# Description

Creating a new UnityContainer (`new UnityContainer()`) takes around 60ms, which is quite slow I think. Is there any way to speed it up? What is the Container doing that is taking so long?

**Comment by ENikS** [comment]
I am guessing here, but probably initializing?

**Comment by s-bauer** [comment]
@ENikS The problem is that I'm unable to cache the Dependency Container instance for a long time, as I'm not in control of the lifetime of my app domain. I'm not familiar with the internals of the UnityContainer and what it is doing to initialize itself. I just wanted to point out that this (long) setup time can be a problem in specific projects and that it would be great if it's possible to decrease this initial setup time.

**Comment by ENikS** [comment]
Do you suspect it is being slowed down on purpose?!

**Comment by s-bauer** [comment]
No, I've never said that... You seem to care about performance as you've done lots of performance measurements and improvements in the 5.X versions of Unity. I'm just saying that resolving and registration  might be the most important performance improvements, but they are not the only ones. Just creating the container without registering or resolving any type shouldn't take that long in my eyes and there is room for improvement.

**Comment by ENikS** [comment]
@s-bauer 
Closing for now. Feel free to reopen or send a PR if you find a way to improve performance.
