### ISSUE TITLE
The release page is not updated

### ISSUE THREAD

**Issue by reader-man** [unitycontainer/unity#30]
Hi,
 the release page is not updated with unity released version.
https://github.com/unitycontainer/unity/releases
with What’s New.
also it will benefit in downloading the .dlls, as nuget download is very slow in my area.

as seen here in EF, release page:
https://github.com/aspnet/EntityFramework/releases

Regards.

**Comment by Leonardo-Ferreira** [comment]
Yes! I agree that the info page could be more complete and engaging, showcasing the work that has been complete (perhaps with a "whats new"/"changelog") and the work that is being developed! A roadmap would be nice, along with expected release dates...

**Comment by arielszklarkiewicz** [comment]
Hi,

We're working to publish a CoreClr-compatible version soon. It will come with the release notes too.

Thanks for the patience.
