### ISSUE TITLE
 A second operation started on this context before a previous asynchronous operation completed...

### ISSUE THREAD

**Issue by raysefo** [unitycontainer/unity#302]
Hi,
I have an asp.net web API. I am using unity 5.11. I am load testing my API and getting this error:
**A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.**

In my service I am using async methods. I wonder if I change this lifetime manager to **ContainerControlledTransientManager** can I get rid of this error?

Here is my Unity configuration:
```
using System;
using BusinessService;
using DataModels;
using Unity;
using Unity.Lifetime;

namespace Game
{
    /// <summary>
    /// Specifies the Unity configuration for the main container.
    /// </summary>
    public static class UnityConfig
    {
        #region Unity Container
        private static Lazy<IUnityContainer> container =
          new Lazy<IUnityContainer>(() =>
          {
              var container = new UnityContainer();
              RegisterTypes(container);
              return container;
          });

        /// <summary>
        /// Configured Unity Container.
        /// </summary>
        public static IUnityContainer Container => container.Value;
        #endregion

        
        public static void RegisterTypes(IUnityContainer container)
        {
            
            container.RegisterType<IGameServices, GameServices>().RegisterType<UnitOfWork>(new HierarchicalLifetimeManager());
            container.RegisterType<IUserValidate, UserValidate>();
            
       }
    }
}
```

Here is my Game Services:
```
public class GameServices : IGameServices
    {
        private readonly UnitOfWork _unitOfWork;

        /// <summary>
        /// Public constructor.
        /// </summary>
        public GameServices(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
...
```

Here is my  UOW:
```
public class UnitOfWork : IDisposable
    {
        private readonly GameContext _context;
        private readonly GenericRepository<GameRequest> gameRequestRepository;
        private readonly GenericRepository<GameResponse> gameResponseRepository;
        private readonly GenericRepository<GameConfirmRequest> gameConfirmRequestRepository;
        private readonly GenericRepository<GameConfirmResponse> gameConfirmResponseRepository;
        private readonly GenericRepository<GameBank> gameBankRepository;
        private readonly GenericRepository<GameBankPin> gameBankPinRepository;
        private readonly GenericRepository<ConfirmCancel> confirmCancelRepository;
        private readonly GenericRepository<Recon> reconRepository;
        private readonly GenericRepository<Company> userRepository;

        public UnitOfWork(GameContext context)
        {
            _context = context;
        }

...
```

**Comment by ENikS** [comment]
I think it would have no effect on the outcome.

**Comment by raysefo** [comment]
So it is not due to Unity lifetime manager settings?

**Comment by ENikS** [comment]
I would

I would doubt that. Unity 5 doesn't have async  capabilities

**Comment by raysefo** [comment]
is there any version that has async capability? Am I the first person trying to accomplish this :)

**Comment by ENikS** [comment]
Version 6 will be async

**Comment by raysefo** [comment]
When I do a load test with 1500 users with 10 sec ramp-up time, I get this error. 

**System.InvalidOperationException: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached. The underlying provider failed on Open.**

I don't manually open connections, I am using Unity as follows:
`container.RegisterType<IGameServices, GameServices>().RegisterType<UnitOfWork>(new TransientLifetimeManager());`

Handle the connection in the unit of work as follows:

`public class UnitOfWork : IDisposable
    {
        private readonly GameContext _context;
     ...//some code here

        public UnitOfWork(GameContext context)
        {
            _context = context;
        }

...//Some code here
        public void Save()
        {
            _context.SaveChanges();
        }

       
        public async Task SaveAsync()
        {
            await _context.SaveChangesAsync();
        }

        private bool disposed = false;

        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    _context.Dispose();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
}`

I wonder if Unity config is correct? Does Unity handles open/close connection?

**Comment by ENikS** [comment]
Unity does not handle connections.

**Comment by raysefo** [comment]
I mean disposal of dbcontext.

**Comment by ENikS** [comment]
The disposal is initiated by the net core code. Unity just follows the orders
