### ISSUE TITLE
RegisterFactory Usage

### ISSUE THREAD

**Issue by jfraschilla** [unitycontainer/unity#305]
In the past, I have used the following RegisterType command to inject a factory

`container.RegisterType<Func<string, ICar>>(new InjectionFactory(
                ctx => new Func<string, ICar>(name => container.Resolve<ICar>(name))));`

Then, using constructor injection I would do

` public ToolboxViewModel(Func<string, ICar> carFactory)
        {
        }`

Using the above, everything works fine.  Now I want to change the above to use the new RegisterFactory command.  So I changed the registration to:

`container.RegisterFactory<Func<string, ICar>>((c, type, name) => c.Resolve<ICar>(name));`

But now, when I run the app I get a ResolutionFailedException (see below).  Am I doing something wrong?

> 'UnityFactory.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview8-28405-07\System.Runtime.CompilerServices.Unsafe.dll'. 
Exception thrown: 'System.InvalidOperationException' in Unity.Container.dll
Exception thrown: 'Unity.ResolutionFailedException' in Unity.Container.dll
Exception thrown: 'Unity.ResolutionFailedException' in Unity.Container.dll
Exception thrown: 'Unity.ResolutionFailedException' in Unity.Container.dll
Exception thrown: 'Unity.ResolutionFailedException' in Unity.Container.dll
Exception thrown: 'Unity.ResolutionFailedException' in Unity.Container.dll
An unhandled exception of type 'Unity.ResolutionFailedException' occurred in Unity.Container.dll
The current type, UnityFactory.ICar, is an interface and cannot be constructed. Are you missing a type mapping?
_____________________________________________________
Exception occurred while:
• while resolving:  ICar
_____________________________________________________
Exception occurred while:
• while resolving:  Func`2
    for parameter:  carFactory
   on constructor:  ToolboxViewModel(Func`2 carFactory)
• while resolving:  ToolboxViewModel

**Comment by jfraschilla** [comment]
`class Program
{
    static void Main(string[] args)
    {
        var container = new UnityContainer();
        container.EnableDebugDiagnostic();

        container.RegisterType<IFoo, Foo1>("Foo1");
        container.RegisterType<IFoo, Foo2>("Foo2");

        container.RegisterType<MainViewModel>();

        // This does not work
        container.RegisterFactory<Func<string, IFoo>>((c, type, name) => c.Resolve<IFoo>(name));

        // This works
        //container.RegisterType<Func<string, IFoo>>(new InjectionFactory(
        //    ctx => new Func<string, IFoo>(name => container.Resolve<IFoo>(name))));


        var vm = container.Resolve<MainViewModel>();
    }
}

public class MainViewModel
{
    public MainViewModel(Func<string, IFoo> fooFactory)
    {
        var foo1 = fooFactory.Invoke("Foo1");
        var foo2 = fooFactory.Invoke("Foo2");
    }
}

public interface IFoo
{
    string Name { get; }
}

public class Foo1 : IFoo
{
    public string Name { get; set; }

    public Foo1()
    {
        Name = "Foo1";
    }
}

public class Foo2 : IFoo
{
    public string Name { get; set; }

    public Foo2()
    {
        Name = "Foo2";
    }
}`

**Comment by ENikS** [comment]
Did you register mapping for ``ICar``?

**Comment by jfraschilla** [comment]
Yes, see the second post I made with more details.  I found that the following registration works
`container.RegisterFactory<Func<string, IFoo>>(c => new Func<string, IFoo>(name => c.Resolve<IFoo>(name)));`
