### ISSUE TITLE
Resolve<List<SomeClass>>() creates a list with 1 item.

### ISSUE THREAD

**Issue by KaeTar** [unitycontainer/unity#314]
In unity as far back as 5.11.1 (does not do this in 5.10.3) UnityContainer.Resolve<>() when performed on a List<SomeType> will return a new List of that type with one item in the list of that type.  

It should return an empty list.  I can not think of any reason anyone would want unity to return a list<type> back with a randomly generated new item of that type in the list.

Here is a .Net Fiddle showing the issue.
[List Create Issue](https://dotnetfiddle.net/e3ERBy)

**Comment by ENikS** [comment]
Unity picks the longest constructor it could satisfy at the time of resolution. One of public List constructors has this signature:
```C#
public List<T>(IEnumerable<T> data)
``` 
So, when Unity initializes the list, it resolves `IEnumerable<T>` and passes enumeration to the list.

**Comment by KaeTar** [comment]
Why is it able to resolve an IEnumerable<T> that is an interface and it is definitely not registered.   Are you saying it is resolving the concrete type of T and then returning that single object as an IEnumerable<T>? (Black magic)    Here is the scenario in which this change completely fubars. (this was a complete train wreck to track down)   We have models that are Deserialized with newtonsoft json on rest endpoint responses.  We have a deserializer setup to use Unity to create objects instead of Activate.  This allows us to inject services into models as needed.  As a result if I have a web api method returning a List<someObject> (or Collection or any other type of list)  it resolves using unity the List first and then it resolves individual items and then adds them to the list.  Whatever changed now I have an extra item in the list no matter what we do.   Any suggestions on how to bandaid our way around this 5.11.x "Feature"?

**Comment by ENikS** [comment]
`IEnumerable<T>` is built in registration, similar to `Array<T>`. It will resolve collection similar to [ResolveAll](https://github.com/unitycontainer/unity/wiki/Difference-between-ResolveAll-and-Enumerable.).

**Comment by KaeTar** [comment]
so in 5.10.3  a resolve on IEnumerable<someClass>  returned an IEnumerable with 0 items in it.  
in the first version of 5.11.x a resolve on the same thing started returning an IEnumerable with 1 item in it.  why did this change?   This is ultimately what is messing us up.

Also how do I get rid of that built in registration for IEnumable<T>?   Until I figure this out I am stuck at version 5.10.3.  Or refactor a lot of code to attempt to remove anywhere we are using Unity to resolving any object that has a constructor that takes a single parameter of IEnumberable<>

**Comment by ENikS** [comment]
You could try telling Unity how you want `List<>` to be created by registering it with default constructor:
```c#
unity.RegisterType(typeof(IList<>), typeof(List<>), Invoke.Constructor())
or
unity.RegisterType(typeof(List<>), Invoke.Constructor())
```
