### ISSUE TITLE
Containered type returns multiple instances. Bug or a design decision?

### ISSUE THREAD

**Issue by JarJarBinkz** [unitycontainer/unity#319]
After updating from Unity version 4.0.1 to Unity.Container 5.11.5 I notice a strange behaviour. 

**My View and my ViewModel are registered as follows:**

`this.Container.RegisterType<ApplicationSettingsMenuView>(new ContainerControlledLifetimeManager());`

`this.Container.RegisterType<IApplicationSettingsMenuViewModel, ApplicationSettingsMenuViewModel>(new ContainerControlledLifetimeManager());`

If the following code was executed under Unity 4.0.1, **only one instance of** `ApplicationSettingsMenuViewModel` was created.

`var a = this.Container.Resolve<ApplicationSettingsMenuView>();`
`var b = this.Container.Resolve<ApplicationSettingsMenuView>();`

`var c = this.Container.Resolve<ApplicationSettingsMenuViewModel>();`
`var d = this.Container.Resolve<ApplicationSettingsMenuViewModel>();`

`var e = this.Container.Resolve<IApplicationSettingsMenuViewModel>();`
`var f = this.Container.Resolve<IApplicationSettingsMenuViewModel>();`

If I now run this in Unity.Container 5.11.5, **multiple instances** of `ApplicationSettingsMenuViewModel` are created.

Is that a bug? Or is that on purpose?

</br>

__For completeness, here is the code of the view__

`public ApplicationSettingsMenuView(ApplicationSettingsMenuViewModel
applicationSettingsMenuViewModel)`
`{`
	`this.InitializeComponent();`
	`this.DataContext = applicationSettingsMenuViewModel;`
`}`

**Comment by ENikS** [comment]
The way Unity registers types has changed (described in more details in wiki).

You are registering two types: the view and the interface.
If you register your interface without lifetime manager, as a mapping, you’ll have your old behavior
