### ISSUE TITLE
4.0.2 fails to install using Nuget

### ISSUE THREAD

**Issue by PhilPJL** [unitycontainer/unity#32]
Using VS2015. Project target framework = 4.5.
I have Unity 4.0.1 installed which is dependent on CommonServiceLocator.

Attempt to update to 4.0.2 fails. 'Failed to add reference to System.Runtime'

If I try to install Unity.ServiceLocator separately which claims there are no dependencies for 4.5 I get 'failed to add reference to System.Globalization'.

If I try to install System.Globalization that fails because it can't target .NET 4.5

**Comment by Robot1que** [comment]
Same here =(

**Comment by pcibraro** [comment]
This supposed to be a new release for targeting Core CLR only. We will remove it from the nuget feed now and rename it so it does not cause more confusion.

**Comment by tangrl** [comment]
We are using internal NuGet server (ProGet). To Include all external NuGet packages we use a connector which is NuGet V2 (https://www.nuget.org/api/v2/). This is a limitation of ProGet. Somehow it picks up Unity 4.0.2 and causes the error above. Can you also remove from NuGet V2 feed?

Thanks!

Richard

**Comment by tomcrusader** [comment]
4.0.2 fails for me to - looks like the PCL profile has changed?

I'm using Unity with Xamarin and Prism.Forms, where PCL 111 is the correct target for Android+iOS+WPA81+UWP10.

`Could not install package 'Unity 4.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by SimonCropp** [comment]
so was 4.0.2 un listed?

**Comment by pcibraro** [comment]
Yes. Microsoft asked to do a clean break. We will be releasing everything in a new nuget package with the new signature and a new namespace. That package will contain the existing assemblies and also the new assemblies targeting core clr.  Does it make sense ? Thanks

**Comment by SimonCropp** [comment]
Ok cool. Perhaps close this one then?

**Comment by tiesmaster** [comment]
@pcibraro Is that also the reason the project was quite for the time being. I'm still waiting on some feedback for issue #36 ;)

**Comment by ENikS** [comment]
Not relevant anymore
