### ISSUE TITLE
Does not call constructor with Parameters

### ISSUE THREAD

**Issue by uniezuka** [unitycontainer/unity#325]
Given my code. Why Unity doesn't resolve my foo object to a constructor with parameters? Instead it calls the constructor with no parameters?

This unit test fails why?

[TestFixture]
    public class UnityFactoryFixture
    {
        private IUnityContainer container;

        [SetUp]
        public void SetUp()
        {
            container = new UnityContainer();
            container.RegisterType<IBar, Bar>();
        }

        [TearDown]
        public void TearDown()
        {
            container.Dispose();
        }

        [Test]
        public void Should_call_constructor_with_parameters()
        {
            var overrides = new ResolverOverride[] { new ParameterOverride("msg", "1") };
            var foo = container.Resolve<Foo>(overrides);

            StringAssert.AreEqualIgnoringCase("Constructor with parameters", foo.Message);
        }

        private interface IBar
        {
        }

        private class Bar : IBar
        {
        }

        private class Foo 
        {
            public string Message { get; set; }

            public Foo() 
            {
                Message = "Default Constructor";
            }

            public Foo(string msg, IBar bar) 
            {
                Message = "Constructor with parameters";
            }
        }
    }

**Comment by ENikS** [comment]
You need to register string so Unity can resolve it for parameter `msg`. 
Unity uses 'smart' algorithm and checks if it can resolve all parameters. It picks longest it can satisfy.
