### ISSUE TITLE
Using UnityContainer post-construction

### ISSUE THREAD

**Issue by rcdailey** [unitycontainer/unity#326]
First this isn't a bug but a question. Sorry if this isn't the right place.

I am told that it is "bad" to pass a `IUnityContainer` around through the interfaces of objects. However, several dependency injected objects are not created at construction time. They need to be created later in response to some events. Unless I keep around an instance to `IUnityContainer` in my class, I'm not sure how I'd be able to use `Resolve<>()` to do the dependency injection. Even worse, classes that are the subject of creation by `UnityContainer` only know of the interfaces for the types that are being injected, it doesn't get passed an instance to the creating `UnityContainer`. So those sub-types can't use it to delay-construct objects.

I don't see a way to avoid propagating the `IUnityContainer` instance down to classes in my hierarchy for the purposes of resolving implementations after construction has occurred.

How do you solve this common issue?

**Comment by rcdailey** [comment]
Would `UnityContainer.RegisterFactory()` also work? Not sure how you'd "reuse" the unity instance in the lambda though:

```
UnityContainer container;
container.RegisterType<IBar, Bar>();
container.RegisterFactory<IFoo>(c => c.Resolve<Foo>());
var bar = container.Resolve<IBar>();
```

Didn't compile this, but is this another solution?

Also I'm having difficulty with the API documentation page [here](http://unitycontainer.org/api/index.html), I expected to see a list of classes & functions but when I search "RegisterFactory()" function, I don't get any results. I'm not sure what parameters get passed to the lambda.

Thanks for the very quick response!

**Comment by ENikS** [comment]
Perhaps if you could explain what exactly you trying to accomplish I could give you better advice?

**Comment by rcdailey** [comment]
Here's some example code demonstrating the issue. The goal here would be to eliminate the reference to `IUnityContainer` inside `DynamicMenus` class.

```
using Unity;

interface ISomeDep
{
    void DoThing(string formName);
}

class DepImpl : ISomeDep
{
    public void DoThing(string formName)
    {
        Console.WriteLine($"DoThing() invoked for form: {formName}");
    }
}

class Form1
{
    readonly ISomeDep _dep;
    
    public Form1(ISomeDep dep)
    {
        _dep = dep;
    }
    
    public void Launch()
    {
        _dep.DoThing("Form1");
    }
}

class Form2
{
    readonly ISomeDep _dep;
    
    public Form2(ISomeDep dep)
    {
        _dep = dep;
    }
    
    public void Launch()
    {
        _dep.DoThing("Form2");
    }
}

class DynamicMenus
{
    readonly IUnityContainer _container;
    
    public DynamicMenus(IUnityContainer container)
    {
        _container = container;  
        Console.WriteLine("Constructed DynamicMenus");
    }
    
    public void ClickEvent1()
    {
        var form = _container.Resolve<Form1>();
        form.Launch();
    }
    
    public void ClickEvent2()
    {
        var form = _container.Resolve<Form2>();
        form.Launch();
    }
}

var c = new UnityContainer();
c.RegisterType<ISomeDep, DepImpl>();

var menus = new DynamicMenus(c);
// some time later...
menus.ClickEvent1();
// some time later...
menus.ClickEvent2();
```

**Comment by rcdailey** [comment]
In that example, the `DynamicMenus` class is actually code-behind for a C# winforms application. It is responsible for launching other Forms when the user clicks buttons in the UI. This class violates open/closed principle due to the tight coupling to the UI. So when new buttons are added to the new UI, new click handlers and new forms will need to be added. And I want to avoid adding more and more parameters to the constructor of `DynamicMenus`, basically something like:

```
Lazy<Form1> _f1;
Lazy<Form2> _f2;

public DynamicMenus(Lazy<Form1> f1, Lazy<Form2> f2)
{
  _f1 = f1;
  _f2 = f2;
}

public void ClickEvent1()
{
  _f1.Value.Launch();
}

// etc....
```

**Comment by ENikS** [comment]
This should work:
```
    public DynamicMenus(Func<Form1> func1, Func<Form1> func2)
    {
        _func1 = func1;
        _func2 = func2;
        Console.WriteLine("Constructed DynamicMenus");
    }
    
    public void ClickEvent1()
    {
        var form = _func1();
        form.Launch();
    }
    
    public void ClickEvent2()
    {
        var form = _func2();
        form.Launch();
    }

**Comment by rcdailey** [comment]
Sorry I guess I should have posted my second comment earlier, because that's the solution I tried too. But what if we have 20-30 forms? Is it really OK to have the constructor for `DynamicMenus` have 20-30 parameters?

**Comment by ENikS** [comment]
You are referencing these types from your code anyway.
Personally I would get IUnityContainer and use Resolve. There is nothing wrong with your original implementation
