### ISSUE TITLE
Uncertain behavior of RegistrationSet in 5.10.3

### ISSUE THREAD

**Issue by Lederilon** [unitycontainer/unity#329]
When registrations of different types are assigned to the same bucket, we have an issue iterating same bucket entries.
Because of --i construction, 'i' variable is assigned not to the 'entry.Next', but to 'entry.Next - 1', so next step 'entry' is wrong.
It seems to work with 'i - 1 = 0' against '--i'
'--i' is good only for first value of 'i' with is assigned to '_buckets[bucket]' 
For all next registrations -1 is already accounted at 
<img width="1271" alt="Знімок екрана 2020-05-13 о 17 28 02" src="https://user-images.githubusercontent.com/10696971/81825386-45845480-953f-11ea-9038-8f4cac6967c1.png">

Can't provide the UT, issue happens only when bucket collision occurs.

![image](https://user-images.githubusercontent.com/10696971/81822881-52ec0f80-953c-11ea-8c41-a8f267e1511c.png)

**Comment by ENikS** [comment]
Is this how the latest unity behaves too?

**Comment by Lederilon** [comment]
Probably this issue has been fixed at and I can create my own build of 5.10.3 with this fix
https://github.com/unitycontainer/container/commit/4547902c8fbb0a6582415b027d62db680df036c8#diff-74ae561ce90c6573d43d690d6a0bd8e1

**Comment by ENikS** [comment]
You should probably just upgrade. 5.10 was not particularly stable.
