### ISSUE TITLE
Resolving an instance registered as Singleton create new instance

### ISSUE THREAD

**Issue by aboudoux** [unitycontainer/unity#332]
Hi,

I'm facing a trouble about singleton resolution throught  the IDependencyResolver interface with the version 5.11.1 of UnityContaner

Indeed, a call to the resolve method with the concrete type as parameter  returns a new instance, while a call to the interface works as expected.

Here's a sample unit test to reproduce the problem :

```
public interface IMySingleton
{
	int Value { get; set; }
}

public class MySingleton : IMySingleton
{
	public int Value { get; set; } = 1;
}

[Fact]
public void ResolveSingletonOk()
{
	var container = new UnityContainer();
	container.RegisterSingleton<IMySingleton, MySingleton>();

	var singleton1 = container.Resolve<IMySingleton>();
	singleton1.Value = 5;

	var newSingleton = container.Resolve<IMySingleton>();
	newSingleton.Value.Should().Be(5); // Works fine
}
```

but

```
[Fact]
public void ResolveSingletonFail()
{
	var container = new UnityContainer();
	container.RegisterSingleton<IMySingleton, MySingleton>();

	var singleton1 = container.Resolve<MySingleton>(); // resolve concret type
	singleton1.Value = 5;

	var newSingleton = container.Resolve<MySingleton>(); // resolve concret type
	newSingleton.Value.Should().Be(5); // Fail because Value = 1
}
```

This poses a problem for me because when I implement the IDependencyResolver, the GetService pass the concret type and my software don't works.

**Comment by ENikS** [comment]
You are registering `IMySingleton` an a singleton and mapping it to unregistered `MySingleton`.

For this to work as intended, you need to register it like this:
```c#
container.RegisterSingleton<MySingleton>()
container.RegisterType<IMySingleton, MySingleton>()
```
So, you are registering your singleton type and map an interface to the singleton.

**Comment by aboudoux** [comment]
Thanks you, it works well !
