### ISSUE TITLE
Discussion: Using BuilderStrategy to intercept instantiations with mock objects for testing purposes

### ISSUE THREAD

**Issue by rcdailey** [unitycontainer/unity#333]
I have a unit test right now that verbatim runs our "production" type and singleton registrations and then proceeds to, for each registered type, resolve it to ensure that all interface dependencies have been registered. This has a lot of value in that it allows us to find logic issues (e.g. programmer created and added a dependency on `IFoo` but forgot to do a `RegisterType` for it) at unit test time rather than at run time which would be manual QA process.

The downside to this is that some interface implementations have external dependencies (e.g. COM) that are not facilitated in the unit test environment. To get around this, I think we still need constructor introspection for the actual concrete type while constructing a completely different type. Here's the flow I'm thinking of:

1. `container.RegisterType<IFoo, ConcreteFoo>()` happens at the start of the test (shared code with production)
1. Unit test iterates `container.Registrations`, but in this case we're only exercising `IFoo`.
1. Invoke `container.Resolve<IFoo>()`
1. Unity resolves the type to implementation `ConcreteFoo`.
1. Internally somewhere, Unity is iterating the constructor arguments of `ConcreteFoo` and resolving those. This process should be recursive starting from here. Each concrete type gets a `Resolve<>()` basically to ensure it is DI-enabled.
1. After `ConcreteFoo`'s constructor args are instantiated, a strategy should be invoked to allow me to instantiate `Mock<IFoo>` (using Moq library) instead of `ConcreteFoo`

Not sure if that was helpful as a "sequence diagram," but I basically wanted to point out the important behavior here: I want to resolve constructor arguments of the real type (and subsequently mock those interfaces as well) but I do not want the real type to be instantiated.

Is this possible today using builder strategies using Unity Container v5.8.10? The documentation is very sparse / non-existent, so I'm not sure how to properly use strategies to replace instantiations while still utilizing Unity's built in recursive type resolution that relies on reflection.

**Comment by ENikS** [comment]
This is a doable but rather involved scenario. It might take quite a lot of custom coding on unity side. 

Basically, this will require implementing something like an auto mocking extension. Might be quite useful for everyone but very complex. I thought about it, but decided to put it on a long ‘nice to have’ but not this time list.

Would your company sponsor this development?

**Comment by rcdailey** [comment]
I got an idea and implementation from [this](http://www.mikevalenty.com/auto-mocking-unity-container-extension/) link. It's a very simple `UnityContainerExtension` class. However, it isn't as flexible as I'd like for certain things (like having *some* types actually have an implementation instead of just an empty `Mock<>` that returns `null` for every method called on it).

Doubtful there will be sponsorship. I'm actually not asking for anything to be implemented native to your library. This was mostly just a discussion to get some valuable advice from someone far smarter than I am about DI.

Thank you for your response!
