### ISSUE TITLE
Allow usage of Intercept as mocker

### ISSUE THREAD

**Issue by dzmitry-lahoda** [unitycontainer/unity#34]
I use `Nest.IElasticClient` for audit. I want to disable audit to test performance impact. I want to use mock for it. It has huge amount of methods, so I want just generate mock. I use Moq for tests, but need something into production code to deploy for scale testing. We use Unity. It has `Intercept` which is almost mock, but next code fails.

**Could we have special mode of `Intercept` to generate mocks?**

```
            IKnownType unityProxy = Intercept.ThroughProxy<IKnownType>(
null,
new InterfaceInterceptor(),
new IInterceptionBehavior[] {
new MockInterceptionBehavior()
});
    class MockInterceptionBehavior : IInterceptionBehavior
    {
        public IEnumerable<Type> GetRequiredInterfaces()
        {
            return Type.EmptyTypes;
        }

        public IMethodReturn Invoke(IMethodInvocation input, GetNextInterceptionBehaviorDelegate getNext)
        {
            return input.CreateMethodReturn(null);
        }

        public bool WillExecute
        {
            get { return true; }
        }
    }
```

**Comment by ENikS** [comment]
I feel this should be directed to Mock team.
