### ISSUE TITLE
Allow resolve type with default value in constructor

### ISSUE THREAD

**Issue by davidshen84** [unitycontainer/unity#35]
The following code will not work:

```
  _container = new UnityContainer()
    .AddNewExtension<Interception>()
    .RegisterType<ObjectCache, MemoryCache>(
      new InjectionConstructor("some_cache")));
```

Because `MemoryCache` type require two parameters in the constructor, a _string_ which is **required**, and a _NameValueCollection_ which is **defaulted to null**.

In my case, I have to provide  a non-null instance of the type _NameValueCollection_. But it would be more convenient if we do not need to provide parameters that already have a default value.

**Comment by ENikS** [comment]
This would take some research

**Comment by ENikS** [comment]
Moved to unitycontainer/container#23
