### ISSUE TITLE
Unable to redirect assembly after upgrading to 5.8 to 5.11 

### ISSUE THREAD

**Issue by G31st** [unitycontainer/unity#350]
Hi All 

I've trying to upgrad a hosting application from 5.8 to 5.11, I'm not unable to redirect unity abstractions. The other unity assemblies seem fine. I noticed the public token change on the assembly changed (5.11). Any reason for this ?

**Comment by ENikS** [comment]
It used different signing certificate. Now all assemblies are using unified certificate.
