### ISSUE TITLE
Dependee with multiple dependents

### ISSUE THREAD

**Issue by EuroEager2008** [unitycontainer/unity#354]
Having 3 objects (services), HighLevelServiceA, HighLevelServiceB and LowLevelService.
The HighLevelServices are both depending on the same instance of LowLevelService.
The LowLevelService would normally be registered as a Singleton I guess, but it must be a new instance at each "session".
The "session" is actually defined by a button click handler in a VSTO Ribbon and each click must re-instantiate all 3 services, but the LowLevelService as a kind of singleton.

I don't know how to achieve this, anyone hint me?

**Comment by ENikS** [comment]
- You'd need a global, perhaps static, singleton that changes with each click.
- You would need a custom lifetime manager similar to hierarchical manager that uses singleton to validate.
- Register low level service with that manager.

You click, singleton changes, resolution starts, lifetime manager sees singleton is not the same and returns NoValue which forces creating new lov level service.
It serves the same instance until next click.

**Comment by EuroEager2008** [comment]
Thanks
I will try rolling my own LifeTimeManager (have no idea how to do, but I guess not too tricky)
