### ISSUE TITLE
Method "ToString" does not have an implementation exception Unity versions 5.11.8 and 5.11.9

### ISSUE THREAD

**Issue by the800kid** [unitycontainer/unity#359]
I updated from Unity version 5.11.7 to 5.11.9 and started receiving an exception on a method implementation of "ToString".  The following error happens when calling the LoadConfiguration method on the UnityContainer object.

System.TypeLoadException: 'Method 'ToString' in type 'Unity.Interception.ContainerIntegration.Interceptor' from assembly 'Unity.Interception, Version=5.10.1.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' does not have an implementation.'

I backed down to version 5.11.8 which also generated the same error.  I backed down to the original version 5.11.7 and the error disappeared.

Source code used to generate the error:

`
using System;
using Microsoft.Practices.Unity.Configuration;
using Unity;

namespace API
{
    /// <summary>
    /// Specifies the Unity configuration for the main container.
    /// </summary>
    public static class UnityConfig
    {
        #region Unity Container
        private static Lazy<IUnityContainer> container =
          new Lazy<IUnityContainer>(() =>
          {
              var container = new UnityContainer();
              RegisterTypes(container);
              return container;
          });

        /// <summary>
        /// Configured Unity Container.
        /// </summary>
        public static IUnityContainer Container => container.Value;
        #endregion

        /// <summary>
        /// Registers the type mappings with the Unity container.
        /// </summary>
        /// <param name="container">The unity container to configure.</param>
        /// <remarks>
        /// There is no need to register concrete types such as controllers or
        /// API controllers (unless you want to change the defaults), as Unity
        /// allows resolving a concrete type even if it was not previously
        /// registered.
        /// </remarks>
        public static void RegisterTypes(IUnityContainer container)
        {
            // NOTE: To load from web.config uncomment the line below.
            // Make sure to add a Unity.Configuration to the using statements.
             container.LoadConfiguration();

            // TODO: Register your type's mappings here.
            // container.RegisterType<IProductRepository, ProductRepository>();
        }
    }
}`

**Comment by ENikS** [comment]
Could you provide a Unit Test I can run?

**Comment by the800kid** [comment]
Sorry for the delayed reply.  I have been working on a unit test when time permits..  At the moment I have not been able to reproduce the issue in the unit test.  I have to go through the unit test some more and make sure I am exactly replicating the main application.

**Comment by wrekaveli** [comment]
Hey guys,

I got the same problem and extracted it into a small solution with one unit test. Hope you can work with it.

https://github.com/wrekaveli/UnityToStringIssue

**Comment by vezixig** [comment]
Is there any info, when this will be fixed?
We are using Unity together with Prism and Prism8 depends on 5.11.8 so updating Prism is not possible atm.
