### ISSUE TITLE
Add support for easier configuration of decorators.

### ISSUE THREAD

**Issue by tiesmaster** [unitycontainer/unity#36]
When using DI, it's very common to use decorators as a way to handle SRP well. Right now, I'm configuring a decorator for a particular class like this:

``` csharp
        var innerSmtpClientServiceIdentifier = Guid.NewGuid().ToString();
        Container.RegisterType<ISendViaSmtpClientService, SendViaSmtpClientService>(innerSmtpClientServiceIdentifier);
        Container.RegisterType<ISendViaSmtpClientService, AppInsightDependencyTrackingSendmailDecorator>(
            new InjectionConstructor(
                new ResolvedParameter<ISendViaSmtpClientService>(innerSmtpClientServiceIdentifier)));
```

However, that is very verbose, and [requires you to specify the constructor arguments](http://stackoverflow.com/a/6110813/471780), which leads to difficult to maintain code.

That SO post is already a couple years old, so maybe there is already a different way how to do this.  But if that's not the case, then this might be a good addition to Unity.

A possible api for this could be:

``` csharp
        Container.RegisterType<ISendViaSmtpClientService, SendViaSmtpClientService>();
        Container.RegisterDecorator<ISendViaSmtpClientService, AppInsightDependencyTrackingSendmailDecorator>();
```

where `RegisterDecorator` would find and modify the the first registration to be named, and make the second call with that named component.

I'm happy to put in a PR, if wanted for Unity.

**Comment by arielszklarkiewicz** [comment]
Hi Thijs!

Sounds good.

Yes, feel free to make a Pull Request!

Thanks!

Ariel

**Comment by tiesmaster** [comment]
Hi,

I had some time to work on this a couple days ago, and I was trying to make the `InjectionConstructor` call "dynamic" in my sample code.

To understand how unity works, and how it deals with constructors, I looked into how it works when you configure Unity based on the `InjectionMember`'s (like the `InjectionConstructor`, and `InjectionFactory`).

I noticed that my suggested API, using an extension method, could be more inline with the "configuration API", and I came up with a different approach. Below you'll find my proposed api.

---
If you just want to configure a new decorator for `MyClass`, you specify an `InjectionDecorator` (which is of type `InjectionMember`):

````csharp
    container.RegisterType<IMyInterface, MyDecorator>(new InjectionDecorator<MyClass>());
````

which will configure Unity to resolve any dependencies that `MyDecorator` has of type `IMyInterface` with `MyClass`, instead of the `MyDecorator`.

---

Next, in case you need to configure the constructor, you can indicate that with `DecoratedParameter` (which is a "sibbling" of `ResolvedParameter`, and `InjectionParameter`):

````csharp
    container.RegisterType<IMyInterface, MyDecorator>(
        new InjectionConstructor(new DecoratedParameter(typeof(MyClass)), typeof(DepA)));
````

which will configure Unity to resolve the specified parameter to map to `MyClass`, instead of the default mapping from `IMyInterface` to `MyDecorator`.

---

I've experimented a little bit with this in a separate solution, to find out if this would work, and how. The repo is [here](https://github.com/tiesmaster/ResearchDecoratorsInDiContainers), and the unit test where I have everything is [this one](https://github.com/tiesmaster/ResearchDecoratorsInDiContainers/blob/master/UnityExample/UnityDecoratorTests.cs).

Before I continue, and make the code production worthy, add unit tests, and write xml-documentation, and put it in a PR, I'd like to have some feedback. What do you think of this approach?

**Comment by tiesmaster** [comment]
@arielszklarkiewicz Did you see my issue comment? I'd like to finish this, but before I do, I'd like to get some feedback on the approach I intent to take. What do you think about it?

**Comment by tiesmaster** [comment]
@pcibraro @woodp Can you guys maybe give feedback on this issue?

Btw I hope I hope I found the right usernames, according to the [blogpost](http://blogs.msdn.com/b/dotnet/archive/2015/08/21/the-future-of-unity.aspx), you guys are the new owners of Unity (though, not really easily to be found on Github...).

**Comment by smarts** [comment]
How would this work with multiple decorators?
e.g., let's say you have an interface, an implementation of the interface that reads from a database, a decorator that logs any exceptions and re-throws them, and another decorator that wraps any thrown exception in your custom exception.

**Comment by tiesmaster** [comment]
That's a really good point. I didn't think of that, and decorating a class a couple of times is very common use case, so we should address that. Do you have any suggestions how to work that in my proposed API?

I still have [my playground](https://github.com/tiesmaster/ResearchDecoratorsInDiContainers/blob/master/UnityExample/UnityDecoratorTests.cs), which can easily be used for playing around and coming up with a good, improved solution for this.

I definitely think it's should be possible to work this into my suggested solution, for example, the `DecoratedConstructorSelectorPolicy` could receive a `params Type[] decoratedClass`, instead of a single type. How to do that with the `InjectionDecorator` I'm not 100% sure. If you have ideas on that, I'm happy to hear them.

---

That being said, I was wondering how you're involved with this. As you can see, this issue basically went dead. I've asked for feedback a couple of times, but didn't get any responds. So if this is not going anywhere, then I don't want to spent too much time on this. So that's why I'm asking. Do you have any ideas if this project is still alive?

**Comment by smarts** [comment]
I'm not involved in any official capacity. I filed an issue a long time ago on Code Plex. Since it moved to GitHub I figured I'd put in a pull request. I haven't gotten any traction on my issue either.
I was just looking through issues and came across yours. I like Unity but I think it would be great if Unity had some easy way of decorating, so I figured I'd read through the issue and add my 2 cents.
Hopefully someone will pay attention soon!

**Comment by tiesmaster** [comment]
Ok, then I'll wait with reworking my api until the project will get some traction again. Thanks for your input!

**Comment by ENikS** [comment]
I know it was a while but I'd like to continue this discussion.

**Comment by tiesmaster** [comment]
Sure, how do you want to proceed? My understanding of how I wanted to go with this, is a bit rusty, so I would need to brush up on this. Do you already have an idea on this yourself?

**Comment by ENikS** [comment]
Nop! Perhaps a test case demonstrating the issue and a solution would help.
Could you submit pull request with proposed fix?

**Comment by ENikS** [comment]
I'll close this for now. Feel free to reopen once you have better understanding how it should be done.
