### ISSUE TITLE
In 4.0.1, the Unity-project has been compiled as PCL. This cannot be referenced anymore by C++ projects. Please provide version as normal class library.

### ISSUE THREAD

**Issue by gottscbe** [unitycontainer/unity#38]
If I try to update to Unity 4.0.1 in our solution here, I get many errors of the following type:
warning C4691: 'System::IDisposable': type referenced was expected in unreferenced assembly 'System.Runtime', type defined in current translation unit used instead.
That problem seems to occur, because the Unity project has been compiled as PCL, not as normal Class Library anymore. Please provide a Class Library version, too.

**Comment by arielszklarkiewicz** [comment]
Hi,

There will be new versions soon. Please keep using version 3.5.1405 for
your scenario in the meantime.

Thanks,

Ariel

**Comment by davidjward30** [comment]
Is there any update on this? Unity for Prism 6 requires >=4.0.1 so continuing to use 3.5 is becoming more of a problem.

**Comment by ENikS** [comment]
Well, it is going to be SOON :)
