### ISSUE TITLE
Consider Adding IBuilderContext.ParentContext

### ISSUE THREAD

**Issue by Mike-EEE** [unitycontainer/unity#39]
Currently there is only a IBuilderContext.ChildContext, which only appears to be used when there is an exception.  It would be nice to easily walk up the current build chain to find the originating (or any) previous build contexts and their build keys.

**Comment by Michael-DST** [comment]
FWIW, I am having to resort to [this strategy](https://github.com/DragonSpark/Framework/blob/Multiversal/DragonSpark/Activation/IoC/BuildChainMonitorStrategy.cs) in the meantime, which works with [this extension method](https://github.com/DragonSpark/Framework/blob/Multiversal/DragonSpark/Extensions/BuilderContextExtensions.cs#L15-L19) to get the data that I need.  This implementation is using the [Connected Properties project](http://connectedproperties.codeplex.com/), which is a pretty cool project, IMO.:)

**Comment by ENikS** [comment]
You could use stack externally to support this behavior.

**Comment by Mike-EEE** [comment]
hey @ENikS thanks for keeping this project alive... curious though is there a resource/blog/url/story on what happened with 4.0 and those that were entrusted with this repo from the start?

**Comment by ENikS** [comment]
Not really sure what happened. By the time I took over it was abandoned for 3 years.

**Comment by Mike-EEE** [comment]
Right... so I guess what I am curious on is how you were able to take over.  Did someone from MSFT still have the keys to the repo or something?  From what I understand, it was handed over to two developers who promptly ghosted out of any meaningful ownership and/or contributions.  Which is, of course, exactly the thing that is _not_ supposed to happen, especially when considering they were greatly touted and so highly commended in the official MSFT announcement as trusted guardians of this repo.

SorryNotSorry... just not a fan of how this project was treated/managed/handed off. 😛 

In any case, it seems like you're _more_ than the right person for the job here and it's good to see some life back into this project. 👍

**Comment by ENikS** [comment]
I forked project and started to fix issues. When it came time to deploy I asked owners if they want to give me the controls. They did and I been handling it ever since. 

The previous owners are still around, they just don't work on Unity anymore.

I am glad you approve :)

**Comment by Mike-EEE** [comment]
> they just don't work on Unity anymore.

The way I see it, they never worked on Unity to begin with. 😛 But thank you for taking the time to provide some context.  I see that there was a certificate that was lost in the transition, which was adding to the mystery (misery? 😆) as well.  

It seems like everything possible that could have happened wrong in the hand-off happened, save for someone losing the administrator/contributor status thereby permanently locking anyone out from ever recovering the project from an authoritative perspective.

FWIW I am harping on this because:

1. I really liked Unity.  I used it in all of my projects for _years_.
1. This is really uncharacteristic of the .NET group which has been on an absolute tear -- for these past few years especially.  Very few if any instances of these types of mishaps have occurred.

But in the end, it seems like everything landed as it should.  As always, a little patience goes a long ways.  A most difficult lesson to learn in life. 😉
