### ISSUE TITLE
Interception behaviors not cleared when re-registering (bug or by design)

### ISSUE THREAD

**Issue by Minx-SigEp** [unitycontainer/unity#40]
I have a large project were my team is using convention based registration to handle the majority of the work. We then re-register a handful of types so we can handle changing lifetime manager and other details about the registration. This second registration of the type does not clear the interception behaviors which causes the behavior to be in the pipeline twice. As a workaround we are finding the IInterceptionBehaviorsPolicy for any type that needs to be re-registered and removing it before re-registering.

I have created a sample project that shows the issue as well as a screen shot. The sample project can be found at https://github.com/Minx-SigEp/UnityInterceptionBug 
![unityinterception](https://cloud.githubusercontent.com/assets/5995359/12066421/032b4bcc-afa5-11e5-9b98-87723edafabf.png)

**Comment by ENikS** [comment]
Moved to unitycontainer/registration-by-convention#1
