### ISSUE TITLE
Where is xsd for unity 4.0.1

### ISSUE THREAD

**Issue by a-frey** [unitycontainer/unity#41]
Hi,

I am looking for the schema definition (xsd) for unity 4.0.1.

Can you share this please?

**Comment by arielszklarkiewicz** [comment]
Hi,

Which XSD are you referring to?

Thanks,

Ariel

**Comment by a-frey** [comment]
Hi,

I would like to have IntelliSense support for unity xml configuration file. On github i already found the schema definition for version 3 of unity. (https://github.com/unitycontainer/unity/blob/master/source/UnityConfiguration30.xsd)

I am looking for the schema for version 4.

Thanks,
Andreas

**Comment by toddmo** [comment]
Did you find it? What's in 4.0.1 that I would miss out on with the 3.0 schema?
