### ISSUE TITLE
Support for vnext/.net 5.0?

### ISSUE THREAD

**Issue by falconmick** [unitycontainer/unity#42]
Just wondering if Unity has support for vnext yet? I've only seen blog posts showing people usign ifdef on the runtime env being 4.5. I really hate this form of coding, so I was wondering if the project supports vnext yet?

Also is there a release blog or somthing I can follow/read?

**Comment by falconmick** [comment]
I tried downloading the source and checking out core-clr. But when I build I get 1117 errors... Namespace doesn't exist... So How am I supposed to build?

**Comment by arielszklarkiewicz** [comment]
Hi,

Please try the xUnit branch in the meanwhile. You can also use the package
at https://www.nuget.org/packages/Unity-CoreClr/1.0.0-beta3.

Thanks,

Ariel

**Comment by falconmick** [comment]
Cheers.

Is there any documentation at the moment for integrating with the new Dependency Injection pipeline they have?

**Comment by arielszklarkiewicz** [comment]
Not yet.

For ASP.NET MVC web applications or Web API, please add the `Unity.Mvc6` package, which reference to `Unity-CoreClr`.

In an ASP.NET MVC application, and using the  ASP.NET 5 Template for Web Application, you will tipically declare a `UnityContainer` property in the `Startup` class. Lets say a 
```UnityContainer _container;```

In the `Startup` method you should instantiate it 

```
 _container = new UnityContainer();
```

The `ConfigureServices` method is where you configure all types you need in the container and, at the bottom of the method, call the `Register` method of `Unity.Mvc.Configuration`, passing the `services` `IServiceCollection` that comes as `ConfigureServices`'s parameter and the container.
It will look like this:

```
public void ConfigureServices(IServiceCollection services)
{
  ...
  services.AddMvc(); // comes with the template
  ...
  _container.RegisterInstance<ISampleInterfaceA>(new SampleClassA());
  _container.RegisterInstance<ISampleInterfaceB>(new SampleClassB());
  ...
  Unity.Mvc.Configuration.Register(services, _container);
}
```

Finally, add the following 2 lines to the begining of the `Configure` method:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  _container.AlternativeServiceProvider = app.ApplicationServices;
  app.ApplicationServices = _container.Resolve<IServiceProvider>();
  ...
}
```

That's it. You should, for instance, write constructors for your controllers that expect `ISampleInterfaceA` and `ISampleInterfaceB` parameters, and they will be injected as configured.

Cheers,

Ariel

**Comment by luizfbicalho** [comment]
I looked at the core-clr version, and the biggest doubt that I have is about the configuration, do you have plans to make some json configuration to use with asp.net 5? 
Do you have a table of features planned for unity-coreclr and old unity? I'm not even sure if all of the actual features can be in the coreclr version.

**Comment by Hem** [comment]
Ariel this solution is not longer working.

1. _container.AlternativeServiceProvider was not found.

2. I'm receiving this error.


An exception of type 'Unity.ResolutionFailedException' occurred in Unity-CoreClr.dll but was not handled in user code

Additional information: Resolution of the dependency failed, type = "Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler", name = "(none)".

Exception occurred while: while resolving.

Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider", name = "(none)".

Exception occurred while: while resolving.

Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "Microsoft.AspNetCore.Mvc.Internal.IControllerPropertyActivator[]", name = "(none)".

Exception occurred while: while resolving.

Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "Microsoft.Extensions.Localization.IStringLocalizerFactory", name = "(none)".

Exception occurred while: while resolving.

Exception is: InvalidOperationException - The current type, Microsoft.Extensions.Localization.IStringLocalizerFactory, is an interface and cannot be constructed. Are you missing a type mapping?

-----------------------------------------------

At the time of the exception, the container was:



  Resolving Microsoft.Extensions.Localization.IStringLocalizerFactory,(none)



-----------------------------------------------

At the time of the exception, the container was:



  Resolving Microsoft.AspNetCore.Mvc.Internal.IControllerPropertyActivator[],(none)

    Resolving Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator,Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (mapped from Microsoft.AspNetCore.Mvc.Internal.IControllerPropertyActivator, Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

    Resolving parameter "modelMetadataProvider" of constructor Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionaryControllerPropertyActivator(Microsoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider modelMetadataProvider)

      Resolving Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider,(none) (mapped from Microsoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider, (none))

      Resolving parameter "detailsProvider" of constructor Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider(Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ICompositeMetadataDetailsProvider detailsProvider)

        Resolving Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ICompositeMetadataDetailsProvider,(none)



-----------------------------------------------

At the time of the exception, the container was:



  Resolving Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerProvider,(none) (mapped from Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider, (none))

  Resolving parameter "controllerFactory" of constructor Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerProvider(Microsoft.AspNetCore.Mvc.Controllers.IControllerFactory controllerFactory, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerCache controllerActionInvokerCache, Microsoft.AspNetCore.Mvc.Internal.IControllerArgumentBinder argumentBinder, Microsoft.Extensions.Options.IOptions`1[[Microsoft.AspNetCore.Mvc.MvcOptions, Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] optionsAccessor, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, System.Diagnostics.DiagnosticSource diagnosticSource)

    Resolving Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory,(none) (mapped from Microsoft.AspNetCore.Mvc.Controllers.IControllerFactory, (none))

    Resolving parameter "propertyActivators" of constructor Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory(Microsoft.AspNetCore.Mvc.Controllers.IControllerActivator controllerActivator, System.Collections.Generic.IEnumerable`1[[Microsoft.AspNetCore.Mvc.Internal.IControllerPropertyActivator, Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] propertyActivators)

      Resolving System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Mvc.Internal.IControllerPropertyActivator],(none)



-----------------------------------------------

At the time of the exception, the container was:



  Resolving Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler,(none)

  Resolving parameter "actionInvokerFactory" of constructor Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler(Microsoft.AspNetCore.Mvc.Internal.IActionInvokerFactory actionInvokerFactory, Microsoft.AspNetCore.Mvc.Infrastructure.IActionSelector actionSelector, System.Diagnostics.DiagnosticSource diagnosticSource, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor actionContextAccessor)

    Resolving Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory,(none) (mapped from Microsoft.AspNetCore.Mvc.Internal.IActionInvokerFactory, (none))

    Resolving parameter "actionInvokerProviders" of constructor Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory(System.Collections.Generic.IEnumerable`1[[Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider, Microsoft.AspNetCore.Mvc.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] actionInvokerProviders)

      Resolving System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider],(none)
