### ISSUE TITLE
Unity 2.1 - RegisterInstance

### ISSUE THREAD

**Issue by Khyatikundlani** [unitycontainer/unity#44]
We are using Unity 2.1 in Asp.net application. 

We are using following code in BeginRequest of Global.asax:

public IUnityContainer GetContainer()
        {
            EngineContainer container = new EngineContainer(_correl);  
            container.RegisterInstance<ICorrelationInfo>(CORRELATION, _correl);
            foreach(DependencyTypeMap typeMap in _typeMapList)
            {
                 SetupDI(container, typeMap);
            }  
            return container;
        }

```
    private void SetupDI(EngineContainer engContainer, DependencyTypeMap map)
    {
         foreach (var m in map.Maps)
        {
            List<object> args = new List<object>();
            args.Add(engContainer.CorrelationInfo);
            if (m.Item3 != null && m.Item3.Count() > 0)
            {
                args.AddRange(m.Item3);
            }           
            if (m.Item4 != null && m.Item4.Count() > 0)
            {
                args.AddRange(m.Item4);
            }
            engContainer.RegisterType(m.Item1, m.Item2, new InjectionConstructor(args.ToArray()));
        }

        if (map.IsloggingEnabled)
        {
            foreach (var type in map.TypesToIntercept)
            {
                engContainer.SetupForInteception(type);
            }
        }
    }
```

Issue: 
The value being passed to RegisterInstance is a session id. In one of the scenario the value being passed to RegisterInstance is user A's id. However, what we get in the Controller is user B's id. So, when Unity is creating Controller instance, incorrect session id is being supplied to the Controller.

Question:
Is RegisterInstance thread safe? 
What could be the cause of problem that I am facing

**Comment by arindambasu** [comment]
The RegisterInstance method provides a similar dependency feature to the RegisterType method (when used with the ContainerControlledLifetimeManager) in that it creates a registration that always returns a reference to the same instance of the specified object, as long as that object is in scope. The RegisterType method with a ContainerControlledLifetimeManager automatically generates this single instance the first time your code calls it, and the RegisterInstance method accepts an existing instance for which it will return references.

If you foresee that object to be used per session, then registertype should be the way forward.

Just a thought...
