### ISSUE TITLE
Unity should throw user friendly message instead of StackOverflowException on cycle depency

### ISSUE THREAD

**Issue by dzmitry-lahoda** [unitycontainer/unity#48]
Latest NuGet Unity  throws `StackOverflowException` instead of `DependencyCycleException: Type B depends on A and A depends on B`. I give simple example here, but in cases we had there where in 3 levels of indirection and dozens of classes so searching for such cycles is hard. It takes day to find root cause of such issues. It would be OK to have special extensions or call on container to validate such things on application start.

``` fsharp
open System
open Microsoft.Practices.Unity

type IA =
  abstract member DoA : unit -> unit

type IB =
  abstract member DoB : unit -> unit

type A(bDepenency:IB) =
  let b = bDepenency
  interface IA with
    member this.DoA() = ()

type B(aDependency: IA) =
  let a = aDependency
  interface IB with
    member this.DoB() = ()

type C() = 
  let c = 1
  interface IA with
    member this.DoA() = ()

[<EntryPoint>]
let main argv = 
    use c = (new UnityContainer()).RegisterType<IA,A>().RegisterType<IB,B>().RegisterType<C>()
    //let r = c.Resolve<C>();
    let r = c.Resolve<IA>();
    Console.WriteLine(r)
    0 // return an integer exit code
```

https://gitlab.com/dzmitry-lahoda/clr/blob/master/enterprise/containers/unity/Program.fs

**Comment by asd-and-Rizzo** [comment]
See how perfect is DryIoc
```
An unhandled exception of type 'DryIoc.ContainerException' occurred in DryIoc.dll

Additional information: Recursive dependency is detected when resolving

IA as parameter "aDependency" <--recursive

  in B: IB as parameter "bDepenency"

  in A: IA <--recursive.
```

**Comment by dadhi** [comment]
In __DryIoc__ you can also call `container.VerifyResolutions()` to find such errors beforehand.

**Comment by ENikS** [comment]
This would only be possible if dependency graph is analysed during loading of catalog or ServiceCollection. The way Unity deals with registrations I really doubt it is feasible.
