### ISSUE TITLE
Allow intercepting methods of multiple interfaces through InterfaceInterceptor

### ISSUE THREAD

**Issue by DixonD-git** [unitycontainer/unity#5]
It would be useful to extend `InterfaceInterceptor` so that we can intercept multiple interfaces at once.   There is `TransparentProxyInterceptor` which does much more that but it is claimed to be much slower, I guess, because it intercepts virtual methods as well.

**Comment by DixonD-git** [comment]
It looks like I've missed `Intercept.ThroughProxyWithAdditionalInterfaces`. I guess, this issue can be closed.

**Comment by pcibraro** [comment]
Thanks. I will close it.
