### ISSUE TITLE
How to impelment Unity DI for my scenario to load class dynamically

### ISSUE THREAD

**Issue by karlosRivera** [unitycontainer/unity#52]
i want to load my class dynamically by Unity DI container based on country code saved in variable.

our win apps has shipping functionality for which we use web service developed by 3rd party company like UPS, FedEx and Purolator.

now how to design my code with unity as a result i could load my shipping class based on country code stored in variable?

suppose this is my sample or proposed class design

   public interface IShip
    {
        string Ship();
    }

```
public class UPS : IShip
{
    public string Ship()
    {
    }
}

public class FedEX : IShip
{
    public string Ship()
    {
    }

}

public class Purolator : IShip
{
    public string Ship()
    {
    }

}
```

now tell me how could i use unity to load class based on variable value.

suppose if GB is stored in variable then i want to load UPS class and invoke ship function ?

suppose if FR is stored in variable then i want to load UPS class and invoke ship function ?

suppose if US is stored in variable then i want to load FedEx class and invoke ship function ?

suppose if CA is stored in variable then i want to load Purolator class and invoke ship function ?

please discuss it with code example of unity thanks

**Comment by ENikS** [comment]
I suppose it is not relevant anymore
