### ISSUE TITLE
Missing companion libraries 

### ISSUE THREAD

**Issue by tylerohlsen** [unitycontainer/unity#53]
I see in [this commit](https://github.com/unitycontainer/unity/commit/bff423458d0fa98b823aef8a8f85364762b74758) that all of the companion libraries have been deleted from the repository (committed directly to master).  What is the plan for getting this functionality back?  
- Unity.Configuration
- Unity.RegistrationByConvention
- Unity.RegistrationByConvention.NetCore
- Unity.RegistrationByConvention.WindowsPhone
- Unity.Interception
- Unity.Interception.Configuration
- Unity.WebApi
- Unity.Mvc

Can we get details about what is getting worked on and anything that is on the roadmap?  It would be good for the community to be aware.

**Comment by ENikS** [comment]
It is all back
