### ISSUE TITLE
NULL Reference Exception - MVC6 - RC2

### ISSUE THREAD

**Issue by rgillen** [unitycontainer/unity#57]
I ran into an issue when trying to use Unity with MVC 6 - RC2 (vNext)

When calling the following line to transfer exisiting registrations to the Unity container I received a NULL reference exception

`Unity.Mvc.Configuration.Register(services, container);`

I was able to trace the issue to the following method... Unity.MVC6\Configuration.cs\RegisterFactory() (line #172)

The following argument is being passed to the `IUnityContainer.RegisterType()` method

`serviceDescriptor.ImplementationType.AssemblyQualifiedName,`

When calling `RegisterFactory()` the property `serviceDescriptor.ImplementationType` is NULL. This makes complete sense, as the method suggests a factory is being registered (not an explicit type).

I was able to resolve my issue by changing the overload that is called (omitted the 'name' argument).

My question is... was that the correct fix or is there a larger issue hiding?

Digging deeper into the `RegisterFactory()` I noticed there are 2 code paths through the method. 

The key switch being `isAggregateType`, for my use-case `isAggregateType = true;` when `isAggregateType = false;` The overload of `IUnityContainer.RegisterType()` called already omits the `serviceDescriptor.ImplementationType.AssemblyQualifiedName,`

Now both paths are exactly the same... this is why I am unsure if the fix is 100% correct. If there were indeed 2 code paths through the method surely there must have been some minor nuance between them. At this point it appears lost as both are now exactly the same.

It would be great if I could receive some clarification on this. I would be happy to submit a repro if necessary

**Comment by KveRa** [comment]
Got the same problem and use the same fix here.
