### ISSUE TITLE
UNITY version 4 where is registertypes method

### ISSUE THREAD

**Issue by stevensrf1** [unitycontainer/unity#60]
I do not see the RegisterTypes method for the unity container when using unity version 4
I do see the RegisterTypes method the the unity container when using unity version 3
Is it still possible to use the RegisterTypes method for unity version 4 or has it been completely done away with?
Feel free to email me responses directly to stevensrf1@inbox.com

**Comment by ENikS** [comment]
This method belongs to RegistrationByConvention and has been removed from the core library. The functionality will be added back as a separate package.

**Comment by ENikS** [comment]
[This Repository](https://github.com/unitycontainer/registration-by-convention) will be release as separate package Unity.RegistrationByConvention shortly after 5.0.0 is released
