### ISSUE TITLE
Visual Studio 2015 InvalidProgramException in Unit Test With Fakes

### ISSUE THREAD

**Issue by emilyclairelewis42** [unitycontainer/unity#7]
Hello, I'm having trouble solving an extraordinarily odd problem when faking the Unity Container with Visual Studio 2015 in a .NET 4.6 project. This problem is new to Visual Studio 2015 and distinct to the VSTest runner.

I was wondering if you could kindly look at the following post I made [here](http://stackoverflow.com/questions/32768123/visual-studio-2015-invalidprogramexception-in-unit-test-with-fakes) and help me understand if this is a Unity Container issue or a Visual Studio issue?

Thank you for your time.

**Comment by pcibraro** [comment]
I can tell you that .NET 4.6 is not a supported scenario yet or at least, we haven't tried. We are working on getting an stable release for 4.6 and coreclr in the next few months.
