### ISSUE TITLE
Diagram tool for Unity

### ISSUE THREAD

**Issue by pantonis** [unitycontainer/unity#70]
Hi,

I recently started using IOC and more specifically Unity. As my project grows I think I am getting lost on which has dependency to what.

Is there any tool that analyzes the code and shows the dependency as a diagram or something equivalent?

Thanks

**Comment by moerwald** [comment]
Hi,

the container stores it mappings under the `Registrations` attribute. Each Registration consists of `Name`, `RegisteredType` and `MappedToType`. You can write a simple dump method that iterates through `Registrations` and logs beforehand mentioned attributes.

Example:

foreach (var item in container.Registrations) {
   var regType = item.RegisteredType.Name;
   var mapTo = item.MappedToType.Name;
    var regName = item.Name ?? "[default]";
    var lifetime = item.LifetimeManagerType.Name;

    Logger.Info ($"{regName}: {regType} -> {mapTo}. {lifetime}");
}

Infos about lifetime -> [lifetime](https://msdn.microsoft.com/en-us/library/ff660872(v=pandp.20).aspx)

**Comment by pantonis** [comment]
@moerwald  thanks for the reply.

I was looking for something which shows the dependency injection tree.

e.g I have following:
IType1, Type1
IType1, Type1A
IType2, Type2
IType3, Type3
IType4, Type4

Type3 has in its constructor IType2 (Type2), IType1 (Type1A)
Type4 has in its constructor IType3

I was looking for a tool that shows the above.
On large projects with hundreds of Contracts it is difficult to keep track the above

**Comment by ENikS** [comment]
A good candidate for an Extension but I don't think I'll have time
