### ISSUE TITLE
Please, update unity release.

### ISSUE THREAD

**Issue by llinyu** [unitycontainer/unity#72]
Update unity and commonservicelocator release, please!
Or can where we download new version source directly?

https://github.com/unitycontainer/unity/releases
https://github.com/unitycontainer/commonservicelocator/releases

**Comment by lineker** [comment]
I wonder if this project is dead at this point. Last commit march 2016. Maintainers don't answer questions. This sucks.

**Comment by hangarter** [comment]
Hi guys I'm new to github and I was looking for a project to contribute. This looks like a nice one as I like the way Unity container works and I'm experienced with c#.
How can I start? I just grab an issue and try to fix?

**Comment by llinyu** [comment]
the last update: 2015-10-06
https://www.nuget.org/packages/Unity/4.0.1

but source is not updated.

**Comment by llinyu** [comment]
If you like .net IOC, you should think about Autofac or StructureMap
https://autofac.org
http://structuremap.github.io/

**Comment by Leonardo-Ferreira** [comment]
hey, i think this is active again... there are a bunch of commits going on since early september!

**Comment by ENikS** [comment]
Yes, it is active now

**Comment by ENikS** [comment]
Publishing to Release is part of deployment script now.
