### ISSUE TITLE
RIP Unity

### ISSUE THREAD

**Issue by dellycowboy** [unitycontainer/unity#73]
Thanks for killing Unity MS

**Comment by hangarter** [comment]
Hi guys I'm new to github and I was looking for a project to contribute. This looks like a nice one as I like the way Unity container works and I'm experienced with c#.
How can I start? I just grab an issue and try to fix?

**Comment by martinpinto** [comment]
@hangarter yeah in the open source community it usually works like that. You check out an issue, ask if you can fix it, fix it, then create a pull request. I'm not so sure however if this project is actually being maintained, so before starting to fix something I would ask around.

**Comment by thomaslevesque** [comment]
> Hi guys I'm new to github and I was looking for a project to contribute. This looks like a nice one as I like the way Unity container works and I'm experienced with c#.
> How can I start? I just grab an issue and try to fix?

Well, given that the maintainers have never merged a single pull request, I think you'd be losing your time. Looks like MS gave ownership of this project to someone who doesn't care...

**Comment by ENikS** [comment]
## The King is dead, long live the King!

I will be helping to keep this lib afloat for a while.

# I welcome any help and contributions!

**Comment by thomaslevesque** [comment]
Great news, thanks @ENikS for taking over this project!
I was really sad to see Unity being abandoned so soon after going open source.

**Comment by Mike-EEE** [comment]
A little shout out to @ENikS here:
https://blogs.msdn.microsoft.com/dotnet/2015/08/21/the-future-of-unity/#comment-545865

It would seem to me that The King is just getting started. 😄 👍
