### ISSUE TITLE
Does anyone want to take this project?

### ISSUE THREAD

**Issue by hangarter** [unitycontainer/unity#74]
Hi Guys,

I can see this project is dying but Unity is a very good DI framework. I'm a .net developer myself for some years and would like to contribute. 
Is there a roadmap of any kind or anyone interested in take this project and maintain it?

Cheers

**Comment by Amarok79** [comment]
I'd like to contribute too, mainly performance tweaks, since we started a new project with Unity at its core. Unfortunately, not enough time to take over the this project.

**Comment by hangarter** [comment]
I'd be happy to contribute to it but not sure the developers are active... I want to avoid to create one more fork of it!

**Comment by PhilipDaniels** [comment]
MS has pretty much tossed this over the wall and abandoned it. I'm not sure it is worth investing any time in it at this point, there are better (documented, faster, easier to use, actively maintained) DI frameworks available such as https://github.com/simpleinjector/SimpleInjector

**Comment by llinyu** [comment]
If you like .net IOC, you should think about Autofac or StructureMap
https://autofac.org
http://structuremap.github.io/

**Comment by cordasfilip** [comment]
I still like unity a lot and it works grate with prism, BUT is it really needed any more here is a huge list with some perf stats.
https://github.com/danielpalme/IocPerformance

**Comment by ENikS** [comment]
Done, I am maintaining it for now
