### ISSUE TITLE
Thread Interlocking while Resolving

### ISSUE THREAD

**Issue by jtourvieille** [unitycontainer/unity#77]
Hi,

There is an issue in Unity in the following scenario:
-Create a class referencing another one in its ctor.
-Register this class using PerResolveLifetimeManager.
-Regiser the referenced class using HierarchicalLifetimeManager.
-Resolve the first class (the one marked with PerResolveLifetimeManager) multiple times from different threads.

Sometimes, threads interlock themselves. See the following code to reproduce. Note: it does not happen every time I run the code on my computer. I have to relaunch multiple time to raise the issue.

`class Program
    {
        static void Main(string[] args)
        {
            var container = new UnityContainer();

            container.RegisterType<IClassPerResolveReferencingHierarchical, ClassPerResolveReferencingHierarchical>(
                new PerResolveLifetimeManager());

            container.RegisterType<IClassHierarchical, ClassHierarchical>(
                new HierarchicalLifetimeManager());

            var childContainer = container.CreateChildContainer();

            Parallel.For(0, 1000, i =>
            {
                var resolved = childContainer.Resolve<IClassPerResolveReferencingHierarchical>();
                Console.WriteLine(resolved);
            });

            childContainer.Dispose();
        }
    }

    internal class ClassHierarchical : IClassHierarchical
    {
    }

    public interface IClassHierarchical
    {
    }

    internal class ClassPerResolveReferencingHierarchical : IClassPerResolveReferencingHierarchical
    {
        private readonly IClassHierarchical _classHierarchical;

        public ClassPerResolveReferencingHierarchical(IClassHierarchical classHierarchical)
        {
            _classHierarchical = classHierarchical;
        }
    }

    public interface IClassPerResolveReferencingHierarchical
    {
    }`

Code seems to be freezing in

Microsoft.Practices.Unity.SynchronizedLifetimeManager.GetValue()

`public override object GetValue()
        {
            Monitor.Enter(this.lockObj);
            object result = this.SynchronizedGetValue();
            if (result != null)
            {
                Monitor.Exit(this.lockObj);
            }
            return result;
        }`

**Comment by ENikS** [comment]
This behavior is by design. SynchronizedGetValue() will block until value has been set.

**Comment by ENikS** [comment]
Starting with 5.0.0-beta2 all internal storage is implemented with ConcurrentDictionary. This should take care of the issue.

**Comment by jrummellelite** [comment]
When will this be fixed in the Unity.Abstractions nuget package? The Unity.Mvc and Unity.AspNet.WebApi packages rely on Unity.Abstractions instead of Unity, which contains all assemblies and seems to be updated. Also, this is confusing that the Unity package contains everything instead of referencing the other packages.

**Comment by ENikS** [comment]
https://github.com/unitycontainer/container/blob/v5.x/src/Utility/ConcurrentDictionary.cs
