### ISSUE TITLE
InterceptingRealProxy throws exception when working with transparent proxy.

### ISSUE THREAD

**Issue by voroninp** [unitycontainer/unity#79]
In our custom TearDown  strategy we get property values of dependency via reflection. But with enabled interception [we get](http://stackoverflow.com/q/42147889/921054) an exception `TargetException` : 

> Object does not match target type

when calling  `property.GetValue(transparent_proxy_obj, null)`

**Comment by ENikS** [comment]
Moved to unitycontainer/interception#1
