### ISSUE TITLE
Changed the SN key is a significant breaking change

### ISSUE THREAD

**Issue by SimonCropp** [unitycontainer/unity#8]
3.5.1404: 31bf3856ad364e35
3.5.1406: 6d32ff45e0ccc69f

Changing the SN key of a assembly is a significant breaking change. It means any intermediate assembly that extends unity will not longer be bale to be used until they do a recompile. And after that recompile they will be incompatible with all older versions of unity.

Firstly please unlist 3.5.1406 from nuget to prevent people from wasting time with binding redirects that will not work. 

Then you have two options 

1. Release a new patch with the old SN key. OR
2. Release a new major with the new SN key

**Comment by SimonCropp** [comment]
for some more info as to why http://haacked.com/archive/2012/02/16/changing-a-strong-name-is-a-major-breaking-change.aspx/

**Comment by richardspence** [comment]
+1.  Changing the key shouldn't be done lightly. I think this was introduced because of #6

**Comment by SimonCropp** [comment]
BTW let me know if I can help with a PR to bump the major

**Comment by SimonCropp** [comment]
@richardspence yeah in that context it makes sense that the SN key had to change. So I guess Unity v4 should be released to cope with the required new SN key.

**Comment by pcibraro** [comment]
Simon, I know, this is unfortunate but I did not have other options. I'm willing to do whatever works better for you guys. Thanks

**Comment by SimonCropp** [comment]
@pcibraro so unlist 3.5.1406 and release a 4.0?

**Comment by pcibraro** [comment]
Ok, I will do that. Thanks

**Comment by SimonCropp** [comment]
@pcibraro thanks for the prompt response. let me know if u need a smoke test of the nuget.

**Comment by adamralph** [comment]
Whilst you are there, why not drop the strong naming?

**Comment by pcibraro** [comment]
I wish I could drop it. People complained they need the assemblies signed. I will work on getting a different nuget without strong signed assemblies.

**Comment by pcibraro** [comment]
The version for the assemblies and packages have been updated to 4.0.0 now.
