### ISSUE TITLE
Upgrade to .netstandard 2.0, asp.net core 2.0 and entity framework core 2.0

### ISSUE THREAD

**Issue by ghd258** [unitycontainer/unity#89]
Upgrade to .netstandard 2.0, asp.net core 2.0 and entity framework core 2.0

**Comment by ENikS** [comment]
Next Unity will be released with support for .NET Standard 1.0. It is much lower denominator than 2.0 and supported by more platforms.

Any Core/Standard 2.0 applications will be able to link to it directly.
