### ISSUE TITLE
Make versions consistent

### ISSUE THREAD

**Issue by SimonCropp** [unitycontainer/unity#9]
Currently 

 * nuget 3.5.1406 = assembly version 3.5.1
 * nuget 3.5.1404 = assembly version 3.5.0

If you are going to change the assembly version in every release you may as well have it match the nuget version. it will save people extra effort in mapping between versions when managing references and binding redirects.

**Comment by pcibraro** [comment]
The version for the assemblies and packages have been updated to 4.0.0 now.

**Comment by SimonCropp** [comment]
@pcibraro thanks again
