### ISSUE TITLE
Resolution Mix-Up with Async methods

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [unitycontainer/unity#97]
I noticed that on regular Asp.Net apps (.net framework and runtime 4.5 for example) if you try to resolve a per-request registration, you might end up with the object of another request... 

I came to this conclusion debugging a intermittent bug: entity framework was recurrently throwing exceptions stating that the foreign key was not being obliged. 
I noticed this because I register a EF Context for each request, and they are specific to the end-user that sprung the current request. Then I started logging the current user for the operation and the target database. 
Noticing the eventual discrepancy, i started logging the EF context registration, and 100% of the cases was as expected. Then i noticed that the EF mix up was not random: the mix up happened only with concurrent requests, meaning, if user X was not executing a request (reading an article for example), the exception would never point to user X database...

Digging down, i came up with a "why don't I try this" test: if i resolved all the dependencies on the constructor, this wouldn't happen. Turns out i was right.

**Comment by ENikS** [comment]
Thank you for the info. Is there anything that you feel needs to be fixed?

**Comment by Leonardo-Ferreira** [comment]
Well... i'm dealing with a pretty huge app here... i've managed to cover only 30% of the code so far... having the container not mixing up this would be great. Being constructor injection the correct modus-operandi for DI, I would love to not being obligated to refactor a huge call-tree every time i want to make a method async...

**Comment by ENikS** [comment]
Would using **PerThreadLifetimeManager** help in your case?

**Comment by Leonardo-Ferreira** [comment]
what if the async method resumes on a different thread?

**Comment by ENikS** [comment]
All of these situations are covered in new Microsoft.Extensions.DependencyInjection spec.
I am working on implementing the spec and releasing it in [5.0.0](https://github.com/unitycontainer/unity/tree/master/src/Unity.Microsoft.DependencyInjection). Still in early stages of the development. Please check back in a week or two.

**Comment by ENikS** [comment]
Merge with #1

**Comment by ENikS** [comment]
Will close for now, will reopen if problem persists
